const unidades = [
    {codigo_unidad_medida: 'kg', nombre_unidad: 'kilogramo'},
    {codigo_unidad_medida: 'gr', nombre_unidad: 'gramo'},
    {codigo_unidad_medida: 'mg', nombre_unidad: 'miligramo'},
    {codigo_unidad_medida: 'lb', nombre_unidad: 'libra'},
    {codigo_unidad_medida: 'un', nombre_unidad: 'unidad'},
    {codigo_unidad_medida: 'pq', nombre_unidad: 'paquete'},
    {codigo_unidad_medida: 'lt', nombre_unidad: 'litro'},
    {codigo_unidad_medida: 'ml', nombre_unidad: 'mililitro'},
    {codigo_unidad_medida: 'oz', nombre_unidad: 'onza'}
    
]

const tipo_usuarios = [
    {tipo_usuario: 'hunter (cazador)'},
    {tipo_usuario: 'challenger (cliente)'},
    {tipo_usuario: 'admin (administrador)'},
    {tipo_usuario: 'retailer (tienda / distribuidor)'},
]

const familias = [
    {nombre_familia: "Almacén"},
    {nombre_familia: "Frescos"},
    {nombre_familia: "Bebidas"},
]

const categorias = [
    {nombre_categoria: "Aceites_y_Aderezos" , familiumId: 1},
    {nombre_categoria: "Aceitunas_y_Encurtidos" , familiumId: 1},
    {nombre_categoria: "Conservas" , familiumId: 1},
    {nombre_categoria: "Desayuno_y_Golosinas" , familiumId: 1},
    {nombre_categoria: "Panificados" , familiumId: 1},
    {nombre_categoria: "Arroz_y_Legumbres" , familiumId: 1},
    {nombre_categoria: "Snacks" , familiumId: 1},
    {nombre_categoria: "Sopas,_Caldos_y_Puré" , familiumId: 1},
    {nombre_categoria: "Pastas_y_Harinas" , familiumId: 1},
    {nombre_categoria: "Lácteos" , familiumId: 2},
    {nombre_categoria: "Pastas y Tapas" , familiumId: 2},
    {nombre_categoria: "Carnicería y Pescadería" , familiumId: 2},
    {nombre_categoria: "Verdulería" , familiumId: 2},
    {nombre_categoria: "Fiambrería" , familiumId: 2},
    {nombre_categoria: "Congelados" , familiumId: 2},
    {nombre_categoria: "Panadería y Repostería" , familiumId: 2},
    {nombre_categoria: "Aperitivos" , familiumId: 3},
    {nombre_categoria: "Cerveza" , familiumId: 3},
    {nombre_categoria: "Vinos y Espumantes" , familiumId: 3},
    {nombre_categoria: "Bebidas blancas y Licores" , familiumId: 3},
    {nombre_categoria: "A Base de Hierbas" , familiumId: 3},
    {nombre_categoria: "Aguas" , familiumId: 3},
    {nombre_categoria: "Gaseosas" , familiumId: 3},
    {nombre_categoria: "Jugos" , familiumId: 3},
    {nombre_categoria: "Isotónicas y Energizantes" , familiumId: 3},
]

const subcategoria =[
    {nombre_subcategoria: "Aceites" , categoriumId: 1},
    {nombre_subcategoria: "Mayonesa" , categoriumId: 1},
    {nombre_subcategoria: "Ketchup" , categoriumId: 1},
    {nombre_subcategoria: "Salsa_Golf" , categoriumId: 1},
    {nombre_subcategoria: "Mostaza" , categoriumId: 1},
    {nombre_subcategoria: "Vinagre" , categoriumId: 1},
    {nombre_subcategoria: "Aceto" , categoriumId: 1},
    {nombre_subcategoria: "Jugo_de_Limón" , categoriumId: 1},
    {nombre_subcategoria: "Aderezos_Salsas" , categoriumId: 1},
    {nombre_subcategoria: "Sal_y_Pimienta" , categoriumId: 1},
    {nombre_subcategoria: "Saborizadores" , categoriumId: 1},
    {nombre_subcategoria: "Otros_Condimentos" , categoriumId: 1},
    {nombre_subcategoria: "Aceitunas_Verdes" , categoriumId: 2},
    {nombre_subcategoria: "Aceitunas_Negras" , categoriumId: 2},
    {nombre_subcategoria: "Aceitunas_Rellenas" , categoriumId: 2} , 
    {nombre_subcategoria: "Encurtidos" , categoriumId: 2},
    {nombre_subcategoria: "Conservas_de_Verdura_y_Legumbres" , categoriumId: 3},
    {nombre_subcategoria: "Conservas_de_Pescado" , categoriumId: 3},
    {nombre_subcategoria: "Conservas_de_Frutas" , categoriumId: 3},
    {nombre_subcategoria: "Tomates_y_Salsas" , categoriumId: 3},
    {nombre_subcategoria: "Azúcar_y_Edulcorante" , categoriumId: 4},
    {nombre_subcategoria: "Cacao" , categoriumId: 4},
    {nombre_subcategoria: "Leche_en_Polvo" , categoriumId: 4},
    {nombre_subcategoria: "Mermeladas_y_Dulces" , categoriumId: 4},
    {nombre_subcategoria: "Café" , categoriumId: 4},
    {nombre_subcategoria: "Té" , categoriumId: 4},
    {nombre_subcategoria: "Yerbas" , categoriumId: 4},
    {nombre_subcategoria: "Repostería" , categoriumId: 4},
    {nombre_subcategoria: "Golosinas" , categoriumId: 4},
    {nombre_subcategoria: "Cereales" , categoriumId: 4},
    {nombre_subcategoria: "Galletitas_Dulces" , categoriumId: 4},
    {nombre_subcategoria: "Galletitas_Saladas" , categoriumId: 4},
    {nombre_subcategoria: "Galletitas_de_Arroz" , categoriumId: 4},
    {nombre_subcategoria: "Pan_Árabe_y_Otros" , categoriumId: 5},
    {nombre_subcategoria: "Pan_de_Molde" , categoriumId: 5},
    {nombre_subcategoria: "Pan_de_Hamburguesas_y_Panchos" , categoriumId: 5},
    {nombre_subcategoria: "Pan_Rallado_y_Rebozadores" , categoriumId: 5},
    {nombre_subcategoria: "Tostadas" , categoriumId: 5},
    {nombre_subcategoria: "Budines_y_Otros" , categoriumId: 5},
    {nombre_subcategoria: "Prepizzas" , categoriumId: 5},
    {nombre_subcategoria: "Madalenas" , categoriumId: 5},
    {nombre_subcategoria: "Arroz_Largo" , categoriumId: 6},
    {nombre_subcategoria: "Arroz_Parboil" , categoriumId: 6},
    {nombre_subcategoria: "Arroz_Doble" , categoriumId: 6},
    {nombre_subcategoria: "Arroz_Integral" , categoriumId: 6},
    {nombre_subcategoria: "Arroz_Especial" , categoriumId: 6},
    {nombre_subcategoria: "Arroz_Preparado" , categoriumId: 6},
    {nombre_subcategoria: "Legumbres" , categoriumId: 6},
    {nombre_subcategoria: "Papas_Fritas" , categoriumId: 7},
    {nombre_subcategoria: "Chizitos" , categoriumId: 7},
    {nombre_subcategoria: "Maní" , categoriumId: 7},
    {nombre_subcategoria: "Palitos" , categoriumId: 7},
    {nombre_subcategoria: "Tortillas" , categoriumId: 7},
    {nombre_subcategoria: "Pochoclos" , categoriumId: 7},
    {nombre_subcategoria: "Conos" , categoriumId: 7},
    {nombre_subcategoria: "Snacks_Mix" , categoriumId: 7},
    {nombre_subcategoria: "Frutas_Secas" , categoriumId: 7},
    {nombre_subcategoria: "Sopas" , categoriumId: 8},
    {nombre_subcategoria: "Caldos" , categoriumId: 8},
    {nombre_subcategoria: "Puré" , categoriumId: 8},
    {nombre_subcategoria: "Pastas" , categoriumId: 9},
    {nombre_subcategoria: "Harinas" , categoriumId: 9},
    {nombre_subcategoria: "Leches" , categoriumId: 10},
    {nombre_subcategoria: "Leches infantiles" , categoriumId: 10},
    {nombre_subcategoria: "Yogures" , categoriumId: 10},
    {nombre_subcategoria: "Cremas de Leche" , categoriumId: 10},
    {nombre_subcategoria: "Dulce de Leche" , categoriumId: 10},
    {nombre_subcategoria: "Levaduras y Grasas" , categoriumId: 10},
    {nombre_subcategoria: "Mantecas y Margarinas" , categoriumId: 10},
    {nombre_subcategoria: "Postres y Flanes" , categoriumId: 10},
    {nombre_subcategoria: "Ricota" , categoriumId: 10},
    {nombre_subcategoria: "Quesos Untables" , categoriumId: 10},
    {nombre_subcategoria: "Fideos" , categoriumId: 11},
    {nombre_subcategoria: "Ñoquis" , categoriumId: 11},
    {nombre_subcategoria: "Pastas Rellenas" , categoriumId: 11},
    {nombre_subcategoria: "Tapas de Tarta" , categoriumId: 11},
    {nombre_subcategoria: "Tapas de Empanadas" , categoriumId: 11},
    {nombre_subcategoria: "Otras Tapas" , categoriumId: 11},
    {nombre_subcategoria: "Carne de cerdo" , categoriumId: 12},
    {nombre_subcategoria: "Carne Vacuna" , categoriumId: 12},
    {nombre_subcategoria: "Carnes Preparadas" , categoriumId: 12},
    {nombre_subcategoria: "Embutidos" , categoriumId: 12},
    {nombre_subcategoria: "Pollo" , categoriumId: 12},
    {nombre_subcategoria: "Huevos" , categoriumId: 12},
    {nombre_subcategoria: "Pescados y Mariscos" , categoriumId: 12},
    {nombre_subcategoria: "Carbón, Leña y Encendido" , categoriumId: 12},
    {nombre_subcategoria: "Granja" , categoriumId: 12},
    {nombre_subcategoria: "Frutas" , categoriumId: 13},
    {nombre_subcategoria: "Frutas Secas y Desecadas" , categoriumId: 13},
    {nombre_subcategoria: "Verduras" , categoriumId: 13},
    {nombre_subcategoria: "Fiambres" , categoriumId: 14},
    {nombre_subcategoria: "Salchichas" , categoriumId: 14},
    {nombre_subcategoria: "Quesos Blandos" , categoriumId: 14},
    {nombre_subcategoria: "Quesos Semiduros" , categoriumId: 14},
    {nombre_subcategoria: "Quesos Duros" , categoriumId: 14},
    {nombre_subcategoria: "Quesos Rallados" , categoriumId: 14},
    {nombre_subcategoria: "Dulces" , categoriumId: 14},
    {nombre_subcategoria: "Quesos Especiales" , categoriumId: 14},
    {nombre_subcategoria: "Hamburguesas" , categoriumId: 15},
    {nombre_subcategoria: "Papas" , categoriumId: 15},
    {nombre_subcategoria: "Milanesas de Soja" , categoriumId: 15},
    {nombre_subcategoria: "Prefritos" , categoriumId: 15},
    {nombre_subcategoria: "Vegetales" , categoriumId: 15},
    {nombre_subcategoria: "Comidas Preparadas" , categoriumId: 15},
    {nombre_subcategoria: "Pizzas" , categoriumId: 15},
    {nombre_subcategoria: "Helados" , categoriumId: 15},
    {nombre_subcategoria: "Frutas" , categoriumId: 15},
    {nombre_subcategoria: "Donuts" , categoriumId: 16},
    {nombre_subcategoria: "Facturería" , categoriumId: 16},
    {nombre_subcategoria: "Galletitas, alfajores y panes dulces" , categoriumId: 16},
    {nombre_subcategoria: "Panificados" , categoriumId: 16},
    {nombre_subcategoria: "Piononos, budines y madalenas" , categoriumId: 16},
    {nombre_subcategoria: "Sandwichería" , categoriumId: 16},
    {nombre_subcategoria: "Tortas y tartas" , categoriumId: 16},
    {nombre_subcategoria: "Americano" , categoriumId: 17},
    {nombre_subcategoria: "Fernet" , categoriumId: 17},
    {nombre_subcategoria: "Otros Aperitivos" , categoriumId: 17},
    {nombre_subcategoria: "Negras y Rojas" , categoriumId: 18},
    {nombre_subcategoria: "Rubias" , categoriumId: 18},
    {nombre_subcategoria: "Sin Alcohol" , categoriumId: 18},
    {nombre_subcategoria: "Espumantes" , categoriumId: 19},
    {nombre_subcategoria: "Vino Blanco" , categoriumId: 19},
    {nombre_subcategoria: "Vino Rosado" , categoriumId: 19},
    {nombre_subcategoria: "Vino Tinto" , categoriumId: 19},
    {nombre_subcategoria: "Bebidas Blancas" , categoriumId: 20},
    {nombre_subcategoria: "Licores" , categoriumId: 20},
    {nombre_subcategoria: "Whiskys" , categoriumId: 20},
    {nombre_subcategoria: "Amargos" , categoriumId: 21},
    {nombre_subcategoria: "Agua Con Gas" , categoriumId: 22},
    {nombre_subcategoria: "Agua Saborizada" , categoriumId: 22},
    {nombre_subcategoria: "Agua Sin Gas" , categoriumId: 22},
    {nombre_subcategoria: "Cola" , categoriumId: 23},
    {nombre_subcategoria: "Gaseosa de Naranja" , categoriumId: 23},
    {nombre_subcategoria: "Gaseosa Sabor Pomelo" , categoriumId: 23},
    {nombre_subcategoria: "Lima Limón" , categoriumId: 23},
    {nombre_subcategoria: "Otras Gaseosas" , categoriumId: 23},
    {nombre_subcategoria: "Tónica" , categoriumId: 23},
    {nombre_subcategoria: "Jugos Concentrados" , categoriumId: 24},
    {nombre_subcategoria: "Jugos en Polvo" , categoriumId: 24},
    {nombre_subcategoria: "Jugos Listos" , categoriumId: 24},
    {nombre_subcategoria: "Jugos Refrigerados" , categoriumId: 24},
    {nombre_subcategoria: "Energizantes" , categoriumId: 25},
    {nombre_subcategoria: "Isotónicas" , categoriumId: 25},
]

const productos =[
    {nombre: "arroz" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId:42},
    {nombre: "papa" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId: 90},
    {nombre: "leche_normal" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "lt" , subcategoriumId: 63},
    {nombre: "huevos" , contenido_neto: 30 ,unidadMedidaCodigoUnidadMedida: "un" , subcategoriumId: 84},
    {nombre: "harina_trigo" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId: 62},
    {nombre: "café" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId: 25},
    {nombre: "pan_tajado" , contenido_neto: 400 ,unidadMedidaCodigoUnidadMedida: "gr" , subcategoriumId: 35},
    {nombre: "azucar" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId: 21},
    {nombre: "sal" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId: 10}
    
]


// const desafios =[
    
// ]


module.exports = {unidades, tipo_usuarios, familias, categorias, subcategoria, productos};

