const unidades = [
    {codigo_unidad_medida: 'kg', nombre_unidad: 'kilogramo'},
    {codigo_unidad_medida: 'gr', nombre_unidad: 'gramo'},
    {codigo_unidad_medida: 'mg', nombre_unidad: 'miligramo'},
    {codigo_unidad_medida: 'lb', nombre_unidad: 'libra'},
    {codigo_unidad_medida: 'un', nombre_unidad: 'unidad'},
    {codigo_unidad_medida: 'pq', nombre_unidad: 'paquete'},
    {codigo_unidad_medida: 'lt', nombre_unidad: 'litro'},
    {codigo_unidad_medida: 'ml', nombre_unidad: 'mililitro'},
    {codigo_unidad_medida: 'oz', nombre_unidad: 'onza'}
    
]

const tipo_usuarios = [
    {tipo_usuario: 'hunter (cazador)'},
    {tipo_usuario: 'challenger (cliente)'},
    {tipo_usuario: 'admin (administrador)'},
    {tipo_usuario: 'retailer (tienda / distribuidor)'},
]

const familias = [
    {nombre_familia: "Almacén"},
    {nombre_familia: "Frescos"},
    {nombre_familia: "Bebidas"},
]

const categorias = [
    {nombre_categoria: "Aceites_y_Aderezos" , familiumId: 1},
    {nombre_categoria: "Aceitunas_y_Encurtidos" , familiumId: 1},
    {nombre_categoria: "Conservas" , familiumId: 1},
    {nombre_categoria: "Desayuno_y_Golosinas" , familiumId: 1},
    {nombre_categoria: "Panificados" , familiumId: 1},
    {nombre_categoria: "Arroz_y_Legumbres" , familiumId: 1},
    {nombre_categoria: "Snacks" , familiumId: 1},
    {nombre_categoria: "Sopas,_Caldos_y_Puré" , familiumId: 1},
    {nombre_categoria: "Pastas_y_Harinas" , familiumId: 1},
    {nombre_categoria: "Lácteos" , familiumId: 2},
    {nombre_categoria: "Pastas y Tapas" , familiumId: 2},
    {nombre_categoria: "Carnicería y Pescadería" , familiumId: 2},
    {nombre_categoria: "Verdulería" , familiumId: 2},
    {nombre_categoria: "Fiambrería" , familiumId: 2},
    {nombre_categoria: "Congelados" , familiumId: 2},
    {nombre_categoria: "Panadería y Repostería" , familiumId: 2},
    {nombre_categoria: "Aperitivos" , familiumId: 3},
    {nombre_categoria: "Cerveza" , familiumId: 3},
    {nombre_categoria: "Vinos y Espumantes" , familiumId: 3},
    {nombre_categoria: "Bebidas blancas y Licores" , familiumId: 3},
    {nombre_categoria: "A Base de Hierbas" , familiumId: 3},
    {nombre_categoria: "Aguas" , familiumId: 3},
    {nombre_categoria: "Gaseosas" , familiumId: 3},
    {nombre_categoria: "Jugos" , familiumId: 3},
    {nombre_categoria: "Isotónicas y Energizantes" , familiumId: 3},
]

const subcategoria =[
    {nombre_subcategoria: "Aceites" , categoriumId: 1},
    {nombre_subcategoria: "Mayonesa" , categoriumId: 1},
    {nombre_subcategoria: "Ketchup" , categoriumId: 1},
    {nombre_subcategoria: "Salsa_Golf" , categoriumId: 1},
    {nombre_subcategoria: "Mostaza" , categoriumId: 1},
    {nombre_subcategoria: "Vinagre" , categoriumId: 1},
    {nombre_subcategoria: "Aceto" , categoriumId: 1},
    {nombre_subcategoria: "Jugo_de_Limón" , categoriumId: 1},
    {nombre_subcategoria: "Aderezos_Salsas" , categoriumId: 1},
    {nombre_subcategoria: "Sal_y_Pimienta" , categoriumId: 1},
    {nombre_subcategoria: "Saborizadores" , categoriumId: 1},
    {nombre_subcategoria: "Otros_Condimentos" , categoriumId: 1},
    {nombre_subcategoria: "Aceitunas_Verdes" , categoriumId: 2},
    {nombre_subcategoria: "Aceitunas_Negras" , categoriumId: 2},
    {nombre_subcategoria: "Aceitunas_Rellenas" , categoriumId: 2} , 
    {nombre_subcategoria: "Encurtidos" , categoriumId: 2},
    {nombre_subcategoria: "Conservas_de_Verdura_y_Legumbres" , categoriumId: 3},
    {nombre_subcategoria: "Conservas_de_Pescado" , categoriumId: 3},
    {nombre_subcategoria: "Conservas_de_Frutas" , categoriumId: 3},
    {nombre_subcategoria: "Tomates_y_Salsas" , categoriumId: 3},
    {nombre_subcategoria: "Azúcar_y_Edulcorante" , categoriumId: 4},
    {nombre_subcategoria: "Cacao" , categoriumId: 4},
    {nombre_subcategoria: "Leche_en_Polvo" , categoriumId: 4},
    {nombre_subcategoria: "Mermeladas_y_Dulces" , categoriumId: 4},
    {nombre_subcategoria: "Café" , categoriumId: 4},
    {nombre_subcategoria: "Té" , categoriumId: 4},
    {nombre_subcategoria: "Yerbas" , categoriumId: 4},
    {nombre_subcategoria: "Repostería" , categoriumId: 4},
    {nombre_subcategoria: "Golosinas" , categoriumId: 4},
    {nombre_subcategoria: "Cereales" , categoriumId: 4},
    {nombre_subcategoria: "Galletitas_Dulces" , categoriumId: 4},
    {nombre_subcategoria: "Galletitas_Saladas" , categoriumId: 4},
    {nombre_subcategoria: "Galletitas_de_Arroz" , categoriumId: 4},
    {nombre_subcategoria: "Pan_Árabe_y_Otros" , categoriumId: 5},
    {nombre_subcategoria: "Pan_de_Molde" , categoriumId: 5},
    {nombre_subcategoria: "Pan_de_Hamburguesas_y_Panchos" , categoriumId: 5},
    {nombre_subcategoria: "Pan_Rallado_y_Rebozadores" , categoriumId: 5},
    {nombre_subcategoria: "Tostadas" , categoriumId: 5},
    {nombre_subcategoria: "Budines_y_Otros" , categoriumId: 5},
    {nombre_subcategoria: "Prepizzas" , categoriumId: 5},
    {nombre_subcategoria: "Madalenas" , categoriumId: 5},
    {nombre_subcategoria: "Arroz_Largo" , categoriumId: 6},
    {nombre_subcategoria: "Arroz_Parboil" , categoriumId: 6},
    {nombre_subcategoria: "Arroz_Doble" , categoriumId: 6},
    {nombre_subcategoria: "Arroz_Integral" , categoriumId: 6},
    {nombre_subcategoria: "Arroz_Especial" , categoriumId: 6},
    {nombre_subcategoria: "Arroz_Preparado" , categoriumId: 6},
    {nombre_subcategoria: "Legumbres" , categoriumId: 6},
    {nombre_subcategoria: "Papas_Fritas" , categoriumId: 7},
    {nombre_subcategoria: "Chizitos" , categoriumId: 7},
    {nombre_subcategoria: "Maní" , categoriumId: 7},
    {nombre_subcategoria: "Palitos" , categoriumId: 7},
    {nombre_subcategoria: "Tortillas" , categoriumId: 7},
    {nombre_subcategoria: "Pochoclos" , categoriumId: 7},
    {nombre_subcategoria: "Conos" , categoriumId: 7},
    {nombre_subcategoria: "Snacks_Mix" , categoriumId: 7},
    {nombre_subcategoria: "Frutas_Secas" , categoriumId: 7},
    {nombre_subcategoria: "Sopas" , categoriumId: 8},
    {nombre_subcategoria: "Caldos" , categoriumId: 8},
    {nombre_subcategoria: "Puré" , categoriumId: 8},
    {nombre_subcategoria: "Pastas" , categoriumId: 9},
    {nombre_subcategoria: "Harinas" , categoriumId: 9},
    {nombre_subcategoria: "Leches" , categoriumId: 10},
    {nombre_subcategoria: "Leches infantiles" , categoriumId: 10},
    {nombre_subcategoria: "Yogures" , categoriumId: 10},
    {nombre_subcategoria: "Cremas de Leche" , categoriumId: 10},
    {nombre_subcategoria: "Dulce de Leche" , categoriumId: 10},
    {nombre_subcategoria: "Levaduras y Grasas" , categoriumId: 10},
    {nombre_subcategoria: "Mantecas y Margarinas" , categoriumId: 10},
    {nombre_subcategoria: "Postres y Flanes" , categoriumId: 10},
    {nombre_subcategoria: "Ricota" , categoriumId: 10},
    {nombre_subcategoria: "Quesos Untables" , categoriumId: 10},
    {nombre_subcategoria: "Fideos" , categoriumId: 11},
    {nombre_subcategoria: "Ñoquis" , categoriumId: 11},
    {nombre_subcategoria: "Pastas Rellenas" , categoriumId: 11},
    {nombre_subcategoria: "Tapas de Tarta" , categoriumId: 11},
    {nombre_subcategoria: "Tapas de Empanadas" , categoriumId: 11},
    {nombre_subcategoria: "Otras Tapas" , categoriumId: 11},
    {nombre_subcategoria: "Carne de cerdo" , categoriumId: 12},
    {nombre_subcategoria: "Carne Vacuna" , categoriumId: 12},
    {nombre_subcategoria: "Carnes Preparadas" , categoriumId: 12},
    {nombre_subcategoria: "Embutidos" , categoriumId: 12},
    {nombre_subcategoria: "Pollo" , categoriumId: 12},
    {nombre_subcategoria: "Huevos" , categoriumId: 12},
    {nombre_subcategoria: "Pescados y Mariscos" , categoriumId: 12},
    {nombre_subcategoria: "Carbón, Leña y Encendido" , categoriumId: 12},
    {nombre_subcategoria: "Granja" , categoriumId: 12},
    {nombre_subcategoria: "Frutas" , categoriumId: 13},
    {nombre_subcategoria: "Frutas Secas y Desecadas" , categoriumId: 13},
    {nombre_subcategoria: "Verduras" , categoriumId: 13},
    {nombre_subcategoria: "Fiambres" , categoriumId: 14},
    {nombre_subcategoria: "Salchichas" , categoriumId: 14},
    {nombre_subcategoria: "Quesos Blandos" , categoriumId: 14},
    {nombre_subcategoria: "Quesos Semiduros" , categoriumId: 14},
    {nombre_subcategoria: "Quesos Duros" , categoriumId: 14},
    {nombre_subcategoria: "Quesos Rallados" , categoriumId: 14},
    {nombre_subcategoria: "Dulces" , categoriumId: 14},
    {nombre_subcategoria: "Quesos Especiales" , categoriumId: 14},
    {nombre_subcategoria: "Hamburguesas" , categoriumId: 15},
    {nombre_subcategoria: "Papas" , categoriumId: 15},
    {nombre_subcategoria: "Milanesas de Soja" , categoriumId: 15},
    {nombre_subcategoria: "Prefritos" , categoriumId: 15},
    {nombre_subcategoria: "Vegetales" , categoriumId: 15},
    {nombre_subcategoria: "Comidas Preparadas" , categoriumId: 15},
    {nombre_subcategoria: "Pizzas" , categoriumId: 15},
    {nombre_subcategoria: "Helados" , categoriumId: 15},
    {nombre_subcategoria: "Frutas" , categoriumId: 15},
    {nombre_subcategoria: "Donuts" , categoriumId: 16},
    {nombre_subcategoria: "Facturería" , categoriumId: 16},
    {nombre_subcategoria: "Galletitas, alfajores y panes dulces" , categoriumId: 16},
    {nombre_subcategoria: "Panificados" , categoriumId: 16},
    {nombre_subcategoria: "Piononos, budines y madalenas" , categoriumId: 16},
    {nombre_subcategoria: "Sandwichería" , categoriumId: 16},
    {nombre_subcategoria: "Tortas y tartas" , categoriumId: 16},
    {nombre_subcategoria: "Americano" , categoriumId: 17},
    {nombre_subcategoria: "Fernet" , categoriumId: 17},
    {nombre_subcategoria: "Otros Aperitivos" , categoriumId: 17},
    {nombre_subcategoria: "Negras y Rojas" , categoriumId: 18},
    {nombre_subcategoria: "Rubias" , categoriumId: 18},
    {nombre_subcategoria: "Sin Alcohol" , categoriumId: 18},
    {nombre_subcategoria: "Espumantes" , categoriumId: 19},
    {nombre_subcategoria: "Vino Blanco" , categoriumId: 19},
    {nombre_subcategoria: "Vino Rosado" , categoriumId: 19},
    {nombre_subcategoria: "Vino Tinto" , categoriumId: 19},
    {nombre_subcategoria: "Bebidas Blancas" , categoriumId: 20},
    {nombre_subcategoria: "Licores" , categoriumId: 20},
    {nombre_subcategoria: "Whiskys" , categoriumId: 20},
    {nombre_subcategoria: "Amargos" , categoriumId: 21},
    {nombre_subcategoria: "Agua Con Gas" , categoriumId: 22},
    {nombre_subcategoria: "Agua Saborizada" , categoriumId: 22},
    {nombre_subcategoria: "Agua Sin Gas" , categoriumId: 22},
    {nombre_subcategoria: "Cola" , categoriumId: 23},
    {nombre_subcategoria: "Gaseosa de Naranja" , categoriumId: 23},
    {nombre_subcategoria: "Gaseosa Sabor Pomelo" , categoriumId: 23},
    {nombre_subcategoria: "Lima Limón" , categoriumId: 23},
    {nombre_subcategoria: "Otras Gaseosas" , categoriumId: 23},
    {nombre_subcategoria: "Tónica" , categoriumId: 23},
    {nombre_subcategoria: "Jugos Concentrados" , categoriumId: 24},
    {nombre_subcategoria: "Jugos en Polvo" , categoriumId: 24},
    {nombre_subcategoria: "Jugos Listos" , categoriumId: 24},
    {nombre_subcategoria: "Jugos Refrigerados" , categoriumId: 24},
    {nombre_subcategoria: "Energizantes" , categoriumId: 25},
    {nombre_subcategoria: "Isotónicas" , categoriumId: 25},
]

const productos =[
    {nombre: "arroz" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId:42},
    {nombre: "papa" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId: 90},
    {nombre: "leche_normal" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "lt" , subcategoriumId: 63},
    {nombre: "huevos" , contenido_neto: 30 ,unidadMedidaCodigoUnidadMedida: "un" , subcategoriumId: 84},
    {nombre: "harina_trigo" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId: 62},
    {nombre: "café" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId: 25},
    {nombre: "pan_tajado" , contenido_neto: 400 ,unidadMedidaCodigoUnidadMedida: "gr" , subcategoriumId: 35},
    {nombre: "azucar" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId: 21},
    {nombre: "sal" , contenido_neto: 1 ,unidadMedidaCodigoUnidadMedida: "kg" , subcategoriumId: 10}
    
]


const desafios =[
    {nombre_desafio: "canasta familiar arroz" , descripcion_desafio: "comparte los precios de los productos con tu comunidad  para beneficio de todos" ,id_producto: 1 , Id_cliente: 1 , url_image: "https://www.latinflores.com/imagenes/productos/CANAVI004_L.jpg" , fecha_inicial: [2021, 06, 10] ,fecha_final:  [2021, 12, 31]},
    {nombre_desafio: "canasta familiar papa" , descripcion_desafio: "comparte los precios de los productos con tu comunidad  para beneficio de todos" ,id_producto: 2 , Id_cliente: 1 , url_image: "https://www.latinflores.com/imagenes/productos/CANAVI004_L.jpg" , fecha_inicial: [2021, 06, 10] ,fecha_final:  [2021, 12, 31]},
    {nombre_desafio: "canasta familiar leche_normal" , descripcion_desafio: "comparte los precios de los productos con tu comunidad  para beneficio de todos" ,id_producto: 3 , Id_cliente: 1 , url_image: "https://www.latinflores.com/imagenes/productos/CANAVI004_L.jpg" , fecha_inicial: [2021, 06, 10] ,fecha_final:  [2021, 12, 31]},
    {nombre_desafio: "canasta familiar huevos" , descripcion_desafio: "comparte los precios de los productos con tu comunidad  para beneficio de todos" ,id_producto: 4 , Id_cliente: 1 , url_image: "https://www.latinflores.com/imagenes/productos/CANAVI004_L.jpg" , fecha_inicial: [2021, 06, 10] ,fecha_final:  [2021, 12, 31]},
    {nombre_desafio: "canasta familiar harina_trigo" , descripcion_desafio: "comparte los precios de los productos con tu comunidad  para beneficio de todos" ,id_producto: 5 , Id_cliente: 1 , url_image: "https://www.latinflores.com/imagenes/productos/CANAVI004_L.jpg" , fecha_inicial: [2021, 06, 10] ,fecha_final:  [2021, 12, 31]},
    {nombre_desafio: "canasta familiar café" , descripcion_desafio: "comparte los precios de los productos con tu comunidad  para beneficio de todos" ,id_producto: 6 , Id_cliente: 1 , url_image: "https://www.latinflores.com/imagenes/productos/CANAVI004_L.jpg" , fecha_inicial: [2021, 06, 10] ,fecha_final:  [2021, 12, 31]},
    {nombre_desafio: "canasta familiar pan_tajado" , descripcion_desafio: "comparte los precios de los productos con tu comunidad  para beneficio de todos" ,id_producto: 7 , Id_cliente: 1 , url_image: "https://www.latinflores.com/imagenes/productos/CANAVI004_L.jpg" , fecha_inicial: [2021, 06, 10] ,fecha_final:  [2021, 12, 31]},
    {nombre_desafio: "canasta familiar azucar" , descripcion_desafio: "comparte los precios de los productos con tu comunidad  para beneficio de todos" ,id_producto: 8 , Id_cliente: 1 , url_image: "https://www.latinflores.com/imagenes/productos/CANAVI004_L.jpg" , fecha_inicial: [2021, 06, 10] ,fecha_final:  [2021, 12, 31]},
    {nombre_desafio: "canasta familiar sal" , descripcion_desafio: "comparte los precios de los productos con tu comunidad  para beneficio de todos" ,id_producto: 9 , Id_cliente: 1 , url_image: "https://www.latinflores.com/imagenes/productos/CANAVI004_L.jpg" , fecha_inicial: [2021, 06, 10] ,fecha_final:  [2021, 12, 31]},
]

const detalle_desafios =[
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 1 ,id_desafio: 1},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 2 ,id_desafio: 1},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 9 ,id_desafio: 1},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 19 ,id_desafio: 1},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 25 ,id_desafio: 1},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 1 ,id_desafio: 2},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 2 ,id_desafio: 2},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 9 ,id_desafio: 2},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 19 ,id_desafio: 2},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 25 ,id_desafio: 2},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 1 ,id_desafio: 3},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 2 ,id_desafio: 3},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 9 ,id_desafio: 3},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 19 ,id_desafio: 3},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 25 ,id_desafio: 3},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 1 ,id_desafio: 4},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 2 ,id_desafio: 4},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 9 ,id_desafio: 4},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 19 ,id_desafio: 4},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 25 ,id_desafio: 4},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 1 ,id_desafio: 5},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 2 ,id_desafio: 5},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 9 ,id_desafio: 5},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 19 ,id_desafio: 5},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 25 ,id_desafio: 5},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 25 ,id_desafio: 6},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 1 ,id_desafio: 6},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 2 ,id_desafio: 6},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 9 ,id_desafio: 6},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 19 ,id_desafio: 6},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 25 ,id_desafio: 7},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 1 ,id_desafio: 7},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 2 ,id_desafio: 7},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 9 ,id_desafio: 7},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 19 ,id_desafio: 7},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 25 ,id_desafio: 8},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 1 ,id_desafio: 8},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 2 ,id_desafio: 8},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 9 ,id_desafio: 8},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 19 ,id_desafio: 8},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 25 ,id_desafio: 9},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 1 ,id_desafio: 9},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 2 ,id_desafio: 9},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 9 ,id_desafio: 9},
    {puntos_ganar: 200 ,cantidad_precios: 100 , id_ciudad: 19 ,id_desafio: 9},
]

const precios = [
    {latitud: "-34.796581" ,longitud: "-34.796581" , id_usuario: 1 ,nombre_negocio: "mercadito 1", direccion_negocio: "calle principal esquina 12 -35", precio: 30 , id_desafio: 1},
    {latitud: "-31.416668" ,longitud: "-31.416668" , id_usuario: 2 ,nombre_negocio: "mercadito 2", direccion_negocio: "calle principal esquina 12 -36", precio: 25 , id_desafio: 1},
    {latitud: "-38.7195900" ,longitud: "-38.7195900" , id_usuario: 3 ,nombre_negocio: "mercadito 3", direccion_negocio: "calle principal esquina 12 -37", precio: 27 , id_desafio: 1},
    {latitud: "-31.73197" ,longitud: "-31.73197" , id_usuario: 4 ,nombre_negocio: "mercadito 4", direccion_negocio: "calle principal esquina 12 -38", precio: 10 , id_desafio: 1},
    {latitud: "-34.920345" ,longitud: "-34.920345" , id_usuario: 5 ,nombre_negocio: "mercadito 5", direccion_negocio: "calle principal esquina 12 -39", precio: 33 , id_desafio: 1},
    {latitud: "-34.796581" ,longitud: "-34.796581" , id_usuario: 1 ,nombre_negocio: "mercadito 6", direccion_negocio: "calle principal esquina 12 -40", precio: 25 , id_desafio: 2},
    {latitud: "-31.416668" ,longitud: "-31.416668" , id_usuario: 2 ,nombre_negocio: "mercadito 7", direccion_negocio: "calle principal esquina 12 -41", precio: 23 , id_desafio: 2},
    {latitud: "-38.7195900" ,longitud: "-38.7195900" , id_usuario: 3 ,nombre_negocio: "mercadito 8", direccion_negocio: "calle principal esquina 12 -42", precio: 27 , id_desafio: 2},
    {latitud: "-31.73197" ,longitud: "-31.73197" , id_usuario: 4 ,nombre_negocio: "mercadito 9", direccion_negocio: "calle principal esquina 12 -43", precio: 24 , id_desafio: 2},
    {latitud: "-34.920345" ,longitud: "-34.920345" , id_usuario: 5 ,nombre_negocio: "mercadito 10", direccion_negocio: "calle principal esquina 12 -44", precio: 26 , id_desafio: 2},
    {latitud: "-34.796581" ,longitud: "-34.796581" , id_usuario: 1 ,nombre_negocio: "mercadito 11", direccion_negocio: "calle principal esquina 12 -45", precio: 80 , id_desafio: 3},
    {latitud: "-31.416668" ,longitud: "-31.416668" , id_usuario: 2 ,nombre_negocio: "mercadito 12", direccion_negocio: "calle principal esquina 12 -46", precio: 75 , id_desafio: 3},
    {latitud: "-38.7195900" ,longitud: "-38.7195900" , id_usuario: 3 ,nombre_negocio: "mercadito 13", direccion_negocio: "calle principal esquina 12 -47", precio: 81 , id_desafio: 3},
    {latitud: "-31.73197" ,longitud: "-31.73197" , id_usuario: 4 ,nombre_negocio: "mercadito 14", direccion_negocio: "calle principal esquina 12 -48", precio: 90 , id_desafio: 3},
    {latitud: "-34.920345" ,longitud: "-34.920345" , id_usuario: 5 ,nombre_negocio: "mercadito 15", direccion_negocio: "calle principal esquina 12 -49", precio: 88 , id_desafio: 3},
    {latitud: "-34.796581" ,longitud: "-34.796581" , id_usuario: 1 ,nombre_negocio: "mercadito 16", direccion_negocio: "calle principal esquina 12 -50", precio: 30 , id_desafio: 4},
    {latitud: "-31.416668" ,longitud: "-31.416668" , id_usuario: 2 ,nombre_negocio: "mercadito 17", direccion_negocio: "calle principal esquina 12 -51", precio: 25 , id_desafio: 4},
    {latitud: "-38.7195900" ,longitud: "-38.7195900" , id_usuario: 3 ,nombre_negocio: "mercadito 18", direccion_negocio: "calle principal esquina 12 -52", precio: 27 , id_desafio: 4},
    {latitud: "-31.73197" ,longitud: "-31.73197" , id_usuario: 4 ,nombre_negocio: "mercadito 19", direccion_negocio: "calle principal esquina 12 -53", precio: 10 , id_desafio: 4},
    {latitud: "-34.920345" ,longitud: "-34.920345" , id_usuario: 5 ,nombre_negocio: "mercadito 20", direccion_negocio: "calle principal esquina 12 -54", precio: 33 , id_desafio: 4},
    {latitud: "-34.796581" ,longitud: "-34.796581" , id_usuario: 1 ,nombre_negocio: "mercadito 21", direccion_negocio: "calle principal esquina 12 -55", precio: 25 , id_desafio: 5},
    {latitud: "-31.416668" ,longitud: "-31.416668" , id_usuario: 2 ,nombre_negocio: "mercadito 22", direccion_negocio: "calle principal esquina 12 -56", precio: 23 , id_desafio: 5},
    {latitud: "-38.7195900" ,longitud: "-38.7195900" , id_usuario: 3 ,nombre_negocio: "mercadito 23", direccion_negocio: "calle principal esquina 12 -57", precio: 27 , id_desafio: 5},
    {latitud: "-31.73197" ,longitud: "-31.73197" , id_usuario: 4 ,nombre_negocio: "mercadito 24", direccion_negocio: "calle principal esquina 12 -58", precio: 24 , id_desafio: 5},
    {latitud: "-34.920345" ,longitud: "-34.920345" , id_usuario: 5 ,nombre_negocio: "mercadito 25", direccion_negocio: "calle principal esquina 12 -59", precio: 26 , id_desafio: 5},
    {latitud: "-34.920345" ,longitud: "-34.920345" , id_usuario: 1 ,nombre_negocio: "mercadito 26", direccion_negocio: "calle principal esquina 12 -60", precio: 80 , id_desafio: 6},
    {latitud: "-34.796581" ,longitud: "-34.796581" , id_usuario: 2 ,nombre_negocio: "mercadito 27", direccion_negocio: "calle principal esquina 12 -61", precio: 75 , id_desafio: 6},
    {latitud: "-31.416668" ,longitud: "-31.416668" , id_usuario: 3 ,nombre_negocio: "mercadito 28", direccion_negocio: "calle principal esquina 12 -62", precio: 81 , id_desafio: 6},
    {latitud: "-38.7195900" ,longitud: "-38.7195900" , id_usuario: 4 ,nombre_negocio: "mercadito 29", direccion_negocio: "calle principal esquina 12 -63", precio: 90 , id_desafio: 6},
    {latitud: "-31.73197" ,longitud: "-31.73197" , id_usuario: 5 ,nombre_negocio: "mercadito 30", direccion_negocio: "calle principal esquina 12 -64", precio: 88 , id_desafio: 6},
    {latitud: "-34.920345" ,longitud: "-34.920345" , id_usuario: 1 ,nombre_negocio: "mercadito 31", direccion_negocio: "calle principal esquina 12 -65", precio: 30 , id_desafio: 7},
    {latitud: "-34.796581" ,longitud: "-34.796581" , id_usuario: 2 ,nombre_negocio: "mercadito 32", direccion_negocio: "calle principal esquina 12 -66", precio: 25 , id_desafio: 7},
    {latitud: "-31.416668" ,longitud: "-31.416668" , id_usuario: 3 ,nombre_negocio: "mercadito 33", direccion_negocio: "calle principal esquina 12 -67", precio: 27 , id_desafio: 7},
    {latitud: "-38.7195900" ,longitud: "-38.7195900" , id_usuario: 4 ,nombre_negocio: "mercadito 34", direccion_negocio: "calle principal esquina 12 -68", precio: 10 , id_desafio: 7},
    {latitud: "-31.73197" ,longitud: "-31.73197" , id_usuario: 5 ,nombre_negocio: "mercadito 35", direccion_negocio: "calle principal esquina 12 -69", precio: 33 , id_desafio: 7},
    {latitud: "-34.920345" ,longitud: "-34.920345" , id_usuario: 1 ,nombre_negocio: "mercadito 36", direccion_negocio: "calle principal esquina 12 -70", precio: 25 , id_desafio: 8},
    {latitud: "-34.796581" ,longitud: "-34.796581" , id_usuario: 2 ,nombre_negocio: "mercadito 37", direccion_negocio: "calle principal esquina 12 -71", precio: 23 , id_desafio: 8},
    {latitud: "-31.416668" ,longitud: "-31.416668" , id_usuario: 3 ,nombre_negocio: "mercadito 38", direccion_negocio: "calle principal esquina 12 -72", precio: 27 , id_desafio: 8},
    {latitud: "-38.7195900" ,longitud: "-38.7195900" , id_usuario: 4 ,nombre_negocio: "mercadito 39", direccion_negocio: "calle principal esquina 12 -73", precio: 24 , id_desafio: 8},
    {latitud: "-31.73197" ,longitud: "-31.73197" , id_usuario: 5 ,nombre_negocio: "mercadito 40", direccion_negocio: "calle principal esquina 12 -74", precio: 26 , id_desafio: 8},
    {latitud: "-34.920345" ,longitud: "-34.920345" , id_usuario: 1 ,nombre_negocio: "mercadito 41", direccion_negocio: "calle principal esquina 12 -75", precio: 80 , id_desafio: 9},
    {latitud: "-34.796581" ,longitud: "-34.796581" , id_usuario: 2 ,nombre_negocio: "mercadito 42", direccion_negocio: "calle principal esquina 12 -76", precio: 75 , id_desafio: 9},
    {latitud: "-31.416668" ,longitud: "-31.416668" , id_usuario: 3 ,nombre_negocio: "mercadito 43", direccion_negocio: "calle principal esquina 12 -77", precio: 81 , id_desafio: 9},
    {latitud: "-38.7195900" ,longitud: "-38.7195900" , id_usuario: 4 ,nombre_negocio: "mercadito 44", direccion_negocio: "calle principal esquina 12 -78", precio: 90 , id_desafio: 9},
    {latitud: "-31.73197" ,longitud: "-31.73197" , id_usuario: 5 ,nombre_negocio: "mercadito 45", direccion_negocio: "calle principal esquina 12 -79", precio: 88 , id_desafio: 9},
]

const usuarios = [
    {Nombre: "Pedro" ,Apellido: "Perez" , fecha_nacimiento: [2000, 12, 05] ,id_ciudad: 1, id_genero: 2, metodo_cobro: "PSE" , Banco: "CITY-BANK" , numero_cuenta: "123456789" , id_tipo_usuario: 1, password: "abc1234"},
    {Nombre: "Juana" ,Apellido: "Gomez" , fecha_nacimiento: [1998, 06, 13] ,id_ciudad: 2, id_genero: 1, metodo_cobro: "PSE" , Banco: "DAVIVIENDA" , numero_cuenta: "654878911" , id_tipo_usuario: 1, password: "xyz6543"},
    {Nombre: "Mario" ,Apellido: "Gonzalez" , fecha_nacimiento: [1996, 03, 26] ,id_ciudad: 9, id_genero: 2, metodo_cobro: "PSE" , Banco: "MERCADO PAGO" , numero_cuenta: "258963147" , id_tipo_usuario: 1, password: "ASD658"},
    {Nombre: "Ana" ,Apellido: "Vargas" , fecha_nacimiento: [2001, 04, 02] ,id_ciudad: 19, id_genero: 1, metodo_cobro: "PSE" , Banco: "MERCADO PAGO" , numero_cuenta: "654321987" , id_tipo_usuario: 1, password: "OIU457"},
    {Nombre: "Nina" ,Apellido: "Otalora" , fecha_nacimiento: [2005, 04, 02] ,id_ciudad: 25, id_genero: 1, metodo_cobro: "PSE" , Banco: "MERCADO PAGO" , numero_cuenta: "951236478" , id_tipo_usuario: 1, password: "PÑL965"},
]

const generos = [
    {genero: "femenino"},
    {genero: "masculino"},
    {genero: "otro"},
]

const clientes =[
    {Razon_social: "Price Hunter Asociados ARG / COL" , nombre_cial_fantasia: "Price Hunter" ,cuit_nit_rut: "800123456" , telefono: "3112546025" ,direccion: "cra 5 este 47 - 49", id_ciudad: 1, metodo_pago: "PSE" , Banco: "MERCADO PAGO" , numero_cuenta: "954786321" , id_tipo_usuario: 2, password: "phunter98756"},
    {Razon_social: "Soy Henry" , nombre_cial_fantasia: "Soy Henry" ,cuit_nit_rut: "800123654" , telefono: "121465488" ,direccion: "calle p no 85 - 12", id_ciudad: 1, metodo_pago: "PSE" , Banco: "MERCADO PAGO" , numero_cuenta: "987412545" , id_tipo_usuario: 2, password: "soyhenry123"},
]

const regiones = [
    {nombre_region: "América del Sur"},
    {nombre_region: "Antillas/Caribe"},
    {nombre_region: "Pacífico"},
]

const monedas = [
    {cod_moneda: "ARS" , moneda: "peso argentino", simbolo: "$"},
    {cod_moneda: "BOB" , moneda: "boliviano", simbolo: "Bs."},
    {cod_moneda: "BRL" , moneda: "real brasileño", simbolo: "R$"},
    {cod_moneda: "CLP" , moneda: "peso chileno", simbolo: "$"},
    {cod_moneda: "COP" , moneda: "peso colombiano", simbolo: "$"},
    {cod_moneda: "CRC" , moneda: "colón costarricense", simbolo: "₡"},
    {cod_moneda: "CUC" , moneda: "peso cubano convertible", simbolo: "$"},
    {cod_moneda: "USD" , moneda: "dólar estadounidense", simbolo: "$"},
    {cod_moneda: "GTQ" , moneda: "quetzal guatemalteco", simbolo: "Q"},
    {cod_moneda: "HTG" , moneda: "gourde haitiano", simbolo: "G"},
    {cod_moneda: "HNL" , moneda: "lempira hondureño", simbolo: "L"},
    {cod_moneda: "MXN" , moneda: "peso mexicano", simbolo: "$"},
    {cod_moneda: "NIO" , moneda: "córdoba nicaragüense", simbolo: "C$"},
    {cod_moneda: "PAB" , moneda: "balboa panameña", simbolo: "B/."},
    {cod_moneda: "PYG" , moneda: "guaraní", simbolo: "₲"},
    {cod_moneda: "PEN" , moneda: "nuevo sol peruano", simbolo: "S/."},
    {cod_moneda: "DOP" , moneda: "peso dominicano", simbolo: "$"},
    {cod_moneda: "UYU" , moneda: "peso uruguayo", simbolo: "$"},
    {cod_moneda: "VES" , moneda: "bolívar soberano", simbolo: "B$"},
];

const paises = [
    {cod_pais: "ARG" , Paises: "Argentina", cod_moneda: "ARS" , id_region: 1},
    {cod_pais: "BOL" , Paises: "Bolivia", cod_moneda: "BOB" , id_region: 1},
    {cod_pais: "BRA" , Paises: "Brasil", cod_moneda: "BRL" , id_region: 1},
    {cod_pais: "CHL" , Paises: "Chile", cod_moneda: "CLP" , id_region: 1},
    {cod_pais: "COL" , Paises: "Colombia", cod_moneda: "COP" , id_region: 1},
    {cod_pais: "CRI" , Paises: "Costa Rica", cod_moneda: "CRC" , id_region: 1},
    {cod_pais: "CUB" , Paises: "Cuba", cod_moneda: "CUC" , id_region: 2},
    {cod_pais: "ECU" , Paises: "Ecuador", cod_moneda: "USD" , id_region: 1},
    {cod_pais: "GTM" , Paises: "Guatemala", cod_moneda: "GTQ" , id_region: 1},
    {cod_pais: "HTI" , Paises: "Haití", cod_moneda: "HTG" , id_region: 2},
    {cod_pais: "HND" , Paises: "Honduras", cod_moneda: "HNL" , id_region: 1},
    {cod_pais: "MEX" , Paises: "México", cod_moneda: "MXN" , id_region: 1},
    {cod_pais: "NIC" , Paises: "Nicaragua", cod_moneda: "NIO" , id_region: 1},
    {cod_pais: "PAN" , Paises: "Panamá", cod_moneda: "PAB" , id_region: 3},
    {cod_pais: "PRY" , Paises: "Paraguay", cod_moneda: "PYG" , id_region: 1},
    {cod_pais: "PER" , Paises: "Perú", cod_moneda: "PEN" , id_region: 1},
    {cod_pais: "DOM" , Paises: "República Dominicana", cod_moneda: "DOP" , id_region: 2},
    {cod_pais: "URY" , Paises: "Uruguay", cod_moneda: "UYU" , id_region: 1},
    {cod_pais: "VEN" , Paises: "Venezuela", cod_moneda: "VES" , id_region: 1},
];

const ciudades =[
    {Ciudad: "Buenos Aires", cod_pais: "ARG"},
    {Ciudad: "Córdoba", cod_pais: "ARG"},
    {Ciudad: "Rosario", cod_pais: "ARG"},
    {Ciudad: "Mar del Plata", cod_pais: "ARG"},
    {Ciudad: "San Miguel de Tucumán", cod_pais: "ARG"},
    {Ciudad: "Salta", cod_pais: "ARG"},
    {Ciudad: "Santa Fe", cod_pais: "ARG"},
    {Ciudad: "Corrientes", cod_pais: "ARG"},
    {Ciudad: "Bahía Blanca", cod_pais: "ARG"},
    {Ciudad: "Resistencia", cod_pais: "ARG"},
    {Ciudad: "Posadas", cod_pais: "ARG"},
    {Ciudad: "Merlo", cod_pais: "ARG"},
    {Ciudad: "Quilmes", cod_pais: "ARG"},
    {Ciudad: "San Salvador de Jujuy", cod_pais: "ARG"},
    {Ciudad: "Guaymallén", cod_pais: "ARG"},
    {Ciudad: "Santiago del Estero", cod_pais: "ARG"},
    {Ciudad: "Gregorio de Laferrere", cod_pais: "ARG"},
    {Ciudad: "José C. Paz", cod_pais: "ARG"},
    {Ciudad: "Paraná", cod_pais: "ARG"},
    {Ciudad: "Banfield nota 2​", cod_pais: "ARG"},
    {Ciudad: "González Catán", cod_pais: "ARG"},
    {Ciudad: "Neuquén", cod_pais: "ARG"},
    {Ciudad: "Formosa", cod_pais: "ARG"},
    {Ciudad: "Lanús", cod_pais: "ARG"},
    {Ciudad: "La Plata", cod_pais: "ARG"},
    {Ciudad: "Godoy Cruz", cod_pais: "ARG"},
    {Ciudad: "Isidro Casanova", cod_pais: "ARG"},
    {Ciudad: "Las Heras", cod_pais: "ARG"},
    {Ciudad: "Berazategui", cod_pais: "ARG"},
    {Ciudad: "La Rioja", cod_pais: "ARG"},
    {Ciudad: "Comodoro Rivadavia", cod_pais: "ARG"},
    {Ciudad: "Moreno", cod_pais: "ARG"},
    {Ciudad: "San Luis", cod_pais: "ARG"},
    {Ciudad: "San Miguel nota 3​", cod_pais: "ARG"},
    {Ciudad: "San Fernando del Valle de Catamarca", cod_pais: "ARG"},
    {Ciudad: "Río Cuarto", cod_pais: "ARG"},
    {Ciudad: "Virrey del Pino", cod_pais: "ARG"},
    {Ciudad: "Santa Cruz de la Sierra", cod_pais: "BOL"},
    {Ciudad: "El Alto", cod_pais: "BOL"},
    {Ciudad: "La Paz", cod_pais: "BOL"},
    {Ciudad: "Cochabamba", cod_pais: "BOL"},
    {Ciudad: "Oruro", cod_pais: "BOL"},
    {Ciudad: "Sucre", cod_pais: "BOL"},
    {Ciudad: "Tarija", cod_pais: "BOL"},
    {Ciudad: "Potosí", cod_pais: "BOL"},
    {Ciudad: "Warnes", cod_pais: "BOL"},
    {Ciudad: "Sacaba", cod_pais: "BOL"},
    {Ciudad: "La Guardia", cod_pais: "BOL"},
    {Ciudad: "Quillacollo", cod_pais: "BOL"},
    {Ciudad: "Montero", cod_pais: "BOL"},
    {Ciudad: "Trinidad", cod_pais: "BOL"},
    {Ciudad: "Yacuiba", cod_pais: "BOL"},
    {Ciudad: "São Paulo", cod_pais: "BRA"},
    {Ciudad: "Rio de Janeiro", cod_pais: "BRA"},
    {Ciudad: "Salvador", cod_pais: "BRA"},
    {Ciudad: "Brasilia", cod_pais: "BRA"},
    {Ciudad: "Fortaleza", cod_pais: "BRA"},
    {Ciudad: "Belo Horizonte", cod_pais: "BRA"},
    {Ciudad: "Manaus", cod_pais: "BRA"},
    {Ciudad: "Curitiba", cod_pais: "BRA"},
    {Ciudad: "Recife", cod_pais: "BRA"},
    {Ciudad: "Porto Alegre", cod_pais: "BRA"},
    {Ciudad: "Belém", cod_pais: "BRA"},
    {Ciudad: "Goiânia", cod_pais: "BRA"},
    {Ciudad: "São Luís", cod_pais: "BRA"},
    {Ciudad: "Maceió", cod_pais: "BRA"},
    {Ciudad: "Teresina", cod_pais: "BRA"},
    {Ciudad: "Natal", cod_pais: "BRA"},
    {Ciudad: "Campo Grande", cod_pais: "BRA"},
    {Ciudad: "João Pessoa", cod_pais: "BRA"},
    {Ciudad: "Aracaju", cod_pais: "BRA"},
    {Ciudad: "Cuiabá", cod_pais: "BRA"},
    {Ciudad: "Porto Velho", cod_pais: "BRA"},
    {Ciudad: "Florianópolis", cod_pais: "BRA"},
    {Ciudad: "Macapá", cod_pais: "BRA"},
    {Ciudad: "Rio Branco", cod_pais: "BRA"},
    {Ciudad: "Vitória", cod_pais: "BRA"},
    {Ciudad: "Boa Vista", cod_pais: "BRA"},
    {Ciudad: "Palmas", cod_pais: "BRA"},
    {Ciudad: "Gran Santiago (C)", cod_pais: "CHL"},
    {Ciudad: "Gran Concepción (C)", cod_pais: "CHL"},
    {Ciudad: "Gran Valparaíso (C)", cod_pais: "CHL"},
    {Ciudad: "Gran La Serena (C)", cod_pais: "CHL"},
    {Ciudad: "Gran Temuco (C)", cod_pais: "CHL"},
    {Ciudad: "Antofagasta (C)", cod_pais: "CHL"},
    {Ciudad: "Gran Iquique (C)", cod_pais: "CHL"},
    {Ciudad: "Gran Puerto Montt (C)", cod_pais: "CHL"},
    {Ciudad: "Gran Talca (C)", cod_pais: "CHL"},
    {Ciudad: "Arica (C)", cod_pais: "CHL"},
    {Ciudad: "Gran Rancagua (C)", cod_pais: "CHL"},
    {Ciudad: "Gran Chillan (C)", cod_pais: "CHL"},
    {Ciudad: "Los Ángeles", cod_pais: "CHL"},
    {Ciudad: "Calama", cod_pais: "CHL"},
    {Ciudad: "Colina", cod_pais: "CHL"},
    {Ciudad: "Valdivia (C)", cod_pais: "CHL"},
    {Ciudad: "Gran Quillota", cod_pais: "CHL"},
    {Ciudad: "Osorno", cod_pais: "CHL"},
    {Ciudad: "Copiapó (C)", cod_pais: "CHL"},
    {Ciudad: "Curicó", cod_pais: "CHL"},
    {Ciudad: "Punta Arenas (C)", cod_pais: "CHL"},
    {Ciudad: "Melipilla", cod_pais: "CHL"},
    {Ciudad: "Gran San Antonio", cod_pais: "CHL"},
    {Ciudad: "Lampa", cod_pais: "CHL"},
    {Ciudad: "Ovalle", cod_pais: "CHL"},
    {Ciudad: "Buin", cod_pais: "CHL"},
    {Ciudad: "Los Andes-Calle Larga-San Esteban", cod_pais: "CHL"},
    {Ciudad: "Linares", cod_pais: "CHL"},
    {Ciudad: "Peñaflor", cod_pais: "CHL"},
    {Ciudad: "San Felipe", cod_pais: "CHL"},
    {Ciudad: "Paine", cod_pais: "CHL"},
    {Ciudad: "Talagante", cod_pais: "CHL"},
    {Ciudad: "San Fernando", cod_pais: "CHL"},
    {Ciudad: "Limache-Olmué", cod_pais: "CHL"},
    {Ciudad: "Rengo", cod_pais: "CHL"},
    {Ciudad: "Coyhaique (C)", cod_pais: "CHL"},
    {Ciudad: "Villarrica", cod_pais: "CHL"},
    {Ciudad: "Vallenar", cod_pais: "CHL"},
    {Ciudad: "San Carlos", cod_pais: "CHL"},
    {Ciudad: "Angol", cod_pais: "CHL"},
    {Ciudad: "San Vicente de Tagua Tagua", cod_pais: "CHL"},
    {Ciudad: "Cauquenes", cod_pais: "CHL"},
    {Ciudad: "Bogotá", cod_pais: "COL"},
    {Ciudad: "Medellín", cod_pais: "COL"},
    {Ciudad: "Cali", cod_pais: "COL"},
    {Ciudad: "Barranquilla", cod_pais: "COL"},
    {Ciudad: "Cartagena", cod_pais: "COL"},
    {Ciudad: "Cúcuta", cod_pais: "COL"},
    {Ciudad: "Soacha", cod_pais: "COL"},
    {Ciudad: "Soledad", cod_pais: "COL"},
    {Ciudad: "Bucaramanga", cod_pais: "COL"},
    {Ciudad: "Bello", cod_pais: "COL"},
    {Ciudad: "Villavicencio", cod_pais: "COL"},
    {Ciudad: "Ibagué", cod_pais: "COL"},
    {Ciudad: "Santa Marta", cod_pais: "COL"},
    {Ciudad: "Valledupar", cod_pais: "COL"},
    {Ciudad: "Montería", cod_pais: "COL"},
    {Ciudad: "Pereira", cod_pais: "COL"},
    {Ciudad: "Manizales", cod_pais: "COL"},
    {Ciudad: "Pasto", cod_pais: "COL"},
    {Ciudad: "Neiva", cod_pais: "COL"},
    {Ciudad: "Palmira", cod_pais: "COL"},
    {Ciudad: "Popayán", cod_pais: "COL"},
    {Ciudad: "Buenaventura", cod_pais: "COL"},
    {Ciudad: "Floridablanca", cod_pais: "COL"},
    {Ciudad: "Armenia", cod_pais: "COL"},
    {Ciudad: "Sincelejo", cod_pais: "COL"},
    {Ciudad: "Itagüí", cod_pais: "COL"},
    {Ciudad: "Tumaco", cod_pais: "COL"},
    {Ciudad: "Envigado", cod_pais: "COL"},
    {Ciudad: "Dosquebradas", cod_pais: "COL"},
    {Ciudad: "Tuluá", cod_pais: "COL"},
    {Ciudad: "Barrancabermeja", cod_pais: "COL"},
    {Ciudad: "Riohacha", cod_pais: "COL"},
    {Ciudad: "Uribia", cod_pais: "COL"},
    {Ciudad: "Maicao", cod_pais: "COL"},
    {Ciudad: "Piedecuesta", cod_pais: "COL"},
    {Ciudad: "Tunja", cod_pais: "COL"},
    {Ciudad: "Yopal", cod_pais: "COL"},
    {Ciudad: "Florencia", cod_pais: "COL"},
    {Ciudad: "Girón", cod_pais: "COL"},
    {Ciudad: "Jamundí", cod_pais: "COL"},
    {Ciudad: "Facatativá", cod_pais: "COL"},
    {Ciudad: "Fusagasugá", cod_pais: "COL"},
    {Ciudad: "Mosquera", cod_pais: "COL"},
    {Ciudad: "Chía", cod_pais: "COL"},
    {Ciudad: "Zipaquirá", cod_pais: "COL"},
    {Ciudad: "Rionegro", cod_pais: "COL"},
    {Ciudad: "Magangué", cod_pais: "COL"},
    {Ciudad: "Malambo", cod_pais: "COL"},
    {Ciudad: "Cartago", cod_pais: "COL"},
    {Ciudad: "Sogamoso", cod_pais: "COL"},
    {Ciudad: "Quibdó", cod_pais: "COL"},
    {Ciudad: "Turbo", cod_pais: "COL"},
    {Ciudad: "Ocaña", cod_pais: "COL"},
    {Ciudad: "Buga", cod_pais: "COL"},
    {Ciudad: "Pitalito", cod_pais: "COL"},
    {Ciudad: "Apartadó", cod_pais: "COL"},
    {Ciudad: "Madrid", cod_pais: "COL"},
    {Ciudad: "Duitama", cod_pais: "COL"},
    {Ciudad: "Ciénaga", cod_pais: "COL"},
    {Ciudad: "Aguachica", cod_pais: "COL"},
    {Ciudad: "Ipiales", cod_pais: "COL"},
    {Ciudad: "Lorica", cod_pais: "COL"},
    {Ciudad: "Turbaco", cod_pais: "COL"},
    {Ciudad: "Santander de Quilichao", cod_pais: "COL"},
    {Ciudad: "Villa del Rosario", cod_pais: "COL"},
    {Ciudad: "Sahagún", cod_pais: "COL"},
    {Ciudad: "Yumbo", cod_pais: "COL"},
    {Ciudad: "Girardot", cod_pais: "COL"},
    {Ciudad: "Cereté", cod_pais: "COL"},
    {Ciudad: "Funza", cod_pais: "COL"},
    {Ciudad: "Sabanalarga", cod_pais: "COL"},
    {Ciudad: "Los Patios", cod_pais: "COL"},
    {Ciudad: "Arauca", cod_pais: "COL"},
    {Ciudad: "Caucasia", cod_pais: "COL"},
    {Ciudad: "Tierralta", cod_pais: "COL"},
    {Ciudad: "Candelaria", cod_pais: "COL"},
    {Ciudad: "Manaure", cod_pais: "COL"},
    {Ciudad: "Cajicá", cod_pais: "COL"},
    {Ciudad: "Acacías", cod_pais: "COL"},
    {Ciudad: "Sabaneta", cod_pais: "COL"},
    {Ciudad: "Montelíbano", cod_pais: "COL"},
    {Ciudad: "Caldas", cod_pais: "COL"},
    {Ciudad: "Copacabana", cod_pais: "COL"},
    {Ciudad: "Santa Rosa de Cabal", cod_pais: "COL"},
    {Ciudad: "Cumaribo", cod_pais: "COL"},
    {Ciudad: "La Estrella", cod_pais: "COL"},
    {Ciudad: "Calarcá", cod_pais: "COL"},
    {Ciudad: "Garzón", cod_pais: "COL"},
    {Ciudad: "La Dorada", cod_pais: "COL"},
    {Ciudad: "Zona Bananera", cod_pais: "COL"},
    {Ciudad: "Arjona", cod_pais: "COL"},
    {Ciudad: "El Carmen de Bolívar", cod_pais: "COL"},
    {Ciudad: "Espinal", cod_pais: "COL"},
    {Ciudad: "Corozal", cod_pais: "COL"},
    {Ciudad: "Granada", cod_pais: "COL"},
    {Ciudad: "Fundación", cod_pais: "COL"},
    {Ciudad: "El Banco", cod_pais: "COL"},
    {Ciudad: "La Ceja", cod_pais: "COL"},
    {Ciudad: "Marinilla", cod_pais: "COL"},
    {Ciudad: "Villamaría", cod_pais: "COL"},
    {Ciudad: "Puerto Asís", cod_pais: "COL"},
    {Ciudad: "Baranoa", cod_pais: "COL"},
    {Ciudad: "Galapa", cod_pais: "COL"},
    {Ciudad: "Planeta Rica", cod_pais: "COL"},
    {Ciudad: "Agustín Codazzi", cod_pais: "COL"},
    {Ciudad: "Plato", cod_pais: "COL"},
    {Ciudad: "Saravena", cod_pais: "COL"},
    {Ciudad: "El Carmen de Viboral", cod_pais: "COL"},
    {Ciudad: "La Plata", cod_pais: "COL"},
    {Ciudad: "San Marcos", cod_pais: "COL"},
    {Ciudad: "Ciénaga de Oro", cod_pais: "COL"},
    {Ciudad: "Chigorodó", cod_pais: "COL"},
    {Ciudad: "San Gil", cod_pais: "COL"},
    {Ciudad: "Mocoa", cod_pais: "COL"},
    {Ciudad: "Tibú", cod_pais: "COL"},
    {Ciudad: "Guarne", cod_pais: "COL"},
    {Ciudad: "Florida", cod_pais: "COL"},
    {Ciudad: "Chiquinquirá", cod_pais: "COL"},
    {Ciudad: "San Andrés", cod_pais: "COL"},
    {Ciudad: "El Cerrito", cod_pais: "COL"},
    {Ciudad: "Barbacoas", cod_pais: "COL"},
    {Ciudad: "Arauquita", cod_pais: "COL"},
    {Ciudad: "San José del Guaviare", cod_pais: "COL"},
    {Ciudad: "Riosucio", cod_pais: "COL"},
    {Ciudad: "Tuchín", cod_pais: "COL"},
    {Ciudad: "Girardota", cod_pais: "COL"},
    {Ciudad: "Barbosa", cod_pais: "COL"},
    {Ciudad: "Pamplona", cod_pais: "COL"},
    {Ciudad: "El Bagre", cod_pais: "COL"},
    {Ciudad: "El Tambo", cod_pais: "COL"},
    {Ciudad: "Puerto Colombia", cod_pais: "COL"},
    {Ciudad: "San Pelayo", cod_pais: "COL"},
    {Ciudad: "San Vicente del Caguán", cod_pais: "COL"},
    {Ciudad: "Chinchiná", cod_pais: "COL"},
    {Ciudad: "Riosucio", cod_pais: "COL"},
    {Ciudad: "Carepa", cod_pais: "COL"},
    {Ciudad: "San Onofre", cod_pais: "COL"},
    {Ciudad: "La Jagua de Ibirico", cod_pais: "COL"},
    {Ciudad: "Chaparral", cod_pais: "COL"},
    {Ciudad: "San José", cod_pais: "CRC"},
    {Ciudad: "Alajuela", cod_pais: "CRC"},
    {Ciudad: "Cartago", cod_pais: "CRC"},
    {Ciudad: "Heredia", cod_pais: "CRC"},
    {Ciudad: "Liberia", cod_pais: "CRC"},
    {Ciudad: "Puntarenas", cod_pais: "CRC"},
    {Ciudad: "Limón", cod_pais: "CRC"},
    {Ciudad: "La Habana", cod_pais: "CUB"},
    {Ciudad: "Santiago de Cuba", cod_pais: "CUB"},
    {Ciudad: "Camagüey", cod_pais: "CUB"},
    {Ciudad: "Holguín", cod_pais: "CUB"},
    {Ciudad: "Guantánamo", cod_pais: "CUB"},
    {Ciudad: "Santa Clara", cod_pais: "CUB"},
    {Ciudad: "Las Tunas", cod_pais: "CUB"},
    {Ciudad: "Bayamo", cod_pais: "CUB"},
    {Ciudad: "Cienfuegos", cod_pais: "CUB"},
    {Ciudad: "Pinar del Río", cod_pais: "CUB"},
    {Ciudad: "Matanzas", cod_pais: "CUB"},
    {Ciudad: "Ciego de Ávila", cod_pais: "CUB"},
    {Ciudad: "Sancti Spíritus", cod_pais: "CUB"},
    {Ciudad: "Manzanillo", cod_pais: "CUB"},
    {Ciudad: "Cárdenas", cod_pais: "CUB"},
    {Ciudad: "Palma Soriano", cod_pais: "CUB"},
    {Ciudad: "Moa", cod_pais: "CUB"},
    {Ciudad: "Morón", cod_pais: "CUB"},
    {Ciudad: "Florida", cod_pais: "CUB"},
    {Ciudad: "Contramaestre", cod_pais: "CUB"},
    {Ciudad: "Artemisa", cod_pais: "CUB"},
    {Ciudad: "Nueva Gerona", cod_pais: "CUB"},
    {Ciudad: "Trinidad", cod_pais: "CUB"},
    {Ciudad: "Colón", cod_pais: "CUB"},
    {Ciudad: "Baracoa", cod_pais: "CUB"},
    {Ciudad: "Güines", cod_pais: "CUB"},
    {Ciudad: "Placetas", cod_pais: "CUB"},
    {Ciudad: "Nuevitas", cod_pais: "CUB"},
    {Ciudad: "Sagua la Grande", cod_pais: "CUB"},
    {Ciudad: "San José de las Lajas", cod_pais: "CUB"},
    {Ciudad: "Banes", cod_pais: "CUB"},
    {Ciudad: "San Luis", cod_pais: "CUB"},
    {Ciudad: "Puerto Padre", cod_pais: "CUB"},
    {Ciudad: "San Antonio de los Baños", cod_pais: "CUB"},
    {Ciudad: "Caibarién", cod_pais: "CUB"},
    {Ciudad: "Cabaiguán", cod_pais: "CUB"},
    {Ciudad: "Mayarí", cod_pais: "CUB"},
    {Ciudad: "San Cristóbal", cod_pais: "CUB"},
    {Ciudad: "Vertientes", cod_pais: "CUB"},
    {Ciudad: "Jagüey Grande", cod_pais: "CUB"},
    {Ciudad: "Consolación del Sur", cod_pais: "CUB"},
    {Ciudad: "Jovellanos", cod_pais: "CUB"},
    {Ciudad: "Amancio", cod_pais: "CUB"},
    {Ciudad: "Güira de Melena", cod_pais: "CUB"},
    {Ciudad: "Cumanayagua", cod_pais: "CUB"},
    {Ciudad: "Jatibonico", cod_pais: "CUB"},
    {Ciudad: "Niquero", cod_pais: "CUB"},
    {Ciudad: "San Germán", cod_pais: "CUB"},
    {Ciudad: "Sagua de Tánamo", cod_pais: "CUB"},
    {Ciudad: "Bauta", cod_pais: "CUB"},
    {Ciudad: "La Maya", cod_pais: "CUB"},
    {Ciudad: "Guanajay", cod_pais: "CUB"},
    {Ciudad: "Colombia", cod_pais: "CUB"},
    {Ciudad: "Jiguaní", cod_pais: "CUB"},
    {Ciudad: "Manicaragua", cod_pais: "CUB"},
    {Ciudad: "Camajuaní", cod_pais: "CUB"},
    {Ciudad: "Guisa", cod_pais: "CUB"},
    {Ciudad: "Jobabo", cod_pais: "CUB"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Pichincha", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Santo Domingo de los Tsáchilas", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Tungurahua", cod_pais: "ECU"},
    {Ciudad: "Esmeraldas", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Chimborazo", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Imbabura", cod_pais: "ECU"},
    {Ciudad: "Santa Elena flag.pngSanta Elena", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Pichincha", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Cotopaxi", cod_pais: "ECU"},
    {Ciudad: "Carchi", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Sucumbíos", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Orellana", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Santa Elena flag.pngSanta Elena", cod_pais: "ECU"},
    {Ciudad: "Imbabura", cod_pais: "ECU"},
    {Ciudad: "Pichincha", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Cañar", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Santa Elena flag.pngSanta Elena", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Cañar", cod_pais: "ECU"},
    {Ciudad: "Pastaza", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Santo Domingo de los Tsáchilas", cod_pais: "ECU"},
    {Ciudad: "Esmeraldas", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Bolívar", cod_pais: "ECU"},
    {Ciudad: "Cotopaxi", cod_pais: "ECU"},
    {Ciudad: "Napo", cod_pais: "ECU"},
    {Ciudad: "Esmeraldas", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Imbabura", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Pichincha", cod_pais: "ECU"},
    {Ciudad: "Sucumbíos", cod_pais: "ECU"},
    {Ciudad: "Esmeraldas", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Carchi", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Cañar", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Tungurahua", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Cotopaxi", cod_pais: "ECU"},
    {Ciudad: "Zamora Chinchipe", cod_pais: "ECU"},
    {Ciudad: "Galápagos", cod_pais: "ECU"},
    {Ciudad: "Orellana", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Tungurahua", cod_pais: "ECU"},
    {Ciudad: "Cotopaxi", cod_pais: "ECU"},
    {Ciudad: "Pichincha", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Zamora Chinchipe", cod_pais: "ECU"},
    {Ciudad: "Imbabura", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Chimborazo", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Chimborazo", cod_pais: "ECU"},
    {Ciudad: "Tungurahua", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Cotopaxi", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Bolívar", cod_pais: "ECU"},
    {Ciudad: "Galápagos", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Chimborazo", cod_pais: "ECU"},
    {Ciudad: "Bolívar", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Bolívar", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Guayas", cod_pais: "ECU"},
    {Ciudad: "Esmeraldas", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Pichincha", cod_pais: "ECU"},
    {Ciudad: "Cañar", cod_pais: "ECU"},
    {Ciudad: "Napo", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Esmeraldas", cod_pais: "ECU"},
    {Ciudad: "Imbabura", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Pichincha", cod_pais: "ECU"},
    {Ciudad: "Cañar", cod_pais: "ECU"},
    {Ciudad: "Los Ríos", cod_pais: "ECU"},
    {Ciudad: "Carchi", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Chimborazo", cod_pais: "ECU"},
    {Ciudad: "Bolívar", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Napo", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Carchi", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Chimborazo", cod_pais: "ECU"},
    {Ciudad: "Chimborazo", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Imbabura", cod_pais: "ECU"},
    {Ciudad: "Orellana", cod_pais: "ECU"},
    {Ciudad: "Esmeraldas", cod_pais: "ECU"},
    {Ciudad: "Zamora Chinchipe", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Carchi", cod_pais: "ECU"},
    {Ciudad: "Zamora Chinchipe", cod_pais: "ECU"},
    {Ciudad: "Pichincha", cod_pais: "ECU"},
    {Ciudad: "Carchi", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Bolívar", cod_pais: "ECU"},
    {Ciudad: "Tungurahua", cod_pais: "ECU"},
    {Ciudad: "Chimborazo", cod_pais: "ECU"},
    {Ciudad: "Tungurahua", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Chimborazo", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Zamora Chinchipe", cod_pais: "ECU"},
    {Ciudad: "Sucumbíos", cod_pais: "ECU"},
    {Ciudad: "Tungurahua", cod_pais: "ECU"},
    {Ciudad: "Manabí", cod_pais: "ECU"},
    {Ciudad: "Galápagos", cod_pais: "ECU"},
    {Ciudad: "Sucumbíos", cod_pais: "ECU"},
    {Ciudad: "Sucumbíos", cod_pais: "ECU"},
    {Ciudad: "Zamora Chinchipe", cod_pais: "ECU"},
    {Ciudad: "Cotopaxi", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Zamora Chinchipe", cod_pais: "ECU"},
    {Ciudad: "Napo", cod_pais: "ECU"},
    {Ciudad: "Cotopaxi", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Bolívar", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Zamora Chinchipe", cod_pais: "ECU"},
    {Ciudad: "Pastaza", cod_pais: "ECU"},
    {Ciudad: "Pastaza", cod_pais: "ECU"},
    {Ciudad: "Sucumbíos", cod_pais: "ECU"},
    {Ciudad: "Tungurahua", cod_pais: "ECU"},
    {Ciudad: "Cañar", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Tungurahua", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Chimborazo", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "El Oro", cod_pais: "ECU"},
    {Ciudad: "Zamora Chinchipe", cod_pais: "ECU"},
    {Ciudad: "Napo", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Pastaza", cod_pais: "ECU"},
    {Ciudad: "Morona Santiago", cod_pais: "ECU"},
    {Ciudad: "Loja", cod_pais: "ECU"},
    {Ciudad: "Cañar", cod_pais: "ECU"},
    {Ciudad: "Sucumbíos", cod_pais: "ECU"},
    {Ciudad: "Azuay", cod_pais: "ECU"},
    {Ciudad: "Orellana", cod_pais: "ECU"},
    {Ciudad: "Ciudad de Guatemala", cod_pais: "GTM"},
    {Ciudad: "Santa Catarina Pinula", cod_pais: "GTM"},
    {Ciudad: "San Miguel Petapa", cod_pais: "GTM"},
    {Ciudad: "Mixco", cod_pais: "GTM"},
    {Ciudad: "Villa Nueva", cod_pais: "GTM"},
    {Ciudad: "Fraijanes", cod_pais: "GTM"},
    {Ciudad: "Antigua Guatemala", cod_pais: "GTM"},
    {Ciudad: "San Lucas Sacatepéquez", cod_pais: "GTM"},
    {Ciudad: "Villa Canales", cod_pais: "GTM"},
    {Ciudad: "San José Pinula", cod_pais: "GTM"},
    {Ciudad: "Amatitlán", cod_pais: "GTM"},
    {Ciudad: "Jocotenango", cod_pais: "GTM"},
    {Ciudad: "San Pedro Sacatepéquez", cod_pais: "GTM"},
    {Ciudad: "San José del Golfo", cod_pais: "GTM"},
    {Ciudad: "Chinautla", cod_pais: "GTM"},
    {Ciudad: "San Bartolomé Milpas Altas", cod_pais: "GTM"},
    {Ciudad: "Quetzaltenango", cod_pais: "GTM"},
    {Ciudad: "Salcajá", cod_pais: "GTM"},
    {Ciudad: "San Raymundo", cod_pais: "GTM"},
    {Ciudad: "Santa Lucía Milpas Altas", cod_pais: "GTM"},
    {Ciudad: "Gonaïves", cod_pais: "HTI"},
    {Ciudad: "Hinche", cod_pais: "HTI"},
    {Ciudad: "Jérémie", cod_pais: "HTI"},
    {Ciudad: "Miragoâne", cod_pais: "HTI"},
    {Ciudad: "Cabo Haitiano", cod_pais: "HTI"},
    {Ciudad: "Fuerte Libertad", cod_pais: "HTI"},
    {Ciudad: "Port-de-Paix", cod_pais: "HTI"},
    {Ciudad: "Puerto Príncipe", cod_pais: "HTI"},
    {Ciudad: "Les Cayes", cod_pais: "HTI"},
    {Ciudad: "Jacmel", cod_pais: "HTI"},
    {Ciudad: "Distrito Central", cod_pais: "HND"},
    {Ciudad: "San Pedro Sula", cod_pais: "HND"},
    {Ciudad: "Choloma", cod_pais: "HND"},
    {Ciudad: "Danlí", cod_pais: "HND"},
    {Ciudad: "La Ceiba", cod_pais: "HND"},
    {Ciudad: "El Progreso", cod_pais: "HND"},
    {Ciudad: "Villanueva", cod_pais: "HND"},
    {Ciudad: "Comayagua", cod_pais: "HND"},
    {Ciudad: "Choluteca", cod_pais: "HND"},
    {Ciudad: "Juticalpa", cod_pais: "HND"},
    {Ciudad: "Puerto Cortés", cod_pais: "HND"},
    {Ciudad: "Catacamas", cod_pais: "HND"},
    {Ciudad: "Olanchito", cod_pais: "HND"},
    {Ciudad: "Tela", cod_pais: "HND"},
    {Ciudad: "Tocoa", cod_pais: "HND"},
    {Ciudad: "Ciudad de México", cod_pais: "MEX"},
    {Ciudad: "Tijuana", cod_pais: "MEX"},
    {Ciudad: "San Cristóbal Ecatepec", cod_pais: "MEX"},
    {Ciudad: "León", cod_pais: "MEX"},
    {Ciudad: "Puebla de Zaragoza", cod_pais: "MEX"},
    {Ciudad: "Ciudad Juárez", cod_pais: "MEX"},
    {Ciudad: "Guadalajara", cod_pais: "MEX"},
    {Ciudad: "Zapopan", cod_pais: "MEX"},
    {Ciudad: "Monterrey", cod_pais: "MEX"},
    {Ciudad: "Nezahualcóyotl", cod_pais: "MEX"},
    {Ciudad: "Chihuahua", cod_pais: "MEX"},
    {Ciudad: "Mérida", cod_pais: "MEX"},
    {Ciudad: "Cancún", cod_pais: "MEX"},
    {Ciudad: "Saltillo", cod_pais: "MEX"},
    {Ciudad: "Aguascalientes", cod_pais: "MEX"},
    {Ciudad: "Hermosillo", cod_pais: "MEX"},
    {Ciudad: "Mexicali", cod_pais: "MEX"},
    {Ciudad: "San Luis Potosí", cod_pais: "MEX"},
    {Ciudad: "Culiacán Rosales", cod_pais: "MEX"},
    {Ciudad: "Santiago de Querétaro", cod_pais: "MEX"},
    {Ciudad: "Naucalpan de Juárez", cod_pais: "MEX"},
    {Ciudad: "Morelia", cod_pais: "MEX"},
    {Ciudad: "Chimalhuacán", cod_pais: "MEX"},
    {Ciudad: "Reynosa", cod_pais: "MEX"},
    {Ciudad: "Torreón", cod_pais: "MEX"},
    {Ciudad: "Tlalnepantla de Baz", cod_pais: "MEX"},
    {Ciudad: "Acapulco de Juárez", cod_pais: "MEX"},
    {Ciudad: "Tlaquepaque", cod_pais: "MEX"},
    {Ciudad: "Guadalupe", cod_pais: "MEX"},
    {Ciudad: "Victoria de Durango", cod_pais: "MEX"},
    {Ciudad: "Tuxtla Gutiérrez", cod_pais: "MEX"},
    {Ciudad: "Apodaca", cod_pais: "MEX"},
    {Ciudad: "Ciudad López Mateos", cod_pais: "MEX"},
    {Ciudad: "Cuautitlán Izcalli", cod_pais: "MEX"},
    {Ciudad: "Heroica Matamoros", cod_pais: "MEX"},
    {Ciudad: "General Escobedo", cod_pais: "MEX"},
    {Ciudad: "Irapuato", cod_pais: "MEX"},
    {Ciudad: "Xalapa", cod_pais: "MEX"},
    {Ciudad: "Tonalá", cod_pais: "MEX"},
    {Ciudad: "Mazatlán", cod_pais: "MEX"},
    {Ciudad: "Nuevo Laredo", cod_pais: "MEX"},
    {Ciudad: "San Nicolás de los Garza", cod_pais: "MEX"},
    {Ciudad: "Veracruz", cod_pais: "MEX"},
    {Ciudad: "Ojo de Agua", cod_pais: "MEX"},
    {Ciudad: "Xico", cod_pais: "MEX"},
    {Ciudad: "Celaya", cod_pais: "MEX"},
    {Ciudad: "Tepic", cod_pais: "MEX"},
    {Ciudad: "Ixtapaluca", cod_pais: "MEX"},
    {Ciudad: "Cuernavaca", cod_pais: "MEX"},
    {Ciudad: "Villahermosa", cod_pais: "MEX"},
    {Ciudad: "Ciudad Victoria", cod_pais: "MEX"},
    {Ciudad: "Ensenada", cod_pais: "MEX"},
    {Ciudad: "Ciudad Obregón", cod_pais: "MEX"},
    {Ciudad: "Villa Nicolás Romero", cod_pais: "MEX"},
    {Ciudad: "Soledad de Graciano Sánchez", cod_pais: "MEX"},
    {Ciudad: "Juárez", cod_pais: "MEX"},
    {Ciudad: "Playa del Carmen", cod_pais: "MEX"},
    {Ciudad: "Santa Catarina", cod_pais: "MEX"},
    {Ciudad: "Gómez Palacio", cod_pais: "MEX"},
    {Ciudad: "Uruapan", cod_pais: "MEX"},
    {Ciudad: "Los Mochis", cod_pais: "MEX"},
    {Ciudad: "Pachuca de Soto", cod_pais: "MEX"},
    {Ciudad: "Tampico", cod_pais: "MEX"},
    {Ciudad: "Tehuacán", cod_pais: "MEX"},
    {Ciudad: "San Francisco Coacalco", cod_pais: "MEX"},
    {Ciudad: "Salamanca", cod_pais: "MEX"},
    {Ciudad: "Heroica Nogales", cod_pais: "MEX"},
    {Ciudad: "Oaxaca de Juárez", cod_pais: "MEX"},
    {Ciudad: "La Paz", cod_pais: "MEX"},
    {Ciudad: "San Francisco de Campeche", cod_pais: "MEX"},
    {Ciudad: "Monclova", cod_pais: "MEX"},
    {Ciudad: "San Pedro Garza García", cod_pais: "MEX"},
    {Ciudad: "Chilpancingo de los Bravo", cod_pais: "MEX"},
    {Ciudad: "Puerto Vallarta", cod_pais: "MEX"},
    {Ciudad: "Toluca de Lerdo", cod_pais: "MEX"},
    {Ciudad: "Tapachula", cod_pais: "MEX"},
    {Ciudad: "Buenavista", cod_pais: "MEX"},
    {Ciudad: "Coatzacoalcos", cod_pais: "MEX"},
    {Ciudad: "Ciudad Madero", cod_pais: "MEX"},
    {Ciudad: "Cabo San Lucas", cod_pais: "MEX"},
    {Ciudad: "Guanajuato", cod_pais: "MEX"},
    {Ciudad: "Chicoloapan", cod_pais: "MEX"},
    {Ciudad: "Ciudad del Carmen", cod_pais: "MEX"},
    {Ciudad: "San Cristóbal de las Casas", cod_pais: "MEX"},
    {Ciudad: "Poza Rica de Hidalgo", cod_pais: "MEX"},
    {Ciudad: "San Juan del Río", cod_pais: "MEX"},
    {Ciudad: "San Luis Río Colorado", cod_pais: "MEX"},
    {Ciudad: "Chalco de Díaz Covarrubias", cod_pais: "MEX"},
    {Ciudad: "Jiutepec", cod_pais: "MEX"},
    {Ciudad: "Piedras Negras", cod_pais: "MEX"},
    {Ciudad: "Guadalupe", cod_pais: "MEX"},
    {Ciudad: "Chetumal", cod_pais: "MEX"},
    {Ciudad: "Miramar", cod_pais: "MEX"},
    {Ciudad: "Ciudad Acuña", cod_pais: "MEX"},
    {Ciudad: "Manzanillo", cod_pais: "MEX"},
    {Ciudad: "San Pablo de las Salinas", cod_pais: "MEX"},
    {Ciudad: "Cuautla de Morelos", cod_pais: "MEX"},
    {Ciudad: "Zamora", cod_pais: "MEX"},
    {Ciudad: "Villa de Álvarez", cod_pais: "MEX"},
    {Ciudad: "Colima", cod_pais: "MEX"},
    {Ciudad: "Fresnillo", cod_pais: "MEX"},
    {Ciudad: "Kanasín", cod_pais: "MEX"},
    {Ciudad: "Córdoba", cod_pais: "MEX"},
    {Ciudad: "Zacatecas", cod_pais: "MEX"},
    {Ciudad: "Ciudad Valles", cod_pais: "MEX"},
    {Ciudad: "San José del Cabo", cod_pais: "MEX"},
    {Ciudad: "Ciudad Cuauhtémoc", cod_pais: "MEX"},
    {Ciudad: "Naucalpan", cod_pais: "MEX"},
    {Ciudad: "Iguala", cod_pais: "MEX"},
    {Ciudad: "San Pedro Garza García", cod_pais: "MEX"},
    {Ciudad: "Veracruz", cod_pais: "MEX"},
    {Ciudad: "Delicias", cod_pais: "MEX"},
    {Ciudad: "Navojoa", cod_pais: "MEX"},
    {Ciudad: "Tepexpan", cod_pais: "MEX"},
    {Ciudad: "Orizaba", cod_pais: "MEX"},
    {Ciudad: "Cuautitlán", cod_pais: "MEX"},
    {Ciudad: "Guaymas", cod_pais: "MEX"},
    {Ciudad: "El Pueblito", cod_pais: "MEX"},
    {Ciudad: "Ramos Arizpe", cod_pais: "MEX"},
    {Ciudad: "Hidalgo del Parral", cod_pais: "MEX"},
    {Ciudad: "Comitán de Domínguez", cod_pais: "MEX"},
    {Ciudad: "Ciudad Guzmán", cod_pais: "MEX"},
    {Ciudad: "Lagos de Moreno", cod_pais: "MEX"},
    {Ciudad: "Río Bravo", cod_pais: "MEX"},
    {Ciudad: "Tulancingo de Bravo", cod_pais: "MEX"},
    {Ciudad: "Temixco (ciudad)", cod_pais: "MEX"},
    {Ciudad: "San Juan Bautista Tuxtepec", cod_pais: "MEX"},
    {Ciudad: "Apatzingán", cod_pais: "MEX"},
    {Ciudad: "San Andrés Cholula", cod_pais: "MEX"},
    {Ciudad: "Minatitlán", cod_pais: "MEX"},
    {Ciudad: "Playas de Rosarito", cod_pais: "MEX"},
    {Ciudad: "Boaco", cod_pais: "NIC"},
    {Ciudad: "Jinotepe", cod_pais: "NIC"},
    {Ciudad: "Chinandega", cod_pais: "NIC"},
    {Ciudad: "Juigalpa", cod_pais: "NIC"},
    {Ciudad: "Puerto Cabezas", cod_pais: "NIC"},
    {Ciudad: "Bluefields", cod_pais: "NIC"},
    {Ciudad: "Estelí", cod_pais: "NIC"},
    {Ciudad: "Granada", cod_pais: "NIC"},
    {Ciudad: "Jinotega", cod_pais: "NIC"},
    {Ciudad: "León", cod_pais: "NIC"},
    {Ciudad: "Somoto", cod_pais: "NIC"},
    {Ciudad: "Managua", cod_pais: "NIC"},
    {Ciudad: "Masaya", cod_pais: "NIC"},
    {Ciudad: "Matagalpa", cod_pais: "NIC"},
    {Ciudad: "Ocotal", cod_pais: "NIC"},
    {Ciudad: "San Carlos", cod_pais: "NIC"},
    {Ciudad: "Rivas", cod_pais: "NIC"},
    {Ciudad: "Panamá", cod_pais: "PAN"},
    {Ciudad: "Colón", cod_pais: "PAN"},
    {Ciudad: "David", cod_pais: "PAN"},
    {Ciudad: "La Chorrera", cod_pais: "PAN"},
    {Ciudad: "Santiago", cod_pais: "PAN"},
    {Ciudad: "Changuinola", cod_pais: "PAN"},
    {Ciudad: "Penonomé", cod_pais: "PAN"},
    {Ciudad: "Bugaba", cod_pais: "PAN"},
    {Ciudad: "Puerto Armuelles", cod_pais: "PAN"},
    {Ciudad: "Antón", cod_pais: "PAN"},
    {Ciudad: "Chepo", cod_pais: "PAN"},
    {Ciudad: "Chitré", cod_pais: "PAN"},
    {Ciudad: "Aguadulce", cod_pais: "PAN"},
    {Ciudad: "Capira", cod_pais: "PAN"},
    {Ciudad: "Chame", cod_pais: "PAN"},
    {Ciudad: "Soná", cod_pais: "PAN"},
    {Ciudad: "Almirante", cod_pais: "PAN"},
    {Ciudad: "La Pintada", cod_pais: "PAN"},
    {Ciudad: "Las Tablas", cod_pais: "PAN"},
    {Ciudad: "La Villa de Los Santos", cod_pais: "PAN"},
    {Ciudad: "Asunción", cod_pais: "PRY"},
    {Ciudad: "Ciudad del Este", cod_pais: "PRY"},
    {Ciudad: "Luque", cod_pais: "PRY"},
    {Ciudad: "San Lorenzo", cod_pais: "PRY"},
    {Ciudad: "Capiatá", cod_pais: "PRY"},
    {Ciudad: "Lambaré", cod_pais: "PRY"},
    {Ciudad: "Fernando de la Mora", cod_pais: "PRY"},
    {Ciudad: "Limpio", cod_pais: "PRY"},
    {Ciudad: "Ñemby", cod_pais: "PRY"},
    {Ciudad: "Encarnación", cod_pais: "PRY"},
    {Ciudad: "Caaguazú", cod_pais: "PRY"},
    {Ciudad: "Coronel Oviedo", cod_pais: "PRY"},
    {Ciudad: "Pedro Juan Caballero", cod_pais: "PRY"},
    {Ciudad: "Itauguá", cod_pais: "PRY"},
    {Ciudad: "Presidente Franco", cod_pais: "PRY"},
    {Ciudad: "Mariano Roque Alonso", cod_pais: "PRY"},
    {Ciudad: "Minga Guazú", cod_pais: "PRY"},
    {Ciudad: "Concepción", cod_pais: "PRY"},
    {Ciudad: "Itá", cod_pais: "PRY"},
    {Ciudad: "Villa Elisa", cod_pais: "PRY"},
    {Ciudad: "Hernandarias", cod_pais: "PRY"},
    {Ciudad: "Areguá", cod_pais: "PRY"},
    {Ciudad: "Villarrica", cod_pais: "PRY"},
    {Ciudad: "San Antonio", cod_pais: "PRY"},
    {Ciudad: "Horqueta", cod_pais: "PRY"},
    {Ciudad: "Cambyretá", cod_pais: "PRY"},
    {Ciudad: "Curuguaty", cod_pais: "PRY"},
    {Ciudad: "Ypané", cod_pais: "PRY"},
    {Ciudad: "Caacupé", cod_pais: "PRY"},
    {Ciudad: "San Estanislao", cod_pais: "PRY"},
    {Ciudad: "Julián Augusto Saldívar", cod_pais: "PRY"},
    {Ciudad: "Villa Hayes", cod_pais: "PRY"},
    {Ciudad: "Capiibary", cod_pais: "PRY"},
    {Ciudad: "Santa Rosa del Aguaray", cod_pais: "PRY"},
    {Ciudad: "Villeta", cod_pais: "PRY"},
    {Ciudad: "Salto del Guairá", cod_pais: "PRY"},
    {Ciudad: "San Juan Nepomuceno", cod_pais: "PRY"},
    {Ciudad: "Guarambaré", cod_pais: "PRY"},
    {Ciudad: "Doctor Juan Eulogio Estigarribia", cod_pais: "PRY"},
    {Ciudad: "Itakyry", cod_pais: "PRY"},
    {Ciudad: "Carapeguá", cod_pais: "PRY"},
    {Ciudad: "Santa Rita", cod_pais: "PRY"},
    {Ciudad: "San Pedro de Ycuamandiyú", cod_pais: "PRY"},
    {Ciudad: "San Ignacio Guazú", cod_pais: "PRY"},
    {Ciudad: "Yhú", cod_pais: "PRY"},
    {Ciudad: "Yby Yaú", cod_pais: "PRY"},
    {Ciudad: "San Pedro del Paraná", cod_pais: "PRY"},
    {Ciudad: "Tobatí", cod_pais: "PRY"},
    {Ciudad: "Repatriación", cod_pais: "PRY"},
    {Ciudad: "Pilar", cod_pais: "PRY"},
    {Ciudad: "Abaí", cod_pais: "PRY"},
    {Ciudad: "Yaguarón", cod_pais: "PRY"},
    {Ciudad: "Guayaibí", cod_pais: "PRY"},
    {Ciudad: "Piribebuy", cod_pais: "PRY"},
    {Ciudad: "Mariscal José Félix Estigarribia", cod_pais: "PRY"},
    {Ciudad: "Choré", cod_pais: "PRY"},
    {Ciudad: "Tomás Romero Pereira", cod_pais: "PRY"},
    {Ciudad: "Ypacaraí", cod_pais: "PRY"},
    {Ciudad: "Teniente Primero Manuel Irala Fernández", cod_pais: "PRY"},
    {Ciudad: "Yasy Cañy", cod_pais: "PRY"},
    {Ciudad: "Independencia", cod_pais: "PRY"},
    {Ciudad: "Paso Yobái", cod_pais: "PRY"},
    {Ciudad: "Juan Emiliano O'Leary", cod_pais: "PRY"},
    {Ciudad: "Caazapá", cod_pais: "PRY"},
    {Ciudad: "Arroyos y Esteros", cod_pais: "PRY"},
    {Ciudad: "Ybycuí", cod_pais: "PRY"},
    {Ciudad: "Liberación", cod_pais: "PRY"},
    {Ciudad: "Doctor Juan Manuel Frutos", cod_pais: "PRY"},
    {Ciudad: "General Isidoro Resquín", cod_pais: "PRY"},
    {Ciudad: "Eusebio Ayala", cod_pais: "PRY"},
    {Ciudad: "San Juan Bautista", cod_pais: "PRY"},
    {Ciudad: "Edelira", cod_pais: "PRY"},
    {Ciudad: "Paraguarí", cod_pais: "PRY"},
    {Ciudad: "General Elizardo Aquino", cod_pais: "PRY"},
    {Ciudad: "Yuty", cod_pais: "PRY"},
    {Ciudad: "San Rafael del Paraná", cod_pais: "PRY"},
    {Ciudad: "Doctor Juan León Mallorquín", cod_pais: "PRY"},
    {Ciudad: "Quiindy", cod_pais: "PRY"},
    {Ciudad: "Coronel José Félix Bogado", cod_pais: "PRY"},
    {Ciudad: "Benjamín Aceval", cod_pais: "PRY"},
    {Ciudad: "Natalio", cod_pais: "PRY"},
    {Ciudad: "Emboscada", cod_pais: "PRY"},
    {Ciudad: "San José de los Arroyos", cod_pais: "PRY"},
    {Ciudad: "Tres de Mayo", cod_pais: "PRY"},
    {Ciudad: "Carlos Antonio López", cod_pais: "PRY"},
    {Ciudad: "Filadelfia", cod_pais: "PRY"},
    {Ciudad: "Ayolas", cod_pais: "PRY"},
    {Ciudad: "Tavaí", cod_pais: "PRY"},
    {Ciudad: "Capitán Bado", cod_pais: "PRY"},
    {Ciudad: "Loreto", cod_pais: "PRY"},
    {Ciudad: "Santa Rosa de Lima", cod_pais: "PRY"},
    {Ciudad: "Alto Verá", cod_pais: "PRY"},
    {Ciudad: "San Joaquín", cod_pais: "PRY"},
    {Ciudad: "Pirayú", cod_pais: "PRY"},
    {Ciudad: "Bella Vista Norte", cod_pais: "PRY"},
    {Ciudad: "Villa Ygatimí", cod_pais: "PRY"},
    {Ciudad: "Obligado", cod_pais: "PRY"},
    {Ciudad: "Raúl Arsenio Oviedo", cod_pais: "PRY"},
    {Ciudad: "Loma Plata", cod_pais: "PRY"},
    {Ciudad: "Atyrá", cod_pais: "PRY"},
    {Ciudad: "Itapúa Poty", cod_pais: "PRY"},
    {Ciudad: "Yrybucuá", cod_pais: "PRY"},
    {Ciudad: "Tacuatí", cod_pais: "PRY"},
    {Ciudad: "Acahay", cod_pais: "PRY"},
    {Ciudad: "Carayaó", cod_pais: "PRY"},
    {Ciudad: "Hohenau", cod_pais: "PRY"},
    {Ciudad: "Mayor Otaño", cod_pais: "PRY"},
    {Ciudad: "Minga Porá", cod_pais: "PRY"},
    {Ciudad: "Bella Vista", cod_pais: "PRY"},
    {Ciudad: "Tembiaporá", cod_pais: "PRY"},
    {Ciudad: "Capitán Meza", cod_pais: "PRY"},
    {Ciudad: "Altos", cod_pais: "PRY"},
    {Ciudad: "Mbuyapey", cod_pais: "PRY"},
    {Ciudad: "Capitán Miranda", cod_pais: "PRY"},
    {Ciudad: "Ybyrarobaná", cod_pais: "PRY"},
    {Ciudad: "Caraguatay", cod_pais: "PRY"},
    {Ciudad: "Yatytay", cod_pais: "PRY"},
    {Ciudad: "Belén", cod_pais: "PRY"},
    {Ciudad: "General Artigas", cod_pais: "PRY"},
    {Ciudad: "Santa Rosa del Mbutuy", cod_pais: "PRY"},
    {Ciudad: "Nueva Esperanza", cod_pais: "PRY"},
    {Ciudad: "Nueva Italia", cod_pais: "PRY"},
    {Ciudad: "San Roque González de Santa Cruz", cod_pais: "PRY"},
    {Ciudad: "Yataity del Norte", cod_pais: "PRY"},
    {Ciudad: "San Bernardino", cod_pais: "PRY"},
    {Ciudad: "Lima", cod_pais: "PRY"},
    {Ciudad: "Puerto Pinasco", cod_pais: "PRY"},
    {Ciudad: "General Francisco Caballero Álvarez", cod_pais: "PRY"},
    {Ciudad: "San Lázaro", cod_pais: "PRY"},
    {Ciudad: "Vaquería", cod_pais: "PRY"},
    {Ciudad: "Yby Pytá", cod_pais: "PRY"},
    {Ciudad: "San Alberto", cod_pais: "PRY"},
    {Ciudad: "Itacurubí del Rosario", cod_pais: "PRY"},
    {Ciudad: "José Domingo Ocampos", cod_pais: "PRY"},
    {Ciudad: "Yguazú", cod_pais: "PRY"},
    {Ciudad: "San Cristóbal", cod_pais: "PRY"},
    {Ciudad: "Capitán Mauricio José Troche", cod_pais: "PRY"},
    {Ciudad: "Itacurubí de la Cordillera", cod_pais: "PRY"},
    {Ciudad: "Fram", cod_pais: "PRY"},
    {Ciudad: "Villa del Rosario", cod_pais: "PRY"},
    {Ciudad: "San Cosme y Damián", cod_pais: "PRY"},
    {Ciudad: "Borja", cod_pais: "PRY"},
    {Ciudad: "Los Cedrales", cod_pais: "PRY"},
    {Ciudad: "25 de Diciembre", cod_pais: "PRY"},
    {Ciudad: "Tres de Febrero", cod_pais: "PRY"},
    {Ciudad: "Trinidad", cod_pais: "PRY"},
    {Ciudad: "San Juan del Paraná", cod_pais: "PRY"},
    {Ciudad: "Corpus Christi", cod_pais: "PRY"},
    {Ciudad: "Doctor Raúl Peña", cod_pais: "PRY"},
    {Ciudad: "Regimiento de Infantería Tres Corrales", cod_pais: "PRY"},
    {Ciudad: "Alberdi", cod_pais: "PRY"},
    {Ciudad: "Pirapó", cod_pais: "PRY"},
    {Ciudad: "Azotey", cod_pais: "PRY"},
    {Ciudad: "Ñacunday", cod_pais: "PRY"},
    {Ciudad: "Carmen del Paraná", cod_pais: "PRY"},
    {Ciudad: "Santa María de Fe", cod_pais: "PRY"},
    {Ciudad: "La Paloma del Espíritu Santo", cod_pais: "PRY"},
    {Ciudad: "Mbocayaty del Guairá", cod_pais: "PRY"},
    {Ciudad: "Ypejhú", cod_pais: "PRY"},
    {Ciudad: "Iturbe", cod_pais: "PRY"},
    {Ciudad: "Katueté", cod_pais: "PRY"},
    {Ciudad: "Mbaracayú", cod_pais: "PRY"},
    {Ciudad: "Escobar", cod_pais: "PRY"},
    {Ciudad: "General Eugenio Alejandrino Garay", cod_pais: "PRY"},
    {Ciudad: "Tavapy", cod_pais: "PRY"},
    {Ciudad: "Caapucú", cod_pais: "PRY"},
    {Ciudad: "Doctor Cecilio Báez", cod_pais: "PRY"},
    {Ciudad: "General Delgado", cod_pais: "PRY"},
    {Ciudad: "Zanja Pytá", cod_pais: "PRY"},
    {Ciudad: "Isla Pucú", cod_pais: "PRY"},
    {Ciudad: "Itapé", cod_pais: "PRY"},
    {Ciudad: "Nueva Alborada", cod_pais: "PRY"},
    {Ciudad: "Santa Rosa del Monday", cod_pais: "PRY"},
    {Ciudad: "Quyquyhó", cod_pais: "PRY"},
    {Ciudad: "Ybytymí", cod_pais: "PRY"},
    {Ciudad: "Nueva Germania", cod_pais: "PRY"},
    {Ciudad: "Coronel Martínez", cod_pais: "PRY"},
    {Ciudad: "General Bernardino Caballero", cod_pais: "PRY"},
    {Ciudad: "Unión", cod_pais: "PRY"},
    {Ciudad: "Sargento José Félix López", cod_pais: "PRY"},
    {Ciudad: "Mariscal Francisco Solano López", cod_pais: "PRY"},
    {Ciudad: "Valenzuela", cod_pais: "PRY"},
    {Ciudad: "Juan de Mena", cod_pais: "PRY"},
    {Ciudad: "José A. Fassardi", cod_pais: "PRY"},
    {Ciudad: "Fulgencio Yegros", cod_pais: "PRY"},
    {Ciudad: "Sapucai", cod_pais: "PRY"},
    {Ciudad: "Puerto Casado", cod_pais: "PRY"},
    {Ciudad: "Primero de Marzo", cod_pais: "PRY"},
    {Ciudad: "Santiago", cod_pais: "PRY"},
    {Ciudad: "Simón Bolívar", cod_pais: "PRY"},
    {Ciudad: "Félix Pérez Cardozo", cod_pais: "PRY"},
    {Ciudad: "Jesús", cod_pais: "PRY"},
    {Ciudad: "General Higinio Morínigo", cod_pais: "PRY"},
    {Ciudad: "Iruña", cod_pais: "PRY"},
    {Ciudad: "Buena Vista", cod_pais: "PRY"},
    {Ciudad: "San Miguel", cod_pais: "PRY"},
    {Ciudad: "Nanawa", cod_pais: "PRY"},
    {Ciudad: "San Juan Bautista del Ñeembucú", cod_pais: "PRY"},
    {Ciudad: "San Alfredo", cod_pais: "PRY"},
    {Ciudad: "Naranjal", cod_pais: "PRY"},
    {Ciudad: "Doctor Moisés Santiago Bertoni", cod_pais: "PRY"},
    {Ciudad: "La Colmena", cod_pais: "PRY"},
    {Ciudad: "Cerrito", cod_pais: "PRY"},
    {Ciudad: "Domingo Martínez de Irala", cod_pais: "PRY"},
    {Ciudad: "Karapaí", cod_pais: "PRY"},
    {Ciudad: "La Pastora", cod_pais: "PRY"},
    {Ciudad: "Natalicio Talavera", cod_pais: "PRY"},
    {Ciudad: "Nueva Toledo", cod_pais: "PRY"},
    {Ciudad: "Santa Elena", cod_pais: "PRY"},
    {Ciudad: "Nueva Londres", cod_pais: "PRY"},
    {Ciudad: "Maciel", cod_pais: "PRY"},
    {Ciudad: "Yataity del Guairá", cod_pais: "PRY"},
    {Ciudad: "José Leandro Oviedo", cod_pais: "PRY"},
    {Ciudad: "Tebicuarymí", cod_pais: "PRY"},
    {Ciudad: "Capitán Carmelo Peralta", cod_pais: "PRY"},
    {Ciudad: "Fuerte Olimpo", cod_pais: "PRY"},
    {Ciudad: "San José Obrero", cod_pais: "PRY"},
    {Ciudad: "Antequera", cod_pais: "PRY"},
    {Ciudad: "Mayor José Martínez", cod_pais: "PRY"},
    {Ciudad: "José Falcón", cod_pais: "PRY"},
    {Ciudad: "Mbocayaty del Yhaguy", cod_pais: "PRY"},
    {Ciudad: "Paso Barreto", cod_pais: "PRY"},
    {Ciudad: "Santa Fe del Paraná", cod_pais: "PRY"},
    {Ciudad: "General José Eduvigis Díaz", cod_pais: "PRY"},
    {Ciudad: "Tacuaras", cod_pais: "PRY"},
    {Ciudad: "Nueva Colombia", cod_pais: "PRY"},
    {Ciudad: "Villa Oliva", cod_pais: "PRY"},
    {Ciudad: "Villa Florida", cod_pais: "PRY"},
    {Ciudad: "San Patricio", cod_pais: "PRY"},
    {Ciudad: "San Pablo", cod_pais: "PRY"},
    {Ciudad: "Loma Grande", cod_pais: "PRY"},
    {Ciudad: "Laureles", cod_pais: "PRY"},
    {Ciudad: "Teniente Esteban Martínez", cod_pais: "PRY"},
    {Ciudad: "Itanará", cod_pais: "PRY"},
    {Ciudad: "Ñumí", cod_pais: "PRY"},
    {Ciudad: "General José María Bruguez", cod_pais: "PRY"},
    {Ciudad: "La Paz", cod_pais: "PRY"},
    {Ciudad: "Tebicuary", cod_pais: "PRY"},
    {Ciudad: "Humaitá", cod_pais: "PRY"},
    {Ciudad: "Isla Umbú", cod_pais: "PRY"},
    {Ciudad: "San Salvador", cod_pais: "PRY"},
    {Ciudad: "Yabebyry", cod_pais: "PRY"},
    {Ciudad: "Bahía Negra", cod_pais: "PRY"},
    {Ciudad: "Villalbín", cod_pais: "PRY"},
    {Ciudad: "Guazú Cuá", cod_pais: "PRY"},
    {Ciudad: "Paso de Patria", cod_pais: "PRY"},
    {Ciudad: "Desmochados", cod_pais: "PRY"},
    {Ciudad: "Doctor Bottrell", cod_pais: "PRY"},
    {Ciudad: "Villa Franca", cod_pais: "PRY"},
    {Ciudad: "San Carlos del Apa", cod_pais: "PRY"},
    {Ciudad: "Maracaná", cod_pais: "PRY"},
    {Ciudad: "María Antonia", cod_pais: "PRY"},
    {Ciudad: "San Vicente Pancholo", cod_pais: "PRY"},
    {Ciudad: "Arroyito", cod_pais: "PRY"},
    {Ciudad: "Puerto Adela", cod_pais: "PRY"},
    {Ciudad: "Paso Horqueta", cod_pais: "PRY"},
    {Ciudad: "Cerro Corá", cod_pais: "PRY"},
    {Ciudad: "Campo Aceval", cod_pais: "PRY"},
    {Ciudad: "Laurel", cod_pais: "PRY"},
    {Ciudad: "Itacuá", cod_pais: "PRY"},
    {Ciudad: "Puerto Ybapobo", cod_pais: "PRY"},
    {Ciudad: "Neuland", cod_pais: "PRY"},
    {Ciudad: "Lima", cod_pais: "PER"},
    {Ciudad: "Arequipa", cod_pais: "PER"},
    {Ciudad: "Callao", cod_pais: "PER"},
    {Ciudad: "Trujillo", cod_pais: "PER"},
    {Ciudad: "Chiclayo", cod_pais: "PER"},
    {Ciudad: "Piura", cod_pais: "PER"},
    {Ciudad: "Huancayo", cod_pais: "PER"},
    {Ciudad: "Cuzco", cod_pais: "PER"},
    {Ciudad: "Chimbote", cod_pais: "PER"},
    {Ciudad: "Iquitos", cod_pais: "PER"},
    {Ciudad: "Pucallpa", cod_pais: "PER"},
    {Ciudad: "Tacna", cod_pais: "PER"},
    {Ciudad: "Ica", cod_pais: "PER"},
    {Ciudad: "Juliaca", cod_pais: "PER"},
    {Ciudad: "Ayacucho", cod_pais: "PER"},
    {Ciudad: "Cajamarca", cod_pais: "PER"},
    {Ciudad: "Huánuco", cod_pais: "PER"},
    {Ciudad: "Tarapoto", cod_pais: "PER"},
    {Ciudad: "Chincha Alta", cod_pais: "PER"},
    {Ciudad: "Huacho", cod_pais: "PER"},
    {Ciudad: "Sullana", cod_pais: "PER"},
    {Ciudad: "Puno", cod_pais: "PER"},
    {Ciudad: "Huaraz", cod_pais: "PER"},
    {Ciudad: "Huaral", cod_pais: "PER"},
    {Ciudad: "Tumbes", cod_pais: "PER"},
    {Ciudad: "Jaén", cod_pais: "PER"},
    {Ciudad: "Cañete", cod_pais: "PER"},
    {Ciudad: "Talara", cod_pais: "PER"},
    {Ciudad: "Paita", cod_pais: "PER"},
    {Ciudad: "Puerto Maldonado", cod_pais: "PER"},
    {Ciudad: "Yurimaguas", cod_pais: "PER"},
    {Ciudad: "Chulucanas", cod_pais: "PER"},
    {Ciudad: "Catacaos", cod_pais: "PER"},
    {Ciudad: "Pisco", cod_pais: "PER"},
    {Ciudad: "Abancay", cod_pais: "PER"},
    {Ciudad: "Lambayeque", cod_pais: "PER"},
    {Ciudad: "Huaura", cod_pais: "PER"},
    {Ciudad: "Moquegua", cod_pais: "PER"},
    {Ciudad: "Huanchaco", cod_pais: "PER"},
    {Ciudad: "Barranca", cod_pais: "PER"},
    {Ciudad: "Ilo", cod_pais: "PER"},
    {Ciudad: "San Miguel", cod_pais: "PER"},
    {Ciudad: "Majes", cod_pais: "PER"},
    {Ciudad: "Cerro de Pasco", cod_pais: "PER"},
    {Ciudad: "Andahuaylas", cod_pais: "PER"},
    {Ciudad: "Sicuani", cod_pais: "PER"},
    {Ciudad: "Chancay", cod_pais: "PER"},
    {Ciudad: "Tingo María", cod_pais: "PER"},
    {Ciudad: "Moyobamba", cod_pais: "PER"},
    {Ciudad: "Huancavelica", cod_pais: "PER"},
    {Ciudad: "Distrito Nacional", cod_pais: "DOM"},
    {Ciudad: "Santo Domingo Este", cod_pais: "DOM"},
    {Ciudad: "Santiago de los Caballeros", cod_pais: "DOM"},
    {Ciudad: "Santo Domingo Norte", cod_pais: "DOM"},
    {Ciudad: "Santo Domingo Oeste", cod_pais: "DOM"},
    {Ciudad: "Higuey", cod_pais: "DOM"},
    {Ciudad: "San Luis", cod_pais: "DOM"},
    {Ciudad: "San Felipe de Puerto Plata", cod_pais: "DOM"},
    {Ciudad: "San Cristóbal", cod_pais: "DOM"},
    {Ciudad: "San Pedro de Macoris", cod_pais: "DOM"},
    {Ciudad: "Los Alcarrizos", cod_pais: "DOM"},
    {Ciudad: "La Vega", cod_pais: "DOM"},
    {Ciudad: "San Francisco de Macorís", cod_pais: "DOM"},
    {Ciudad: "La Romana", cod_pais: "DOM"},
    {Ciudad: "Moca", cod_pais: "DOM"},
    {Ciudad: "Villa Altagracia", cod_pais: "DOM"},
    {Ciudad: "San Juan de La Maguana", cod_pais: "DOM"},
    {Ciudad: "Haina", cod_pais: "DOM"},
    {Ciudad: "Bonao", cod_pais: "DOM"},
    {Ciudad: "Cotuí", cod_pais: "DOM"},
    {Ciudad: "Baní", cod_pais: "DOM"},
    {Ciudad: "Santa Cruz de Barahona", cod_pais: "DOM"},
    {Ciudad: "Azua de Compostela", cod_pais: "DOM"},
    {Ciudad: "Boca Chica", cod_pais: "DOM"},
    {Ciudad: "Villa hermosa", cod_pais: "DOM"},
    {Ciudad: "Mao", cod_pais: "DOM"},
    {Ciudad: "Pedro Brand", cod_pais: "DOM"},
    {Ciudad: "San Antonio de Guerra", cod_pais: "DOM"},
    {Ciudad: "San Ignacio de Sabaneta", cod_pais: "DOM"},
    {Ciudad: "Santa Cruz del Seibo", cod_pais: "DOM"},
    {Ciudad: "Tamboril", cod_pais: "DOM"},
    {Ciudad: "Nagua", cod_pais: "DOM"},
    {Ciudad: "Puñal", cod_pais: "DOM"},
    {Ciudad: "Hato Mayor del Rey", cod_pais: "DOM"},
    {Ciudad: "Esperanza", cod_pais: "DOM"},
    {Ciudad: "Sosúa", cod_pais: "DOM"},
    {Ciudad: "Jarabacoa", cod_pais: "DOM"},
    {Ciudad: "San José de las Matas", cod_pais: "DOM"},
    {Ciudad: "Yamasá", cod_pais: "DOM"},
    {Ciudad: "Monte Plata", cod_pais: "DOM"},
    {Ciudad: "Villa González", cod_pais: "DOM"},
    {Ciudad: "Montevideo", cod_pais: "URY"},
    {Ciudad: "Ciudad de la Costa", cod_pais: "URY"},
    {Ciudad: "Salto", cod_pais: "URY"},
    {Ciudad: "Paysandú", cod_pais: "URY"},
    {Ciudad: "Maldonado", cod_pais: "URY"},
    {Ciudad: "Rivera", cod_pais: "URY"},
    {Ciudad: "Las Piedras", cod_pais: "URY"},
    {Ciudad: "Tacuarembó", cod_pais: "URY"},
    {Ciudad: "Melo", cod_pais: "URY"},
    {Ciudad: "Artigas", cod_pais: "URY"},
    {Ciudad: "Mercedes", cod_pais: "URY"},
    {Ciudad: "Minas", cod_pais: "URY"},
    {Ciudad: "San José de Mayo", cod_pais: "URY"},
    {Ciudad: "Durazno", cod_pais: "URY"},
    {Ciudad: "Florida", cod_pais: "URY"},
    {Ciudad: "Treinta y Tres", cod_pais: "URY"},
    {Ciudad: "Barros Blancos", cod_pais: "URY"},
    {Ciudad: "Ciudad del Plata", cod_pais: "URY"},
    {Ciudad: "San Carlos", cod_pais: "URY"},
    {Ciudad: "Colonia del Sacramento", cod_pais: "URY"},
    {Ciudad: "Pando", cod_pais: "URY"},
    {Ciudad: "Rocha", cod_pais: "URY"},
    {Ciudad: "Fray Bentos", cod_pais: "URY"},
    {Ciudad: "Salinas", cod_pais: "URY"},
    {Ciudad: "Trinidad", cod_pais: "URY"},
    {Ciudad: "18 de Mayo", cod_pais: "URY"},
    {Ciudad: "La Paz", cod_pais: "URY"},
    {Ciudad: "Canelones", cod_pais: "URY"},
    {Ciudad: "Dolores", cod_pais: "URY"},
    {Ciudad: "Carmelo", cod_pais: "URY"},
    {Ciudad: "Bella Unión", cod_pais: "URY"},
    {Ciudad: "Young", cod_pais: "URY"},
    {Ciudad: "Santa Lucía", cod_pais: "URY"},
    {Ciudad: "Progreso", cod_pais: "URY"},
    {Ciudad: "Paso Carrasco", cod_pais: "URY"},
    {Ciudad: "Joaquín Suárez", cod_pais: "URY"},
    {Ciudad: "Nueva Helvecia", cod_pais: "URY"},
    {Ciudad: "General Líber Seregni", cod_pais: "URY"},
    {Ciudad: "Río Branco", cod_pais: "URY"},
    {Ciudad: "Toledo", cod_pais: "URY"},
    {Ciudad: "Paso de los Toros", cod_pais: "URY"},
    {Ciudad: "Juan Lacaze", cod_pais: "URY"},
    {Ciudad: "Punta del Este", cod_pais: "URY"},
    {Ciudad: "Parque del Plata", cod_pais: "URY"},
    {Ciudad: "Piriápolis", cod_pais: "URY"},
    {Ciudad: "Libertad", cod_pais: "URY"},
    {Ciudad: "Rosario", cod_pais: "URY"},
    {Ciudad: "Nueva Palmira", cod_pais: "URY"},
    {Ciudad: "Chuy", cod_pais: "URY"},
    {Ciudad: "Atlántida", cod_pais: "URY"},
    {Ciudad: "Cardona", cod_pais: "URY"},
    {Ciudad: "Lascano", cod_pais: "URY"},
    {Ciudad: "Castillos", cod_pais: "URY"},
    {Ciudad: "Pan de Azúcar", cod_pais: "URY"},
    {Ciudad: "Tranqueras", cod_pais: "URY"},
    {Ciudad: "Sarandí del Yí", cod_pais: "URY"},
    {Ciudad: "San Ramón", cod_pais: "URY"},
    {Ciudad: "Tarariras", cod_pais: "URY"},
    {Ciudad: "Sauce", cod_pais: "URY"},
    {Ciudad: "Sarandí Grande", cod_pais: "URY"},
    {Ciudad: "José Pedro Varela", cod_pais: "URY"},
    {Ciudad: "Tala", cod_pais: "URY"},
    {Ciudad: "Guichón", cod_pais: "URY"},
    {Ciudad: "La Paloma", cod_pais: "URY"},
    {Ciudad: "Caracas", cod_pais: "VEN"},
    {Ciudad: "Maracaibo", cod_pais: "VEN"},
    {Ciudad: "Valencia", cod_pais: "VEN"},
    {Ciudad: "Barquisimeto", cod_pais: "VEN"},
    {Ciudad: "Maracay", cod_pais: "VEN"},
    {Ciudad: "Ciudad Guayana", cod_pais: "VEN"},
    {Ciudad: "Barcelona", cod_pais: "VEN"},
    {Ciudad: "San Cristóbal", cod_pais: "VEN"},
    {Ciudad: "Maturín", cod_pais: "VEN"},
    {Ciudad: "Barinas", cod_pais: "VEN"},
    {Ciudad: "Ciudad Bolívar", cod_pais: "VEN"},
    {Ciudad: "Cumaná", cod_pais: "VEN"},
    {Ciudad: "Mérida", cod_pais: "VEN"},
    {Ciudad: "Valera", cod_pais: "VEN"},
    {Ciudad: "Cabimas", cod_pais: "VEN"},
    {Ciudad: "Santa Teresa del Tuy", cod_pais: "VEN"},
    {Ciudad: "Punto Fijo", cod_pais: "VEN"},
    {Ciudad: "Acarigua", cod_pais: "VEN"},
    {Ciudad: "Los Teques", cod_pais: "VEN"},
    {Ciudad: "Coro", cod_pais: "VEN"},
    {Ciudad: "Guanare", cod_pais: "VEN"},
    {Ciudad: "Ciudad Ojeda", cod_pais: "VEN"},
    {Ciudad: "Puerto Cabello", cod_pais: "VEN"},
    {Ciudad: "Guarenas", cod_pais: "VEN"},
    {Ciudad: "Puerto La Cruz", cod_pais: "VEN"},
    {Ciudad: "Guatire", cod_pais: "VEN"},
    {Ciudad: "Turmero", cod_pais: "VEN"},
    {Ciudad: "Tocuyito", cod_pais: "VEN"},
    {Ciudad: "El Tigre", cod_pais: "VEN"},
    {Ciudad: "Carora", cod_pais: "VEN"},
    {Ciudad: "La Victoria", cod_pais: "VEN"},
    {Ciudad: "Cabudare", cod_pais: "VEN"},
    {Ciudad: "Carúpano", cod_pais: "VEN"},
    {Ciudad: "San Fernando de Apure", cod_pais: "VEN"},
    {Ciudad: "Guacara", cod_pais: "VEN"},
    {Ciudad: "El Tocuyo", cod_pais: "VEN"},
    {Ciudad: "Los Guayos", cod_pais: "VEN"},
    {Ciudad: "Santa Rita", cod_pais: "VEN"},
    {Ciudad: "Güigüe", cod_pais: "VEN"},
    {Ciudad: "Anaco", cod_pais: "VEN"},
    {Ciudad: "San Juan de Los Morros", cod_pais: "VEN"},
    {Ciudad: "Quibor", cod_pais: "VEN"},
    {Ciudad: "El Vigía", cod_pais: "VEN"},
    {Ciudad: "Palo Negro", cod_pais: "VEN"},
    {Ciudad: "San Felipe", cod_pais: "VEN"},
    {Ciudad: "San Carlos", cod_pais: "VEN"},
    {Ciudad: "Mariara", cod_pais: "VEN"},
    {Ciudad: "Villa de Cura", cod_pais: "VEN"},
    {Ciudad: "Ocumare del Tuy", cod_pais: "VEN"},
    {Ciudad: "Yaritagua", cod_pais: "VEN"},
    {Ciudad: "Cúa", cod_pais: "VEN"},
    {Ciudad: "Araure", cod_pais: "VEN"},
    {Ciudad: "Calabozo", cod_pais: "VEN"},
    {Ciudad: "Táriba", cod_pais: "VEN"},
    {Ciudad: "Guasdualito", cod_pais: "VEN"},
    {Ciudad: "Puerto Ayacucho", cod_pais: "VEN"},
    {Ciudad: "Machiques", cod_pais: "VEN"},
    {Ciudad: "Cagua", cod_pais: "VEN"},
    {Ciudad: "Porlamar", cod_pais: "VEN"},
    {Ciudad: "Charallave", cod_pais: "VEN"},
    {Ciudad: "La Asunción", cod_pais: "VEN"},
    {Ciudad: "Valle de la Pascua", cod_pais: "VEN"},
    {Ciudad: "Santa Lucía", cod_pais: "VEN"},
    {Ciudad: "Trujillo", cod_pais: "VEN"},
    {Ciudad: "El Valle del Espiritu Santo", cod_pais: "VEN"},
    {Ciudad: "Tinaquillo", cod_pais: "VEN"},
    {Ciudad: "Puerto Píritu", cod_pais: "VEN"},
    {Ciudad: "El Limón", cod_pais: "VEN"},
    {Ciudad: "Socopó", cod_pais: "VEN"},
    {Ciudad: "Boconó", cod_pais: "VEN"},
    {Ciudad: "Punta de Mata", cod_pais: "VEN"},
    {Ciudad: "Ejido", cod_pais: "VEN"},
    {Ciudad: "Upata", cod_pais: "VEN"},
    {Ciudad: "Rubio", cod_pais: "VEN"},
    {Ciudad: "Caja Seca", cod_pais: "VEN"},
    {Ciudad: "Catia La Mar", cod_pais: "VEN"},
    {Ciudad: "Tumeremo", cod_pais: "VEN"},
    {Ciudad: "Cantaura", cod_pais: "VEN"},
    {Ciudad: "La Grita", cod_pais: "VEN"},
    {Ciudad: "Santa Bárbara del Zulia", cod_pais: "VEN"},
    {Ciudad: "Tucupita", cod_pais: "VEN"},
    {Ciudad: "San José de Guanipa", cod_pais: "VEN"},
    {Ciudad: "Chivacoa", cod_pais: "VEN"},
    {Ciudad: "Lechería", cod_pais: "VEN"},
    {Ciudad: "Zaraza", cod_pais: "VEN"},
    {Ciudad: "Nirgua", cod_pais: "VEN"},
    {Ciudad: "Siquisique", cod_pais: "VEN"},
    {Ciudad: "Santa Rita", cod_pais: "VEN"},
    {Ciudad: "Guanta", cod_pais: "VEN"},
    {Ciudad: "Morón", cod_pais: "VEN"},
    {Ciudad: "Pariaguán", cod_pais: "VEN"},
    {Ciudad: "San Juan de Colón", cod_pais: "VEN"},
    {Ciudad: "San Joaquín", cod_pais: "VEN"},
    {Ciudad: "San Antonio de los Altos", cod_pais: "VEN"},
    {Ciudad: "Caicara del Orinoco", cod_pais: "VEN"},
    {Ciudad: "Achaguas", cod_pais: "VEN"},
    {Ciudad: "Biruaca", cod_pais: "VEN"},
    {Ciudad: "Pampatar", cod_pais: "VEN"},
    {Ciudad: "La Guaira", cod_pais: "VEN"},
    {Ciudad: "Maiquetía", cod_pais: "VEN"},

]

module.exports = {ciudades, paises, monedas, regiones, clientes, generos, usuarios, precios, detalle_desafios, desafios, unidades, tipo_usuarios, familias, categorias, subcategoria, productos};

