export const unidades = [
    {code_um: 'kg', name: 'kilogramo'},
    {code_um: 'gm', name: 'gramo'},
    {code_um: 'mg', name: 'miligramo'},
    {code_um: 'lb', name: 'libra'},
    {code_um: 'un', name: 'unidad'},
    {code_um: 'pq', name: 'paquete'},
    {code_um: 'lt', name: 'litro'},
    {code_um: 'ml', name: 'mililitro'},
    {code_um: 'oz', name: 'onza'},
    

]

export const tipo_usuarios = [
    {id: 1, tipo: 'hunter (cazador)'},
    {id: 2, tipo: 'challenger (cliente)'},
    {id: 3, tipo: 'admin (administrador)'},
    {id: 4, tipo: 'retailer (tienda / distribuidor)'},
]

export const familias = [
    {id_familia: 1 , familia: "Almacén"},
    {id_familia: 2 , familia: "Frescos"},
    {id_familia: 3 , familia: "Bebidas"},
]

export const categorias = [
    {Id_categoria: 1 , categoria: "Aceites_y_Aderezos" , id_familia: 1},
    {Id_categoria: 2 , categoria: "Aceitunas_y_Encurtidos" , id_familia: 1},
    {Id_categoria: 3 , categoria: "Conservas" , id_familia: 1},
    {Id_categoria: 4 , categoria: "Desayuno_y_Golosinas" , id_familia: 1},
    {Id_categoria: 5 , categoria: "Panificados" , id_familia: 1},
    {Id_categoria: 6 , categoria: "Arroz_y_Legumbres" , id_familia: 1},
    {Id_categoria: 7 , categoria: "Snacks" , id_familia: 1},
    {Id_categoria: 8 , categoria: "Sopas,_Caldos_y_Puré" , id_familia: 1},
    {Id_categoria: 9 , categoria: "Pastas_y_Harinas" , id_familia: 1},
    {Id_categoria: 10 , categoria: "Lácteos" , id_familia: 2},
    {Id_categoria: 11 , categoria: "Pastas y Tapas" , id_familia: 2},
    {Id_categoria: 12 , categoria: "Carnicería y Pescadería" , id_familia: 2},
    {Id_categoria: 13 , categoria: "Verdulería" , id_familia: 2},
    {Id_categoria: 14 , categoria: "Fiambrería" , id_familia: 2},
    {Id_categoria: 15 , categoria: "Congelados" , id_familia: 2},
    {Id_categoria: 16 , categoria: "Panadería y Repostería" , id_familia: 2},
    {Id_categoria: 17 , categoria: "Aperitivos" , id_familia: 3},
    {Id_categoria: 18 , categoria: "Cerveza" , id_familia: 3},
    {Id_categoria: 19 , categoria: "Vinos y Espumantes" , id_familia: 3},
    {Id_categoria: 20 , categoria: "Bebidas blancas y Licores" , id_familia: 3},
    {Id_categoria: 21 , categoria: "A Base de Hierbas" , id_familia: 3},
    {Id_categoria: 22 , categoria: "Aguas" , id_familia: 3},
    {Id_categoria: 23 , categoria: "Gaseosas" , id_familia: 3},
    {Id_categoria: 24 , categoria: "Jugos" , id_familia: 3},
    {Id_categoria: 25 , categoria: "Isotónicas y Energizantes" , id_familia: 3},
]

export const subcategoria =[
    {id_sub: 1 , subcategoria: "Aceites" , Id_categoria: 1},
    {id_sub: 2 , subcategoria: "Mayonesa" , Id_categoria: 1},
    {id_sub: 3 , subcategoria: "Ketchup" , Id_categoria: 1},
    {id_sub: 4 , subcategoria: "Salsa_Golf" , Id_categoria: 1},
    {id_sub: 5 , subcategoria: "Mostaza" , Id_categoria: 1},
    {id_sub: 6 , subcategoria: "Vinagre" , Id_categoria: 1},
    {id_sub: 7 , subcategoria: "Aceto" , Id_categoria: 1},
    {id_sub: 8 , subcategoria: "Jugo_de_Limón" , Id_categoria: 1},
    {id_sub: 9 , subcategoria: "Aderezos_Salsas" , Id_categoria: 1},
    {id_sub: 10 , subcategoria: "Sal_y_Pimienta" , Id_categoria: 1},
    {id_sub: 11 , subcategoria: "Saborizadores" , Id_categoria: 1},
    {id_sub: 12 , subcategoria: "Otros_Condimentos" , Id_categoria: 1},
    {id_sub: 13 , subcategoria: "Aceitunas_Verdes" , Id_categoria: 2},
    {id_sub: 14 , subcategoria: "Aceitunas_Negras" , Id_categoria: 2},
    {id_sub: 15 , subcategoria: "Aceitunas_Rellenas" , Id_categoria: 2},
    {id_sub: 16 , subcategoria: "Encurtidos" , Id_categoria: 2},
    {id_sub: 17 , subcategoria: "Conservas_de_Verdura_y_Legumbres" , Id_categoria: 3},
    {id_sub: 18 , subcategoria: "Conservas_de_Pescado" , Id_categoria: 3},
    {id_sub: 19 , subcategoria: "Conservas_de_Frutas" , Id_categoria: 3},
    {id_sub: 20 , subcategoria: "Tomates_y_Salsas" , Id_categoria: 3},
    {id_sub: 21 , subcategoria: "Azúcar_y_Edulcorante" , Id_categoria: 4},
    {id_sub: 22 , subcategoria: "Cacao" , Id_categoria: 4},
    {id_sub: 23 , subcategoria: "Leche_en_Polvo" , Id_categoria: 4},
    {id_sub: 24 , subcategoria: "Mermeladas_y_Dulces" , Id_categoria: 4},
    {id_sub: 25 , subcategoria: "Café" , Id_categoria: 4},
    {id_sub: 26 , subcategoria: "Té" , Id_categoria: 4},
    {id_sub: 27 , subcategoria: "Yerbas" , Id_categoria: 4},
    {id_sub: 28 , subcategoria: "Repostería" , Id_categoria: 4},
    {id_sub: 29 , subcategoria: "Golosinas" , Id_categoria: 4},
    {id_sub: 30 , subcategoria: "Cereales" , Id_categoria: 4},
    {id_sub: 31 , subcategoria: "Galletitas_Dulces" , Id_categoria: 4},
    {id_sub: 32 , subcategoria: "Galletitas_Saladas" , Id_categoria: 4},
    {id_sub: 33 , subcategoria: "Galletitas_de_Arroz" , Id_categoria: 4},
    {id_sub: 34 , subcategoria: "Pan_Árabe_y_Otros" , Id_categoria: 5},
    {id_sub: 35 , subcategoria: "Pan_de_Molde" , Id_categoria: 5},
    {id_sub: 36 , subcategoria: "Pan_de_Hamburguesas_y_Panchos" , Id_categoria: 5},
    {id_sub: 37 , subcategoria: "Pan_Rallado_y_Rebozadores" , Id_categoria: 5},
    {id_sub: 38 , subcategoria: "Tostadas" , Id_categoria: 5},
    {id_sub: 39 , subcategoria: "Budines_y_Otros" , Id_categoria: 5},
    {id_sub: 40 , subcategoria: "Prepizzas" , Id_categoria: 5},
    {id_sub: 41 , subcategoria: "Madalenas" , Id_categoria: 5},
    {id_sub: 42 , subcategoria: "Arroz_Largo" , Id_categoria: 6},
    {id_sub: 43 , subcategoria: "Arroz_Parboil" , Id_categoria: 6},
    {id_sub: 44 , subcategoria: "Arroz_Doble" , Id_categoria: 6},
    {id_sub: 45 , subcategoria: "Arroz_Integral" , Id_categoria: 6},
    {id_sub: 46 , subcategoria: "Arroz_Especial" , Id_categoria: 6},
    {id_sub: 47 , subcategoria: "Arroz_Preparado" , Id_categoria: 6},
    {id_sub: 48 , subcategoria: "Legumbres" , Id_categoria: 6},
    {id_sub: 49 , subcategoria: "Papas_Fritas" , Id_categoria: 7},
    {id_sub: 50 , subcategoria: "Chizitos" , Id_categoria: 7},
    {id_sub: 51 , subcategoria: "Maní" , Id_categoria: 7},
    {id_sub: 52 , subcategoria: "Palitos" , Id_categoria: 7},
    {id_sub: 53 , subcategoria: "Tortillas" , Id_categoria: 7},
    {id_sub: 54 , subcategoria: "Pochoclos" , Id_categoria: 7},
    {id_sub: 55 , subcategoria: "Conos" , Id_categoria: 7},
    {id_sub: 56 , subcategoria: "Snacks_Mix" , Id_categoria: 7},
    {id_sub: 57 , subcategoria: "Frutas_Secas" , Id_categoria: 7},
    {id_sub: 58 , subcategoria: "Sopas" , Id_categoria: 8},
    {id_sub: 59 , subcategoria: "Caldos" , Id_categoria: 8},
    {id_sub: 60 , subcategoria: "Puré" , Id_categoria: 8},
    {id_sub: 61 , subcategoria: "Pastas" , Id_categoria: 9},
    {id_sub: 62 , subcategoria: "Harinas" , Id_categoria: 9},
    {id_sub: 63 , subcategoria: "Leches" , Id_categoria: 10},
    {id_sub: 64 , subcategoria: "Leches infantiles" , Id_categoria: 10},
    {id_sub: 65 , subcategoria: "Yogures" , Id_categoria: 10},
    {id_sub: 66 , subcategoria: "Cremas de Leche" , Id_categoria: 10},
    {id_sub: 67 , subcategoria: "Dulce de Leche" , Id_categoria: 10},
    {id_sub: 68 , subcategoria: "Levaduras y Grasas" , Id_categoria: 10},
    {id_sub: 69 , subcategoria: "Mantecas y Margarinas" , Id_categoria: 10},
    {id_sub: 70 , subcategoria: "Postres y Flanes" , Id_categoria: 10},
    {id_sub: 71 , subcategoria: "Ricota" , Id_categoria: 10},
    {id_sub: 72 , subcategoria: "Quesos Untables" , Id_categoria: 10},
    {id_sub: 73 , subcategoria: "Fideos" , Id_categoria: 11},
    {id_sub: 74 , subcategoria: "Ñoquis" , Id_categoria: 11},
    {id_sub: 75 , subcategoria: "Pastas Rellenas" , Id_categoria: 11},
    {id_sub: 76 , subcategoria: "Tapas de Tarta" , Id_categoria: 11},
    {id_sub: 77 , subcategoria: "Tapas de Empanadas" , Id_categoria: 11},
    {id_sub: 78 , subcategoria: "Otras Tapas" , Id_categoria: 11},
    {id_sub: 79 , subcategoria: "Carne de cerdo" , Id_categoria: 12},
    {id_sub: 80 , subcategoria: "Carne Vacuna" , Id_categoria: 12},
    {id_sub: 81 , subcategoria: "Carnes Preparadas" , Id_categoria: 12},
    {id_sub: 82 , subcategoria: "Embutidos" , Id_categoria: 12},
    {id_sub: 83 , subcategoria: "Pollo" , Id_categoria: 12},
    {id_sub: 84 , subcategoria: "Huevos" , Id_categoria: 12},
    {id_sub: 85 , subcategoria: "Pescados y Mariscos" , Id_categoria: 12},
    {id_sub: 86 , subcategoria: "Carbón, Leña y Encendido" , Id_categoria: 12},
    {id_sub: 87 , subcategoria: "Granja" , Id_categoria: 12},
    {id_sub: 88 , subcategoria: "Frutas" , Id_categoria: 13},
    {id_sub: 89 , subcategoria: "Frutas Secas y Desecadas" , Id_categoria: 13},
    {id_sub: 90 , subcategoria: "Verduras" , Id_categoria: 13},
    {id_sub: 91 , subcategoria: "Fiambres" , Id_categoria: 14},
    {id_sub: 92 , subcategoria: "Salchichas" , Id_categoria: 14},
    {id_sub: 93 , subcategoria: "Quesos Blandos" , Id_categoria: 14},
    {id_sub: 94 , subcategoria: "Quesos Semiduros" , Id_categoria: 14},
    {id_sub: 95 , subcategoria: "Quesos Duros" , Id_categoria: 14},
    {id_sub: 96 , subcategoria: "Quesos Rallados" , Id_categoria: 14},
    {id_sub: 97 , subcategoria: "Dulces" , Id_categoria: 14},
    {id_sub: 98 , subcategoria: "Quesos Especiales" , Id_categoria: 14},
    {id_sub: 99 , subcategoria: "Hamburguesas" , Id_categoria: 15},
    {id_sub: 100 , subcategoria: "Papas" , Id_categoria: 15},
    {id_sub: 101 , subcategoria: "Milanesas de Soja" , Id_categoria: 15},
    {id_sub: 102 , subcategoria: "Prefritos" , Id_categoria: 15},
    {id_sub: 103 , subcategoria: "Vegetales" , Id_categoria: 15},
    {id_sub: 104 , subcategoria: "Comidas Preparadas" , Id_categoria: 15},
    {id_sub: 105 , subcategoria: "Pizzas" , Id_categoria: 15},
    {id_sub: 106 , subcategoria: "Helados" , Id_categoria: 15},
    {id_sub: 107 , subcategoria: "Frutas" , Id_categoria: 15},
    {id_sub: 108 , subcategoria: "Donuts" , Id_categoria: 16},
    {id_sub: 109 , subcategoria: "Facturería" , Id_categoria: 16},
    {id_sub: 110 , subcategoria: "Galletitas, alfajores y panes dulces" , Id_categoria: 16},
    {id_sub: 111 , subcategoria: "Panificados" , Id_categoria: 16},
    {id_sub: 112 , subcategoria: "Piononos, budines y madalenas" , Id_categoria: 16},
    {id_sub: 113 , subcategoria: "Sandwichería" , Id_categoria: 16},
    {id_sub: 114 , subcategoria: "Tortas y tartas" , Id_categoria: 16},
    {id_sub: 115 , subcategoria: "Americano" , Id_categoria: 17},
    {id_sub: 116 , subcategoria: "Fernet" , Id_categoria: 17},
    {id_sub: 117 , subcategoria: "Otros Aperitivos" , Id_categoria: 17},
    {id_sub: 118 , subcategoria: "Negras y Rojas" , Id_categoria: 18},
    {id_sub: 119 , subcategoria: "Rubias" , Id_categoria: 18},
    {id_sub: 120 , subcategoria: "Sin Alcohol" , Id_categoria: 18},
    {id_sub: 121 , subcategoria: "Espumantes" , Id_categoria: 19},
    {id_sub: 122 , subcategoria: "Vino Blanco" , Id_categoria: 19},
    {id_sub: 123 , subcategoria: "Vino Rosado" , Id_categoria: 19},
    {id_sub: 124 , subcategoria: "Vino Tinto" , Id_categoria: 19},
    {id_sub: 125 , subcategoria: "Bebidas Blancas" , Id_categoria: 20},
    {id_sub: 126 , subcategoria: "Licores" , Id_categoria: 20},
    {id_sub: 127 , subcategoria: "Whiskys" , Id_categoria: 20},
    {id_sub: 128 , subcategoria: "Amargos" , Id_categoria: 21},
    {id_sub: 129 , subcategoria: "Agua Con Gas" , Id_categoria: 22},
    {id_sub: 130 , subcategoria: "Agua Saborizada" , Id_categoria: 22},
    {id_sub: 131 , subcategoria: "Agua Sin Gas" , Id_categoria: 22},
    {id_sub: 132 , subcategoria: "Cola" , Id_categoria: 23},
    {id_sub: 133 , subcategoria: "Gaseosa de Naranja" , Id_categoria: 23},
    {id_sub: 134 , subcategoria: "Gaseosa Sabor Pomelo" , Id_categoria: 23},
    {id_sub: 135 , subcategoria: "Lima Limón" , Id_categoria: 23},
    {id_sub: 136 , subcategoria: "Otras Gaseosas" , Id_categoria: 23},
    {id_sub: 137 , subcategoria: "Tónica" , Id_categoria: 23},
    {id_sub: 138 , subcategoria: "Jugos Concentrados" , Id_categoria: 24},
    {id_sub: 139 , subcategoria: "Jugos en Polvo" , Id_categoria: 24},
    {id_sub: 140 , subcategoria: "Jugos Listos" , Id_categoria: 24},
    {id_sub: 141 , subcategoria: "Jugos Refrigerados" , Id_categoria: 24},
    {id_sub: 142 , subcategoria: "Energizantes" , Id_categoria: 25},
    {id_sub: 143 , subcategoria: "Isotónicas" , Id_categoria: 25},
]

export const productos =[
    {id_producto: 1 , nombre_producto: "arroz" , contenido_neto: 1 ,cod_u_medida: "kg" , id_sub: 42},
    {id_producto: 2 , nombre_producto: "papa" , contenido_neto: 1 ,cod_u_medida: "kg" , id_sub: 90},
    {id_producto: 3 , nombre_producto: "leche_normal" , contenido_neto: 1 ,cod_u_medida: "lt" , id_sub: 63},
    {id_producto: 4 , nombre_producto: "huevos" , contenido_neto: 30 ,cod_u_medida: "un" , id_sub: 84},
    {id_producto: 5 , nombre_producto: "harina_trigo" , contenido_neto: 1 ,cod_u_medida: "kg" , id_sub: 62},
    {id_producto: 6 , nombre_producto: "café" , contenido_neto: 1 ,cod_u_medida: "kg" , id_sub: 25},
    {id_producto: 7 , nombre_producto: "pan_tajado" , contenido_neto: 400 ,cod_u_medida: "gm" , id_sub: 35},
    {id_producto: 9 , nombre_producto: "azucar" , contenido_neto: 1 ,cod_u_medida: "kg" , id_sub: 21},
    {id_producto: 10 , nombre_producto: "sal" , contenido_neto: 1 ,cod_u_medida: "kg" , id_sub: 10},
]


export const desafios =[
    
]
