const ciudades =[
    {Ciudad: "Buenos Aires", paiseCodigoAlfa: "ARG"},
{Ciudad: "Córdoba", paiseCodigoAlfa: "ARG"},
{Ciudad: "Rosario", paiseCodigoAlfa: "ARG"},
{Ciudad: "Mar del Plata", paiseCodigoAlfa: "ARG"},
{Ciudad: "San Miguel de Tucumán", paiseCodigoAlfa: "ARG"},
{Ciudad: "Salta", paiseCodigoAlfa: "ARG"},
{Ciudad: "Santa Fe", paiseCodigoAlfa: "ARG"},
{Ciudad: "Corrientes", paiseCodigoAlfa: "ARG"},
{Ciudad: "Bahía Blanca", paiseCodigoAlfa: "ARG"},
{Ciudad: "Resistencia", paiseCodigoAlfa: "ARG"},
{Ciudad: "Posadas", paiseCodigoAlfa: "ARG"},
{Ciudad: "Merlo", paiseCodigoAlfa: "ARG"},
{Ciudad: "Quilmes", paiseCodigoAlfa: "ARG"},
{Ciudad: "San Salvador de Jujuy", paiseCodigoAlfa: "ARG"},
{Ciudad: "Guaymallén", paiseCodigoAlfa: "ARG"},
{Ciudad: "Santiago del Estero", paiseCodigoAlfa: "ARG"},
{Ciudad: "Gregorio de Laferrere", paiseCodigoAlfa: "ARG"},
{Ciudad: "José C. Paz", paiseCodigoAlfa: "ARG"},
{Ciudad: "Paraná", paiseCodigoAlfa: "ARG"},
{Ciudad: "Banfield nota 2​", paiseCodigoAlfa: "ARG"},
{Ciudad: "González Catán", paiseCodigoAlfa: "ARG"},
{Ciudad: "Neuquén", paiseCodigoAlfa: "ARG"},
{Ciudad: "Formosa", paiseCodigoAlfa: "ARG"},
{Ciudad: "Lanús", paiseCodigoAlfa: "ARG"},
{Ciudad: "La Plata", paiseCodigoAlfa: "ARG"},
{Ciudad: "Godoy Cruz", paiseCodigoAlfa: "ARG"},
{Ciudad: "Isidro Casanova", paiseCodigoAlfa: "ARG"},
{Ciudad: "Las Heras", paiseCodigoAlfa: "ARG"},
{Ciudad: "Berazategui", paiseCodigoAlfa: "ARG"},
{Ciudad: "La Rioja", paiseCodigoAlfa: "ARG"},
{Ciudad: "Comodoro Rivadavia", paiseCodigoAlfa: "ARG"},
{Ciudad: "Moreno", paiseCodigoAlfa: "ARG"},
{Ciudad: "San Luis", paiseCodigoAlfa: "ARG"},
{Ciudad: "San Miguel nota 3​", paiseCodigoAlfa: "ARG"},
{Ciudad: "San Fernando del Valle de Catamarca", paiseCodigoAlfa: "ARG"},
{Ciudad: "Río Cuarto", paiseCodigoAlfa: "ARG"},
{Ciudad: "Virrey del Pino", paiseCodigoAlfa: "ARG"},
{Ciudad: "Santa Cruz de la Sierra", paiseCodigoAlfa: "BOL"},
{Ciudad: "El Alto", paiseCodigoAlfa: "BOL"},
{Ciudad: "La Paz", paiseCodigoAlfa: "BOL"},
{Ciudad: "Cochabamba", paiseCodigoAlfa: "BOL"},
{Ciudad: "Oruro", paiseCodigoAlfa: "BOL"},
{Ciudad: "Sucre", paiseCodigoAlfa: "BOL"},
{Ciudad: "Tarija", paiseCodigoAlfa: "BOL"},
{Ciudad: "Potosí", paiseCodigoAlfa: "BOL"},
{Ciudad: "Warnes", paiseCodigoAlfa: "BOL"},
{Ciudad: "Sacaba", paiseCodigoAlfa: "BOL"},
{Ciudad: "La Guardia", paiseCodigoAlfa: "BOL"},
{Ciudad: "Quillacollo", paiseCodigoAlfa: "BOL"},
{Ciudad: "Montero", paiseCodigoAlfa: "BOL"},
{Ciudad: "Trinidad", paiseCodigoAlfa: "BOL"},
{Ciudad: "Yacuiba", paiseCodigoAlfa: "BOL"},
{Ciudad: "Sao Paulo", paiseCodigoAlfa: "BRA"},
{Ciudad: "Rio de Janeiro", paiseCodigoAlfa: "BRA"},
{Ciudad: "Salvador", paiseCodigoAlfa: "BRA"},
{Ciudad: "Brasilia", paiseCodigoAlfa: "BRA"},
{Ciudad: "Fortaleza", paiseCodigoAlfa: "BRA"},
{Ciudad: "Belo Horizonte", paiseCodigoAlfa: "BRA"},
{Ciudad: "Manaus", paiseCodigoAlfa: "BRA"},
{Ciudad: "Curitiba", paiseCodigoAlfa: "BRA"},
{Ciudad: "Recife", paiseCodigoAlfa: "BRA"},
{Ciudad: "Porto Alegre", paiseCodigoAlfa: "BRA"},
{Ciudad: "Belém", paiseCodigoAlfa: "BRA"},
{Ciudad: "Goiania", paiseCodigoAlfa: "BRA"},
{Ciudad: "Sao Luís", paiseCodigoAlfa: "BRA"},
{Ciudad: "Maceió", paiseCodigoAlfa: "BRA"},
{Ciudad: "Teresina", paiseCodigoAlfa: "BRA"},
{Ciudad: "Natal", paiseCodigoAlfa: "BRA"},
{Ciudad: "Campo Grande", paiseCodigoAlfa: "BRA"},
{Ciudad: "Joao Pessoa", paiseCodigoAlfa: "BRA"},
{Ciudad: "Aracaju", paiseCodigoAlfa: "BRA"},
{Ciudad: "Cuiabá", paiseCodigoAlfa: "BRA"},
{Ciudad: "Porto Velho", paiseCodigoAlfa: "BRA"},
{Ciudad: "Florianópolis", paiseCodigoAlfa: "BRA"},
{Ciudad: "Macapá", paiseCodigoAlfa: "BRA"},
{Ciudad: "Rio Branco", paiseCodigoAlfa: "BRA"},
{Ciudad: "Vitória", paiseCodigoAlfa: "BRA"},
{Ciudad: "Boa Vista", paiseCodigoAlfa: "BRA"},
{Ciudad: "Palmas", paiseCodigoAlfa: "BRA"},
{Ciudad: "Gran Santiago (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran Concepción (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran Valparaíso (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran La Serena (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran Temuco (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Antofagasta (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran Iquique (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran Puerto Montt (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran Talca (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Arica (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran Rancagua (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran Chillan (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Los Ángeles", paiseCodigoAlfa: "CHL"},
{Ciudad: "Calama", paiseCodigoAlfa: "CHL"},
{Ciudad: "Colina", paiseCodigoAlfa: "CHL"},
{Ciudad: "Valdivia (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran Quillota", paiseCodigoAlfa: "CHL"},
{Ciudad: "Osorno", paiseCodigoAlfa: "CHL"},
{Ciudad: "Copiapó (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Curicó", paiseCodigoAlfa: "CHL"},
{Ciudad: "Punta Arenas (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Melipilla", paiseCodigoAlfa: "CHL"},
{Ciudad: "Gran San Antonio", paiseCodigoAlfa: "CHL"},
{Ciudad: "Lampa", paiseCodigoAlfa: "CHL"},
{Ciudad: "Ovalle", paiseCodigoAlfa: "CHL"},
{Ciudad: "Buin", paiseCodigoAlfa: "CHL"},
{Ciudad: "Los Andes-Calle Larga-San Esteban", paiseCodigoAlfa: "CHL"},
{Ciudad: "Linares", paiseCodigoAlfa: "CHL"},
{Ciudad: "Peñaflor", paiseCodigoAlfa: "CHL"},
{Ciudad: "San Felipe", paiseCodigoAlfa: "CHL"},
{Ciudad: "Paine", paiseCodigoAlfa: "CHL"},
{Ciudad: "Talagante", paiseCodigoAlfa: "CHL"},
{Ciudad: "San Fernando", paiseCodigoAlfa: "CHL"},
{Ciudad: "Limache-Olmué", paiseCodigoAlfa: "CHL"},
{Ciudad: "Rengo", paiseCodigoAlfa: "CHL"},
{Ciudad: "Coyhaique (C)", paiseCodigoAlfa: "CHL"},
{Ciudad: "Villarrica", paiseCodigoAlfa: "CHL"},
{Ciudad: "Vallenar", paiseCodigoAlfa: "CHL"},
{Ciudad: "San Carlos", paiseCodigoAlfa: "CHL"},
{Ciudad: "Angol", paiseCodigoAlfa: "CHL"},
{Ciudad: "San Vicente de Tagua Tagua", paiseCodigoAlfa: "CHL"},
{Ciudad: "Cauquenes", paiseCodigoAlfa: "CHL"},
{Ciudad: "Bogotá", paiseCodigoAlfa: "COL"},
{Ciudad: "Medellín", paiseCodigoAlfa: "COL"},
{Ciudad: "Cali", paiseCodigoAlfa: "COL"},
{Ciudad: "Barranquilla", paiseCodigoAlfa: "COL"},
{Ciudad: "Cartagena", paiseCodigoAlfa: "COL"},
{Ciudad: "Cúcuta", paiseCodigoAlfa: "COL"},
{Ciudad: "Soacha", paiseCodigoAlfa: "COL"},
{Ciudad: "Soledad", paiseCodigoAlfa: "COL"},
{Ciudad: "Bucaramanga", paiseCodigoAlfa: "COL"},
{Ciudad: "Bello", paiseCodigoAlfa: "COL"},
{Ciudad: "Villavicencio", paiseCodigoAlfa: "COL"},
{Ciudad: "Ibagué", paiseCodigoAlfa: "COL"},
{Ciudad: "Santa Marta", paiseCodigoAlfa: "COL"},
{Ciudad: "Valledupar", paiseCodigoAlfa: "COL"},
{Ciudad: "Montería", paiseCodigoAlfa: "COL"},
{Ciudad: "Pereira", paiseCodigoAlfa: "COL"},
{Ciudad: "Manizales", paiseCodigoAlfa: "COL"},
{Ciudad: "Pasto", paiseCodigoAlfa: "COL"},
{Ciudad: "Neiva", paiseCodigoAlfa: "COL"},
{Ciudad: "Palmira", paiseCodigoAlfa: "COL"},
{Ciudad: "Popayán", paiseCodigoAlfa: "COL"},
{Ciudad: "Buenaventura", paiseCodigoAlfa: "COL"},
{Ciudad: "Floridablanca", paiseCodigoAlfa: "COL"},
{Ciudad: "Armenia", paiseCodigoAlfa: "COL"},
{Ciudad: "Sincelejo", paiseCodigoAlfa: "COL"},
{Ciudad: "Itagüí", paiseCodigoAlfa: "COL"},
{Ciudad: "Tumaco", paiseCodigoAlfa: "COL"},
{Ciudad: "Envigado", paiseCodigoAlfa: "COL"},
{Ciudad: "Dosquebradas", paiseCodigoAlfa: "COL"},
{Ciudad: "Tuluá", paiseCodigoAlfa: "COL"},
{Ciudad: "Barrancabermeja", paiseCodigoAlfa: "COL"},
{Ciudad: "Riohacha", paiseCodigoAlfa: "COL"},
{Ciudad: "Uribia", paiseCodigoAlfa: "COL"},
{Ciudad: "Maicao", paiseCodigoAlfa: "COL"},
{Ciudad: "Piedecuesta", paiseCodigoAlfa: "COL"},
{Ciudad: "Tunja", paiseCodigoAlfa: "COL"},
{Ciudad: "Yopal", paiseCodigoAlfa: "COL"},
{Ciudad: "Florencia", paiseCodigoAlfa: "COL"},
{Ciudad: "Girón", paiseCodigoAlfa: "COL"},
{Ciudad: "Jamundí", paiseCodigoAlfa: "COL"},
{Ciudad: "Facatativá", paiseCodigoAlfa: "COL"},
{Ciudad: "Fusagasugá", paiseCodigoAlfa: "COL"},
{Ciudad: "Mosquera", paiseCodigoAlfa: "COL"},
{Ciudad: "Chía", paiseCodigoAlfa: "COL"},
{Ciudad: "Zipaquirá", paiseCodigoAlfa: "COL"},
{Ciudad: "Rionegro", paiseCodigoAlfa: "COL"},
{Ciudad: "Magangué", paiseCodigoAlfa: "COL"},
{Ciudad: "Malambo", paiseCodigoAlfa: "COL"},
{Ciudad: "Cartago", paiseCodigoAlfa: "COL"},
{Ciudad: "Sogamoso", paiseCodigoAlfa: "COL"},
{Ciudad: "Quibdó", paiseCodigoAlfa: "COL"},
{Ciudad: "Turbo", paiseCodigoAlfa: "COL"},
{Ciudad: "Ocaña", paiseCodigoAlfa: "COL"},
{Ciudad: "Buga", paiseCodigoAlfa: "COL"},
{Ciudad: "Pitalito", paiseCodigoAlfa: "COL"},
{Ciudad: "Apartadó", paiseCodigoAlfa: "COL"},
{Ciudad: "Madrid", paiseCodigoAlfa: "COL"},
{Ciudad: "Duitama", paiseCodigoAlfa: "COL"},
{Ciudad: "Ciénaga", paiseCodigoAlfa: "COL"},
{Ciudad: "Aguachica", paiseCodigoAlfa: "COL"},
{Ciudad: "Ipiales", paiseCodigoAlfa: "COL"},
{Ciudad: "Lorica", paiseCodigoAlfa: "COL"},
{Ciudad: "Turbaco", paiseCodigoAlfa: "COL"},
{Ciudad: "Santander de Quilichao", paiseCodigoAlfa: "COL"},
{Ciudad: "Villa del Rosario", paiseCodigoAlfa: "COL"},
{Ciudad: "Sahagún", paiseCodigoAlfa: "COL"},
{Ciudad: "Yumbo", paiseCodigoAlfa: "COL"},
{Ciudad: "Girardot", paiseCodigoAlfa: "COL"},
{Ciudad: "Cereté", paiseCodigoAlfa: "COL"},
{Ciudad: "Funza", paiseCodigoAlfa: "COL"},
{Ciudad: "Sabanalarga", paiseCodigoAlfa: "COL"},
{Ciudad: "Los Patios", paiseCodigoAlfa: "COL"},
{Ciudad: "Arauca", paiseCodigoAlfa: "COL"},
{Ciudad: "Caucasia", paiseCodigoAlfa: "COL"},
{Ciudad: "Tierralta", paiseCodigoAlfa: "COL"},
{Ciudad: "Candelaria", paiseCodigoAlfa: "COL"},
{Ciudad: "Manaure", paiseCodigoAlfa: "COL"},
{Ciudad: "Cajicá", paiseCodigoAlfa: "COL"},
{Ciudad: "Acacías", paiseCodigoAlfa: "COL"},
{Ciudad: "Sabaneta", paiseCodigoAlfa: "COL"},
{Ciudad: "Montelíbano", paiseCodigoAlfa: "COL"},
{Ciudad: "Caldas", paiseCodigoAlfa: "COL"},
{Ciudad: "Copacabana", paiseCodigoAlfa: "COL"},
{Ciudad: "Santa Rosa de Cabal", paiseCodigoAlfa: "COL"},
{Ciudad: "Cumaribo", paiseCodigoAlfa: "COL"},
{Ciudad: "La Estrella", paiseCodigoAlfa: "COL"},
{Ciudad: "Calarcá", paiseCodigoAlfa: "COL"},
{Ciudad: "Garzón", paiseCodigoAlfa: "COL"},
{Ciudad: "La Dorada", paiseCodigoAlfa: "COL"},
{Ciudad: "Zona Bananera", paiseCodigoAlfa: "COL"},
{Ciudad: "Arjona", paiseCodigoAlfa: "COL"},
{Ciudad: "El Carmen de Bolívar", paiseCodigoAlfa: "COL"},
{Ciudad: "Espinal", paiseCodigoAlfa: "COL"},
{Ciudad: "Corozal", paiseCodigoAlfa: "COL"},
{Ciudad: "Granada", paiseCodigoAlfa: "COL"},
{Ciudad: "Fundación", paiseCodigoAlfa: "COL"},
{Ciudad: "El Banco", paiseCodigoAlfa: "COL"},
{Ciudad: "La Ceja", paiseCodigoAlfa: "COL"},
{Ciudad: "Marinilla", paiseCodigoAlfa: "COL"},
{Ciudad: "Villamaría", paiseCodigoAlfa: "COL"},
{Ciudad: "Puerto Asís", paiseCodigoAlfa: "COL"},
{Ciudad: "Baranoa", paiseCodigoAlfa: "COL"},
{Ciudad: "Galapa", paiseCodigoAlfa: "COL"},
{Ciudad: "Planeta Rica", paiseCodigoAlfa: "COL"},
{Ciudad: "Agustín Codazzi", paiseCodigoAlfa: "COL"},
{Ciudad: "Plato", paiseCodigoAlfa: "COL"},
{Ciudad: "Saravena", paiseCodigoAlfa: "COL"},
{Ciudad: "El Carmen de Viboral", paiseCodigoAlfa: "COL"},
{Ciudad: "La Plata", paiseCodigoAlfa: "COL"},
{Ciudad: "San Marcos", paiseCodigoAlfa: "COL"},
{Ciudad: "Ciénaga de Oro", paiseCodigoAlfa: "COL"},
{Ciudad: "Chigorodó", paiseCodigoAlfa: "COL"},
{Ciudad: "San Gil", paiseCodigoAlfa: "COL"},
{Ciudad: "Mocoa", paiseCodigoAlfa: "COL"},
{Ciudad: "Tibú", paiseCodigoAlfa: "COL"},
{Ciudad: "Guarne", paiseCodigoAlfa: "COL"},
{Ciudad: "Florida", paiseCodigoAlfa: "COL"},
{Ciudad: "Chiquinquirá", paiseCodigoAlfa: "COL"},
{Ciudad: "San Andrés", paiseCodigoAlfa: "COL"},
{Ciudad: "El Cerrito", paiseCodigoAlfa: "COL"},
{Ciudad: "Barbacoas", paiseCodigoAlfa: "COL"},
{Ciudad: "Arauquita", paiseCodigoAlfa: "COL"},
{Ciudad: "San José del Guaviare", paiseCodigoAlfa: "COL"},
{Ciudad: "Riosucio", paiseCodigoAlfa: "COL"},
{Ciudad: "Tuchín", paiseCodigoAlfa: "COL"},
{Ciudad: "Girardota", paiseCodigoAlfa: "COL"},
{Ciudad: "Barbosa", paiseCodigoAlfa: "COL"},
{Ciudad: "Pamplona", paiseCodigoAlfa: "COL"},
{Ciudad: "El Bagre", paiseCodigoAlfa: "COL"},
{Ciudad: "El Tambo", paiseCodigoAlfa: "COL"},
{Ciudad: "Puerto Colombia", paiseCodigoAlfa: "COL"},
{Ciudad: "San Pelayo", paiseCodigoAlfa: "COL"},
{Ciudad: "San Vicente del Caguán", paiseCodigoAlfa: "COL"},
{Ciudad: "Chinchiná", paiseCodigoAlfa: "COL"},
{Ciudad: "Carepa", paiseCodigoAlfa: "COL"},
{Ciudad: "San Onofre", paiseCodigoAlfa: "COL"},
{Ciudad: "La Jagua de Ibirico", paiseCodigoAlfa: "COL"},
{Ciudad: "Chaparral", paiseCodigoAlfa: "COL"},
{Ciudad: "San José", paiseCodigoAlfa: "CRC"},
{Ciudad: "Alajuela", paiseCodigoAlfa: "CRC"},
{Ciudad: "Cartago", paiseCodigoAlfa: "CRC"},
{Ciudad: "Heredia", paiseCodigoAlfa: "CRC"},
{Ciudad: "Liberia", paiseCodigoAlfa: "CRC"},
{Ciudad: "Puntarenas", paiseCodigoAlfa: "CRC"},
{Ciudad: "Limón", paiseCodigoAlfa: "CRC"},
{Ciudad: "La Habana", paiseCodigoAlfa: "CUB"},
{Ciudad: "Santiago de Cuba", paiseCodigoAlfa: "CUB"},
{Ciudad: "Camagüey", paiseCodigoAlfa: "CUB"},
{Ciudad: "Holguín", paiseCodigoAlfa: "CUB"},
{Ciudad: "Guantánamo", paiseCodigoAlfa: "CUB"},
{Ciudad: "Santa Clara", paiseCodigoAlfa: "CUB"},
{Ciudad: "Las Tunas", paiseCodigoAlfa: "CUB"},
{Ciudad: "Bayamo", paiseCodigoAlfa: "CUB"},
{Ciudad: "Cienfuegos", paiseCodigoAlfa: "CUB"},
{Ciudad: "Pinar del Río", paiseCodigoAlfa: "CUB"},
{Ciudad: "Matanzas", paiseCodigoAlfa: "CUB"},
{Ciudad: "Ciego de Ávila", paiseCodigoAlfa: "CUB"},
{Ciudad: "Sancti Spíritus", paiseCodigoAlfa: "CUB"},
{Ciudad: "Manzanillo", paiseCodigoAlfa: "CUB"},
{Ciudad: "Cárdenas", paiseCodigoAlfa: "CUB"},
{Ciudad: "Palma Soriano", paiseCodigoAlfa: "CUB"},
{Ciudad: "Moa", paiseCodigoAlfa: "CUB"},
{Ciudad: "Morón", paiseCodigoAlfa: "CUB"},
{Ciudad: "Florida", paiseCodigoAlfa: "CUB"},
{Ciudad: "Contramaestre", paiseCodigoAlfa: "CUB"},
{Ciudad: "Artemisa", paiseCodigoAlfa: "CUB"},
{Ciudad: "Nueva Gerona", paiseCodigoAlfa: "CUB"},
{Ciudad: "Trinidad", paiseCodigoAlfa: "CUB"},
{Ciudad: "Colón", paiseCodigoAlfa: "CUB"},
{Ciudad: "Baracoa", paiseCodigoAlfa: "CUB"},
{Ciudad: "Güines", paiseCodigoAlfa: "CUB"},
{Ciudad: "Placetas", paiseCodigoAlfa: "CUB"},
{Ciudad: "Nuevitas", paiseCodigoAlfa: "CUB"},
{Ciudad: "Sagua la Grande", paiseCodigoAlfa: "CUB"},
{Ciudad: "San José de las Lajas", paiseCodigoAlfa: "CUB"},
{Ciudad: "Banes", paiseCodigoAlfa: "CUB"},
{Ciudad: "San Luis", paiseCodigoAlfa: "CUB"},
{Ciudad: "Puerto Padre", paiseCodigoAlfa: "CUB"},
{Ciudad: "San Antonio de los Baños", paiseCodigoAlfa: "CUB"},
{Ciudad: "Caibarién", paiseCodigoAlfa: "CUB"},
{Ciudad: "Cabaiguán", paiseCodigoAlfa: "CUB"},
{Ciudad: "Mayarí", paiseCodigoAlfa: "CUB"},
{Ciudad: "San Cristóbal", paiseCodigoAlfa: "CUB"},
{Ciudad: "Vertientes", paiseCodigoAlfa: "CUB"},
{Ciudad: "Jagüey Grande", paiseCodigoAlfa: "CUB"},
{Ciudad: "Consolación del Sur", paiseCodigoAlfa: "CUB"},
{Ciudad: "Jovellanos", paiseCodigoAlfa: "CUB"},
{Ciudad: "Amancio", paiseCodigoAlfa: "CUB"},
{Ciudad: "Güira de Melena", paiseCodigoAlfa: "CUB"},
{Ciudad: "Cumanayagua", paiseCodigoAlfa: "CUB"},
{Ciudad: "Jatibonico", paiseCodigoAlfa: "CUB"},
{Ciudad: "Niquero", paiseCodigoAlfa: "CUB"},
{Ciudad: "San Germán", paiseCodigoAlfa: "CUB"},
{Ciudad: "Sagua de Tánamo", paiseCodigoAlfa: "CUB"},
{Ciudad: "Bauta", paiseCodigoAlfa: "CUB"},
{Ciudad: "La Maya", paiseCodigoAlfa: "CUB"},
{Ciudad: "Guanajay", paiseCodigoAlfa: "CUB"},
{Ciudad: "Colombia", paiseCodigoAlfa: "CUB"},
{Ciudad: "Jiguaní", paiseCodigoAlfa: "CUB"},
{Ciudad: "Manicaragua", paiseCodigoAlfa: "CUB"},
{Ciudad: "Camajuaní", paiseCodigoAlfa: "CUB"},
{Ciudad: "Guisa", paiseCodigoAlfa: "CUB"},
{Ciudad: "Jobabo", paiseCodigoAlfa: "CUB"},
{Ciudad: "Guayas", paiseCodigoAlfa: "ECU"},
{Ciudad: "Pichincha", paiseCodigoAlfa: "ECU"},
{Ciudad: "Azuay", paiseCodigoAlfa: "ECU"},
{Ciudad: "Santo Domingo de los Tsáchilas", paiseCodigoAlfa: "ECU"},
{Ciudad: "El Oro", paiseCodigoAlfa: "ECU"},
{Ciudad: "Manabí", paiseCodigoAlfa: "ECU"},
{Ciudad: "Loja", paiseCodigoAlfa: "ECU"},
{Ciudad: "Tungurahua", paiseCodigoAlfa: "ECU"},
{Ciudad: "Esmeraldas", paiseCodigoAlfa: "ECU"},
{Ciudad: "Los Ríos", paiseCodigoAlfa: "ECU"},
{Ciudad: "Chimborazo", paiseCodigoAlfa: "ECU"},
{Ciudad: "Imbabura", paiseCodigoAlfa: "ECU"},
{Ciudad: "Santa Elena flag.pngSanta Elena", paiseCodigoAlfa: "ECU"},
{Ciudad: "Cotopaxi", paiseCodigoAlfa: "ECU"},
{Ciudad: "Carchi", paiseCodigoAlfa: "ECU"},
{Ciudad: "Sucumbíos", paiseCodigoAlfa: "ECU"},
{Ciudad: "Orellana", paiseCodigoAlfa: "ECU"},
{Ciudad: "Cañar", paiseCodigoAlfa: "ECU"},
{Ciudad: "Pastaza", paiseCodigoAlfa: "ECU"},
{Ciudad: "Bolívar", paiseCodigoAlfa: "ECU"},
{Ciudad: "Napo", paiseCodigoAlfa: "ECU"},
{Ciudad: "Morona Santiago", paiseCodigoAlfa: "ECU"},
{Ciudad: "Zamora Chinchipe", paiseCodigoAlfa: "ECU"},
{Ciudad: "Galápagos", paiseCodigoAlfa: "ECU"},
{Ciudad: "Ciudad de Guatemala", paiseCodigoAlfa: "GTM"},
{Ciudad: "Santa Catarina Pinula", paiseCodigoAlfa: "GTM"},
{Ciudad: "San Miguel Petapa", paiseCodigoAlfa: "GTM"},
{Ciudad: "Mixco", paiseCodigoAlfa: "GTM"},
{Ciudad: "Villa Nueva", paiseCodigoAlfa: "GTM"},
{Ciudad: "Fraijanes", paiseCodigoAlfa: "GTM"},
{Ciudad: "Antigua Guatemala", paiseCodigoAlfa: "GTM"},
{Ciudad: "San Lucas Sacatepéquez", paiseCodigoAlfa: "GTM"},
{Ciudad: "Villa Canales", paiseCodigoAlfa: "GTM"},
{Ciudad: "San José Pinula", paiseCodigoAlfa: "GTM"},
{Ciudad: "Amatitlán", paiseCodigoAlfa: "GTM"},
{Ciudad: "Jocotenango", paiseCodigoAlfa: "GTM"},
{Ciudad: "San Pedro Sacatepéquez", paiseCodigoAlfa: "GTM"},
{Ciudad: "San José del Golfo", paiseCodigoAlfa: "GTM"},
{Ciudad: "Chinautla", paiseCodigoAlfa: "GTM"},
{Ciudad: "San Bartolomé Milpas Altas", paiseCodigoAlfa: "GTM"},
{Ciudad: "Quetzaltenango", paiseCodigoAlfa: "GTM"},
{Ciudad: "Salcajá", paiseCodigoAlfa: "GTM"},
{Ciudad: "San Raymundo", paiseCodigoAlfa: "GTM"},
{Ciudad: "Santa Lucía Milpas Altas", paiseCodigoAlfa: "GTM"},
{Ciudad: "Gonaïves", paiseCodigoAlfa: "HTI"},
{Ciudad: "Hinche", paiseCodigoAlfa: "HTI"},
{Ciudad: "Jérémie", paiseCodigoAlfa: "HTI"},
{Ciudad: "Miragoâne", paiseCodigoAlfa: "HTI"},
{Ciudad: "Cabo Haitiano", paiseCodigoAlfa: "HTI"},
{Ciudad: "Fuerte Libertad", paiseCodigoAlfa: "HTI"},
{Ciudad: "Port-de-Paix", paiseCodigoAlfa: "HTI"},
{Ciudad: "Puerto Príncipe", paiseCodigoAlfa: "HTI"},
{Ciudad: "Les Cayes", paiseCodigoAlfa: "HTI"},
{Ciudad: "Jacmel", paiseCodigoAlfa: "HTI"},
{Ciudad: "Distrito Central", paiseCodigoAlfa: "HND"},
{Ciudad: "San Pedro Sula", paiseCodigoAlfa: "HND"},
{Ciudad: "Choloma", paiseCodigoAlfa: "HND"},
{Ciudad: "Danlí", paiseCodigoAlfa: "HND"},
{Ciudad: "La Ceiba", paiseCodigoAlfa: "HND"},
{Ciudad: "El Progreso", paiseCodigoAlfa: "HND"},
{Ciudad: "Villanueva", paiseCodigoAlfa: "HND"},
{Ciudad: "Comayagua", paiseCodigoAlfa: "HND"},
{Ciudad: "Choluteca", paiseCodigoAlfa: "HND"},
{Ciudad: "Juticalpa", paiseCodigoAlfa: "HND"},
{Ciudad: "Puerto Cortés", paiseCodigoAlfa: "HND"},
{Ciudad: "Catacamas", paiseCodigoAlfa: "HND"},
{Ciudad: "Olanchito", paiseCodigoAlfa: "HND"},
{Ciudad: "Tela", paiseCodigoAlfa: "HND"},
{Ciudad: "Tocoa", paiseCodigoAlfa: "HND"},
{Ciudad: "Ciudad de México", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tijuana", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Cristóbal Ecatepec", paiseCodigoAlfa: "MEX"},
{Ciudad: "León", paiseCodigoAlfa: "MEX"},
{Ciudad: "Puebla de Zaragoza", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ciudad Juárez", paiseCodigoAlfa: "MEX"},
{Ciudad: "Guadalajara", paiseCodigoAlfa: "MEX"},
{Ciudad: "Zapopan", paiseCodigoAlfa: "MEX"},
{Ciudad: "Monterrey", paiseCodigoAlfa: "MEX"},
{Ciudad: "Nezahualcóyotl", paiseCodigoAlfa: "MEX"},
{Ciudad: "Chihuahua", paiseCodigoAlfa: "MEX"},
{Ciudad: "Mérida", paiseCodigoAlfa: "MEX"},
{Ciudad: "Cancún", paiseCodigoAlfa: "MEX"},
{Ciudad: "Saltillo", paiseCodigoAlfa: "MEX"},
{Ciudad: "Aguascalientes", paiseCodigoAlfa: "MEX"},
{Ciudad: "Hermosillo", paiseCodigoAlfa: "MEX"},
{Ciudad: "Mexicali", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Luis Potosí", paiseCodigoAlfa: "MEX"},
{Ciudad: "Culiacán Rosales", paiseCodigoAlfa: "MEX"},
{Ciudad: "Santiago de Querétaro", paiseCodigoAlfa: "MEX"},
{Ciudad: "Naucalpan de Juárez", paiseCodigoAlfa: "MEX"},
{Ciudad: "Morelia", paiseCodigoAlfa: "MEX"},
{Ciudad: "Chimalhuacán", paiseCodigoAlfa: "MEX"},
{Ciudad: "Reynosa", paiseCodigoAlfa: "MEX"},
{Ciudad: "Torreón", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tlalnepantla de Baz", paiseCodigoAlfa: "MEX"},
{Ciudad: "Acapulco de Juárez", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tlaquepaque", paiseCodigoAlfa: "MEX"},
{Ciudad: "Guadalupe", paiseCodigoAlfa: "MEX"},
{Ciudad: "Victoria de Durango", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tuxtla Gutiérrez", paiseCodigoAlfa: "MEX"},
{Ciudad: "Apodaca", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ciudad López Mateos", paiseCodigoAlfa: "MEX"},
{Ciudad: "Cuautitlán Izcalli", paiseCodigoAlfa: "MEX"},
{Ciudad: "Heroica Matamoros", paiseCodigoAlfa: "MEX"},
{Ciudad: "General Escobedo", paiseCodigoAlfa: "MEX"},
{Ciudad: "Irapuato", paiseCodigoAlfa: "MEX"},
{Ciudad: "Xalapa", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tonalá", paiseCodigoAlfa: "MEX"},
{Ciudad: "Mazatlán", paiseCodigoAlfa: "MEX"},
{Ciudad: "Nuevo Laredo", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Nicolás de los Garza", paiseCodigoAlfa: "MEX"},
{Ciudad: "Veracruz", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ojo de Agua", paiseCodigoAlfa: "MEX"},
{Ciudad: "Xico", paiseCodigoAlfa: "MEX"},
{Ciudad: "Celaya", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tepic", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ixtapaluca", paiseCodigoAlfa: "MEX"},
{Ciudad: "Cuernavaca", paiseCodigoAlfa: "MEX"},
{Ciudad: "Villahermosa", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ciudad Victoria", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ensenada", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ciudad Obregón", paiseCodigoAlfa: "MEX"},
{Ciudad: "Villa Nicolás Romero", paiseCodigoAlfa: "MEX"},
{Ciudad: "Soledad de Graciano Sánchez", paiseCodigoAlfa: "MEX"},
{Ciudad: "Juárez", paiseCodigoAlfa: "MEX"},
{Ciudad: "Playa del Carmen", paiseCodigoAlfa: "MEX"},
{Ciudad: "Santa Catarina", paiseCodigoAlfa: "MEX"},
{Ciudad: "Gómez Palacio", paiseCodigoAlfa: "MEX"},
{Ciudad: "Uruapan", paiseCodigoAlfa: "MEX"},
{Ciudad: "Los Mochis", paiseCodigoAlfa: "MEX"},
{Ciudad: "Pachuca de Soto", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tampico", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tehuacán", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Francisco Coacalco", paiseCodigoAlfa: "MEX"},
{Ciudad: "Salamanca", paiseCodigoAlfa: "MEX"},
{Ciudad: "Heroica Nogales", paiseCodigoAlfa: "MEX"},
{Ciudad: "Oaxaca de Juárez", paiseCodigoAlfa: "MEX"},
{Ciudad: "La Paz", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Francisco de Campeche", paiseCodigoAlfa: "MEX"},
{Ciudad: "Monclova", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Pedro Garza García", paiseCodigoAlfa: "MEX"},
{Ciudad: "Chilpancingo de los Bravo", paiseCodigoAlfa: "MEX"},
{Ciudad: "Puerto Vallarta", paiseCodigoAlfa: "MEX"},
{Ciudad: "Toluca de Lerdo", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tapachula", paiseCodigoAlfa: "MEX"},
{Ciudad: "Buenavista", paiseCodigoAlfa: "MEX"},
{Ciudad: "Coatzacoalcos", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ciudad Madero", paiseCodigoAlfa: "MEX"},
{Ciudad: "Cabo San Lucas", paiseCodigoAlfa: "MEX"},
{Ciudad: "Guanajuato", paiseCodigoAlfa: "MEX"},
{Ciudad: "Chicoloapan", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ciudad del Carmen", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Cristóbal de las Casas", paiseCodigoAlfa: "MEX"},
{Ciudad: "Poza Rica de Hidalgo", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Juan del Río", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Luis Río Colorado", paiseCodigoAlfa: "MEX"},
{Ciudad: "Chalco de Díaz Covarrubias", paiseCodigoAlfa: "MEX"},
{Ciudad: "Jiutepec", paiseCodigoAlfa: "MEX"},
{Ciudad: "Piedras Negras", paiseCodigoAlfa: "MEX"},
{Ciudad: "Chetumal", paiseCodigoAlfa: "MEX"},
{Ciudad: "Miramar", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ciudad Acuña", paiseCodigoAlfa: "MEX"},
{Ciudad: "Manzanillo", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Pablo de las Salinas", paiseCodigoAlfa: "MEX"},
{Ciudad: "Cuautla de Morelos", paiseCodigoAlfa: "MEX"},
{Ciudad: "Zamora", paiseCodigoAlfa: "MEX"},
{Ciudad: "Villa de Álvarez", paiseCodigoAlfa: "MEX"},
{Ciudad: "Colima", paiseCodigoAlfa: "MEX"},
{Ciudad: "Fresnillo", paiseCodigoAlfa: "MEX"},
{Ciudad: "Kanasín", paiseCodigoAlfa: "MEX"},
{Ciudad: "Córdoba", paiseCodigoAlfa: "MEX"},
{Ciudad: "Zacatecas", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ciudad Valles", paiseCodigoAlfa: "MEX"},
{Ciudad: "San José del Cabo", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ciudad Cuauhtémoc", paiseCodigoAlfa: "MEX"},
{Ciudad: "Naucalpan", paiseCodigoAlfa: "MEX"},
{Ciudad: "Iguala", paiseCodigoAlfa: "MEX"},
{Ciudad: "Delicias", paiseCodigoAlfa: "MEX"},
{Ciudad: "Navojoa", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tepexpan", paiseCodigoAlfa: "MEX"},
{Ciudad: "Orizaba", paiseCodigoAlfa: "MEX"},
{Ciudad: "Cuautitlán", paiseCodigoAlfa: "MEX"},
{Ciudad: "Guaymas", paiseCodigoAlfa: "MEX"},
{Ciudad: "El Pueblito", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ramos Arizpe", paiseCodigoAlfa: "MEX"},
{Ciudad: "Hidalgo del Parral", paiseCodigoAlfa: "MEX"},
{Ciudad: "Comitán de Domínguez", paiseCodigoAlfa: "MEX"},
{Ciudad: "Ciudad Guzmán", paiseCodigoAlfa: "MEX"},
{Ciudad: "Lagos de Moreno", paiseCodigoAlfa: "MEX"},
{Ciudad: "Río Bravo", paiseCodigoAlfa: "MEX"},
{Ciudad: "Tulancingo de Bravo", paiseCodigoAlfa: "MEX"},
{Ciudad: "Temixco (ciudad)", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Juan Bautista Tuxtepec", paiseCodigoAlfa: "MEX"},
{Ciudad: "Apatzingán", paiseCodigoAlfa: "MEX"},
{Ciudad: "San Andrés Cholula", paiseCodigoAlfa: "MEX"},
{Ciudad: "Minatitlán", paiseCodigoAlfa: "MEX"},
{Ciudad: "Playas de Rosarito", paiseCodigoAlfa: "MEX"},
{Ciudad: "Boaco", paiseCodigoAlfa: "NIC"},
{Ciudad: "Jinotepe", paiseCodigoAlfa: "NIC"},
{Ciudad: "Chinandega", paiseCodigoAlfa: "NIC"},
{Ciudad: "Juigalpa", paiseCodigoAlfa: "NIC"},
{Ciudad: "Puerto Cabezas", paiseCodigoAlfa: "NIC"},
{Ciudad: "Bluefields", paiseCodigoAlfa: "NIC"},
{Ciudad: "Estelí", paiseCodigoAlfa: "NIC"},
{Ciudad: "Granada", paiseCodigoAlfa: "NIC"},
{Ciudad: "Jinotega", paiseCodigoAlfa: "NIC"},
{Ciudad: "León", paiseCodigoAlfa: "NIC"},
{Ciudad: "Somoto", paiseCodigoAlfa: "NIC"},
{Ciudad: "Managua", paiseCodigoAlfa: "NIC"},
{Ciudad: "Masaya", paiseCodigoAlfa: "NIC"},
{Ciudad: "Matagalpa", paiseCodigoAlfa: "NIC"},
{Ciudad: "Ocotal", paiseCodigoAlfa: "NIC"},
{Ciudad: "San Carlos", paiseCodigoAlfa: "NIC"},
{Ciudad: "Rivas", paiseCodigoAlfa: "NIC"},
{Ciudad: "Panamá", paiseCodigoAlfa: "PAN"},
{Ciudad: "Colón", paiseCodigoAlfa: "PAN"},
{Ciudad: "David", paiseCodigoAlfa: "PAN"},
{Ciudad: "La Chorrera", paiseCodigoAlfa: "PAN"},
{Ciudad: "Santiago", paiseCodigoAlfa: "PAN"},
{Ciudad: "Changuinola", paiseCodigoAlfa: "PAN"},
{Ciudad: "Penonomé", paiseCodigoAlfa: "PAN"},
{Ciudad: "Bugaba", paiseCodigoAlfa: "PAN"},
{Ciudad: "Puerto Armuelles", paiseCodigoAlfa: "PAN"},
{Ciudad: "Antón", paiseCodigoAlfa: "PAN"},
{Ciudad: "Chepo", paiseCodigoAlfa: "PAN"},
{Ciudad: "Chitré", paiseCodigoAlfa: "PAN"},
{Ciudad: "Aguadulce", paiseCodigoAlfa: "PAN"},
{Ciudad: "Capira", paiseCodigoAlfa: "PAN"},
{Ciudad: "Chame", paiseCodigoAlfa: "PAN"},
{Ciudad: "Soná", paiseCodigoAlfa: "PAN"},
{Ciudad: "Almirante", paiseCodigoAlfa: "PAN"},
{Ciudad: "La Pintada", paiseCodigoAlfa: "PAN"},
{Ciudad: "Las Tablas", paiseCodigoAlfa: "PAN"},
{Ciudad: "La Villa de Los Santos", paiseCodigoAlfa: "PAN"},
{Ciudad: "Asunción", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ciudad del Este", paiseCodigoAlfa: "PRY"},
{Ciudad: "Luque", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Lorenzo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Capiatá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Lambaré", paiseCodigoAlfa: "PRY"},
{Ciudad: "Fernando de la Mora", paiseCodigoAlfa: "PRY"},
{Ciudad: "Limpio", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ñemby", paiseCodigoAlfa: "PRY"},
{Ciudad: "Encarnación", paiseCodigoAlfa: "PRY"},
{Ciudad: "Caaguazú", paiseCodigoAlfa: "PRY"},
{Ciudad: "Coronel Oviedo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Pedro Juan Caballero", paiseCodigoAlfa: "PRY"},
{Ciudad: "Itauguá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Presidente Franco", paiseCodigoAlfa: "PRY"},
{Ciudad: "Mariano Roque Alonso", paiseCodigoAlfa: "PRY"},
{Ciudad: "Minga Guazú", paiseCodigoAlfa: "PRY"},
{Ciudad: "Concepción", paiseCodigoAlfa: "PRY"},
{Ciudad: "Itá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Villa Elisa", paiseCodigoAlfa: "PRY"},
{Ciudad: "Hernandarias", paiseCodigoAlfa: "PRY"},
{Ciudad: "Areguá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Villarrica", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Antonio", paiseCodigoAlfa: "PRY"},
{Ciudad: "Horqueta", paiseCodigoAlfa: "PRY"},
{Ciudad: "Cambyretá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Curuguaty", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ypané", paiseCodigoAlfa: "PRY"},
{Ciudad: "Caacupé", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Estanislao", paiseCodigoAlfa: "PRY"},
{Ciudad: "Julián Augusto Saldívar", paiseCodigoAlfa: "PRY"},
{Ciudad: "Villa Hayes", paiseCodigoAlfa: "PRY"},
{Ciudad: "Capiibary", paiseCodigoAlfa: "PRY"},
{Ciudad: "Santa Rosa del Aguaray", paiseCodigoAlfa: "PRY"},
{Ciudad: "Villeta", paiseCodigoAlfa: "PRY"},
{Ciudad: "Salto del Guairá", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Juan Nepomuceno", paiseCodigoAlfa: "PRY"},
{Ciudad: "Guarambaré", paiseCodigoAlfa: "PRY"},
{Ciudad: "Doctor Juan Eulogio Estigarribia", paiseCodigoAlfa: "PRY"},
{Ciudad: "Itakyry", paiseCodigoAlfa: "PRY"},
{Ciudad: "Carapeguá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Santa Rita", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Pedro de Ycuamandiyú", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Ignacio Guazú", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yhú", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yby Yaú", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Pedro del Paraná", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tobatí", paiseCodigoAlfa: "PRY"},
{Ciudad: "Repatriación", paiseCodigoAlfa: "PRY"},
{Ciudad: "Pilar", paiseCodigoAlfa: "PRY"},
{Ciudad: "Abaí", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yaguarón", paiseCodigoAlfa: "PRY"},
{Ciudad: "Guayaibí", paiseCodigoAlfa: "PRY"},
{Ciudad: "Piribebuy", paiseCodigoAlfa: "PRY"},
{Ciudad: "Mariscal José Félix Estigarribia", paiseCodigoAlfa: "PRY"},
{Ciudad: "Choré", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tomás Romero Pereira", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ypacaraí", paiseCodigoAlfa: "PRY"},
{Ciudad: "Teniente Primero Manuel Irala Fernández", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yasy Cañy", paiseCodigoAlfa: "PRY"},
{Ciudad: "Independencia", paiseCodigoAlfa: "PRY"},
{Ciudad: "Paso Yobái", paiseCodigoAlfa: "PRY"},
{Ciudad: "Juan Emiliano O'Leary", paiseCodigoAlfa: "PRY"},
{Ciudad: "Caazapá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Arroyos y Esteros", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ybycuí", paiseCodigoAlfa: "PRY"},
{Ciudad: "Liberación", paiseCodigoAlfa: "PRY"},
{Ciudad: "Doctor Juan Manuel Frutos", paiseCodigoAlfa: "PRY"},
{Ciudad: "General Isidoro Resquín", paiseCodigoAlfa: "PRY"},
{Ciudad: "Eusebio Ayala", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Juan Bautista", paiseCodigoAlfa: "PRY"},
{Ciudad: "Edelira", paiseCodigoAlfa: "PRY"},
{Ciudad: "Paraguarí", paiseCodigoAlfa: "PRY"},
{Ciudad: "General Elizardo Aquino", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yuty", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Rafael del Paraná", paiseCodigoAlfa: "PRY"},
{Ciudad: "Doctor Juan León Mallorquín", paiseCodigoAlfa: "PRY"},
{Ciudad: "Quiindy", paiseCodigoAlfa: "PRY"},
{Ciudad: "Coronel José Félix Bogado", paiseCodigoAlfa: "PRY"},
{Ciudad: "Benjamín Aceval", paiseCodigoAlfa: "PRY"},
{Ciudad: "Natalio", paiseCodigoAlfa: "PRY"},
{Ciudad: "Emboscada", paiseCodigoAlfa: "PRY"},
{Ciudad: "San José de los Arroyos", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tres de Mayo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Carlos Antonio López", paiseCodigoAlfa: "PRY"},
{Ciudad: "Filadelfia", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ayolas", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tavaí", paiseCodigoAlfa: "PRY"},
{Ciudad: "Capitán Bado", paiseCodigoAlfa: "PRY"},
{Ciudad: "Loreto", paiseCodigoAlfa: "PRY"},
{Ciudad: "Santa Rosa de Lima", paiseCodigoAlfa: "PRY"},
{Ciudad: "Alto Verá", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Joaquín", paiseCodigoAlfa: "PRY"},
{Ciudad: "Pirayú", paiseCodigoAlfa: "PRY"},
{Ciudad: "Bella Vista Norte", paiseCodigoAlfa: "PRY"},
{Ciudad: "Villa Ygatimí", paiseCodigoAlfa: "PRY"},
{Ciudad: "Obligado", paiseCodigoAlfa: "PRY"},
{Ciudad: "Raúl Arsenio Oviedo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Loma Plata", paiseCodigoAlfa: "PRY"},
{Ciudad: "Atyrá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Itapúa Poty", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yrybucuá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tacuatí", paiseCodigoAlfa: "PRY"},
{Ciudad: "Acahay", paiseCodigoAlfa: "PRY"},
{Ciudad: "Carayaó", paiseCodigoAlfa: "PRY"},
{Ciudad: "Hohenau", paiseCodigoAlfa: "PRY"},
{Ciudad: "Mayor Otaño", paiseCodigoAlfa: "PRY"},
{Ciudad: "Minga Porá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Bella Vista", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tembiaporá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Capitán Meza", paiseCodigoAlfa: "PRY"},
{Ciudad: "Altos", paiseCodigoAlfa: "PRY"},
{Ciudad: "Mbuyapey", paiseCodigoAlfa: "PRY"},
{Ciudad: "Capitán Miranda", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ybyrarobaná", paiseCodigoAlfa: "PRY"},
{Ciudad: "Caraguatay", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yatytay", paiseCodigoAlfa: "PRY"},
{Ciudad: "Belén", paiseCodigoAlfa: "PRY"},
{Ciudad: "General Artigas", paiseCodigoAlfa: "PRY"},
{Ciudad: "Santa Rosa del Mbutuy", paiseCodigoAlfa: "PRY"},
{Ciudad: "Nueva Esperanza", paiseCodigoAlfa: "PRY"},
{Ciudad: "Nueva Italia", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Roque González de Santa Cruz", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yataity del Norte", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Bernardino", paiseCodigoAlfa: "PRY"},
{Ciudad: "Lima", paiseCodigoAlfa: "PRY"},
{Ciudad: "Puerto Pinasco", paiseCodigoAlfa: "PRY"},
{Ciudad: "General Francisco Caballero Álvarez", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Lázaro", paiseCodigoAlfa: "PRY"},
{Ciudad: "Vaquería", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yby Pytá", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Alberto", paiseCodigoAlfa: "PRY"},
{Ciudad: "Itacurubí del Rosario", paiseCodigoAlfa: "PRY"},
{Ciudad: "José Domingo Ocampos", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yguazú", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Cristóbal", paiseCodigoAlfa: "PRY"},
{Ciudad: "Capitán Mauricio José Troche", paiseCodigoAlfa: "PRY"},
{Ciudad: "Itacurubí de la Cordillera", paiseCodigoAlfa: "PRY"},
{Ciudad: "Fram", paiseCodigoAlfa: "PRY"},
{Ciudad: "Villa del Rosario", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Cosme y Damián", paiseCodigoAlfa: "PRY"},
{Ciudad: "Borja", paiseCodigoAlfa: "PRY"},
{Ciudad: "Los Cedrales", paiseCodigoAlfa: "PRY"},
{Ciudad: "25 de Diciembre", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tres de Febrero", paiseCodigoAlfa: "PRY"},
{Ciudad: "Trinidad", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Juan del Paraná", paiseCodigoAlfa: "PRY"},
{Ciudad: "Corpus Christi", paiseCodigoAlfa: "PRY"},
{Ciudad: "Doctor Raúl Peña", paiseCodigoAlfa: "PRY"},
{Ciudad: "Regimiento de Infantería Tres Corrales", paiseCodigoAlfa: "PRY"},
{Ciudad: "Alberdi", paiseCodigoAlfa: "PRY"},
{Ciudad: "Pirapó", paiseCodigoAlfa: "PRY"},
{Ciudad: "Azotey", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ñacunday", paiseCodigoAlfa: "PRY"},
{Ciudad: "Carmen del Paraná", paiseCodigoAlfa: "PRY"},
{Ciudad: "Santa María de Fe", paiseCodigoAlfa: "PRY"},
{Ciudad: "La Paloma del Espíritu Santo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Mbocayaty del Guairá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ypejhú", paiseCodigoAlfa: "PRY"},
{Ciudad: "Iturbe", paiseCodigoAlfa: "PRY"},
{Ciudad: "Katueté", paiseCodigoAlfa: "PRY"},
{Ciudad: "Mbaracayú", paiseCodigoAlfa: "PRY"},
{Ciudad: "Escobar", paiseCodigoAlfa: "PRY"},
{Ciudad: "General Eugenio Alejandrino Garay", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tavapy", paiseCodigoAlfa: "PRY"},
{Ciudad: "Caapucú", paiseCodigoAlfa: "PRY"},
{Ciudad: "Doctor Cecilio Báez", paiseCodigoAlfa: "PRY"},
{Ciudad: "General Delgado", paiseCodigoAlfa: "PRY"},
{Ciudad: "Zanja Pytá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Isla Pucú", paiseCodigoAlfa: "PRY"},
{Ciudad: "Itapé", paiseCodigoAlfa: "PRY"},
{Ciudad: "Nueva Alborada", paiseCodigoAlfa: "PRY"},
{Ciudad: "Santa Rosa del Monday", paiseCodigoAlfa: "PRY"},
{Ciudad: "Quyquyhó", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ybytymí", paiseCodigoAlfa: "PRY"},
{Ciudad: "Nueva Germania", paiseCodigoAlfa: "PRY"},
{Ciudad: "Coronel Martínez", paiseCodigoAlfa: "PRY"},
{Ciudad: "General Bernardino Caballero", paiseCodigoAlfa: "PRY"},
{Ciudad: "Unión", paiseCodigoAlfa: "PRY"},
{Ciudad: "Sargento José Félix López", paiseCodigoAlfa: "PRY"},
{Ciudad: "Mariscal Francisco Solano López", paiseCodigoAlfa: "PRY"},
{Ciudad: "Valenzuela", paiseCodigoAlfa: "PRY"},
{Ciudad: "Juan de Mena", paiseCodigoAlfa: "PRY"},
{Ciudad: "José A. Fassardi", paiseCodigoAlfa: "PRY"},
{Ciudad: "Fulgencio Yegros", paiseCodigoAlfa: "PRY"},
{Ciudad: "Sapucai", paiseCodigoAlfa: "PRY"},
{Ciudad: "Puerto Casado", paiseCodigoAlfa: "PRY"},
{Ciudad: "Primero de Marzo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Santiago", paiseCodigoAlfa: "PRY"},
{Ciudad: "Simón Bolívar", paiseCodigoAlfa: "PRY"},
{Ciudad: "Félix Pérez Cardozo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Jesús", paiseCodigoAlfa: "PRY"},
{Ciudad: "General Higinio Morínigo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Iruña", paiseCodigoAlfa: "PRY"},
{Ciudad: "Buena Vista", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Miguel", paiseCodigoAlfa: "PRY"},
{Ciudad: "Nanawa", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Juan Bautista del Ñeembucú", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Alfredo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Naranjal", paiseCodigoAlfa: "PRY"},
{Ciudad: "Doctor Moisés Santiago Bertoni", paiseCodigoAlfa: "PRY"},
{Ciudad: "La Colmena", paiseCodigoAlfa: "PRY"},
{Ciudad: "Cerrito", paiseCodigoAlfa: "PRY"},
{Ciudad: "Domingo Martínez de Irala", paiseCodigoAlfa: "PRY"},
{Ciudad: "Karapaí", paiseCodigoAlfa: "PRY"},
{Ciudad: "La Pastora", paiseCodigoAlfa: "PRY"},
{Ciudad: "Natalicio Talavera", paiseCodigoAlfa: "PRY"},
{Ciudad: "Nueva Toledo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Santa Elena", paiseCodigoAlfa: "PRY"},
{Ciudad: "Nueva Londres", paiseCodigoAlfa: "PRY"},
{Ciudad: "Maciel", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yataity del Guairá", paiseCodigoAlfa: "PRY"},
{Ciudad: "José Leandro Oviedo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tebicuarymí", paiseCodigoAlfa: "PRY"},
{Ciudad: "Capitán Carmelo Peralta", paiseCodigoAlfa: "PRY"},
{Ciudad: "Fuerte Olimpo", paiseCodigoAlfa: "PRY"},
{Ciudad: "San José Obrero", paiseCodigoAlfa: "PRY"},
{Ciudad: "Antequera", paiseCodigoAlfa: "PRY"},
{Ciudad: "Mayor José Martínez", paiseCodigoAlfa: "PRY"},
{Ciudad: "José Falcón", paiseCodigoAlfa: "PRY"},
{Ciudad: "Mbocayaty del Yhaguy", paiseCodigoAlfa: "PRY"},
{Ciudad: "Paso Barreto", paiseCodigoAlfa: "PRY"},
{Ciudad: "Santa Fe del Paraná", paiseCodigoAlfa: "PRY"},
{Ciudad: "General José Eduvigis Díaz", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tacuaras", paiseCodigoAlfa: "PRY"},
{Ciudad: "Nueva Colombia", paiseCodigoAlfa: "PRY"},
{Ciudad: "Villa Oliva", paiseCodigoAlfa: "PRY"},
{Ciudad: "Villa Florida", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Patricio", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Pablo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Loma Grande", paiseCodigoAlfa: "PRY"},
{Ciudad: "Laureles", paiseCodigoAlfa: "PRY"},
{Ciudad: "Teniente Esteban Martínez", paiseCodigoAlfa: "PRY"},
{Ciudad: "Itanará", paiseCodigoAlfa: "PRY"},
{Ciudad: "Ñumí", paiseCodigoAlfa: "PRY"},
{Ciudad: "General José María Bruguez", paiseCodigoAlfa: "PRY"},
{Ciudad: "La Paz", paiseCodigoAlfa: "PRY"},
{Ciudad: "Tebicuary", paiseCodigoAlfa: "PRY"},
{Ciudad: "Humaitá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Isla Umbú", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Salvador", paiseCodigoAlfa: "PRY"},
{Ciudad: "Yabebyry", paiseCodigoAlfa: "PRY"},
{Ciudad: "Bahía Negra", paiseCodigoAlfa: "PRY"},
{Ciudad: "Villalbín", paiseCodigoAlfa: "PRY"},
{Ciudad: "Guazú Cuá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Paso de Patria", paiseCodigoAlfa: "PRY"},
{Ciudad: "Desmochados", paiseCodigoAlfa: "PRY"},
{Ciudad: "Doctor Bottrell", paiseCodigoAlfa: "PRY"},
{Ciudad: "Villa Franca", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Carlos del Apa", paiseCodigoAlfa: "PRY"},
{Ciudad: "Maracaná", paiseCodigoAlfa: "PRY"},
{Ciudad: "María Antonia", paiseCodigoAlfa: "PRY"},
{Ciudad: "San Vicente Pancholo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Arroyito", paiseCodigoAlfa: "PRY"},
{Ciudad: "Puerto Adela", paiseCodigoAlfa: "PRY"},
{Ciudad: "Paso Horqueta", paiseCodigoAlfa: "PRY"},
{Ciudad: "Cerro Corá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Campo Aceval", paiseCodigoAlfa: "PRY"},
{Ciudad: "Laurel", paiseCodigoAlfa: "PRY"},
{Ciudad: "Itacuá", paiseCodigoAlfa: "PRY"},
{Ciudad: "Puerto Ybapobo", paiseCodigoAlfa: "PRY"},
{Ciudad: "Neuland", paiseCodigoAlfa: "PRY"},
{Ciudad: "Lima", paiseCodigoAlfa: "PER"},
{Ciudad: "Arequipa", paiseCodigoAlfa: "PER"},
{Ciudad: "Callao", paiseCodigoAlfa: "PER"},
{Ciudad: "Trujillo", paiseCodigoAlfa: "PER"},
{Ciudad: "Chiclayo", paiseCodigoAlfa: "PER"},
{Ciudad: "Piura", paiseCodigoAlfa: "PER"},
{Ciudad: "Huancayo", paiseCodigoAlfa: "PER"},
{Ciudad: "Cuzco", paiseCodigoAlfa: "PER"},
{Ciudad: "Chimbote", paiseCodigoAlfa: "PER"},
{Ciudad: "Iquitos", paiseCodigoAlfa: "PER"},
{Ciudad: "Pucallpa", paiseCodigoAlfa: "PER"},
{Ciudad: "Tacna", paiseCodigoAlfa: "PER"},
{Ciudad: "Ica", paiseCodigoAlfa: "PER"},
{Ciudad: "Juliaca", paiseCodigoAlfa: "PER"},
{Ciudad: "Ayacucho", paiseCodigoAlfa: "PER"},
{Ciudad: "Cajamarca", paiseCodigoAlfa: "PER"},
{Ciudad: "Huánuco", paiseCodigoAlfa: "PER"},
{Ciudad: "Tarapoto", paiseCodigoAlfa: "PER"},
{Ciudad: "Chincha Alta", paiseCodigoAlfa: "PER"},
{Ciudad: "Huacho", paiseCodigoAlfa: "PER"},
{Ciudad: "Sullana", paiseCodigoAlfa: "PER"},
{Ciudad: "Puno", paiseCodigoAlfa: "PER"},
{Ciudad: "Huaraz", paiseCodigoAlfa: "PER"},
{Ciudad: "Huaral", paiseCodigoAlfa: "PER"},
{Ciudad: "Tumbes", paiseCodigoAlfa: "PER"},
{Ciudad: "Jaén", paiseCodigoAlfa: "PER"},
{Ciudad: "Cañete", paiseCodigoAlfa: "PER"},
{Ciudad: "Talara", paiseCodigoAlfa: "PER"},
{Ciudad: "Paita", paiseCodigoAlfa: "PER"},
{Ciudad: "Puerto Maldonado", paiseCodigoAlfa: "PER"},
{Ciudad: "Yurimaguas", paiseCodigoAlfa: "PER"},
{Ciudad: "Chulucanas", paiseCodigoAlfa: "PER"},
{Ciudad: "Catacaos", paiseCodigoAlfa: "PER"},
{Ciudad: "Pisco", paiseCodigoAlfa: "PER"},
{Ciudad: "Abancay", paiseCodigoAlfa: "PER"},
{Ciudad: "Lambayeque", paiseCodigoAlfa: "PER"},
{Ciudad: "Huaura", paiseCodigoAlfa: "PER"},
{Ciudad: "Moquegua", paiseCodigoAlfa: "PER"},
{Ciudad: "Huanchaco", paiseCodigoAlfa: "PER"},
{Ciudad: "Barranca", paiseCodigoAlfa: "PER"},
{Ciudad: "Ilo", paiseCodigoAlfa: "PER"},
{Ciudad: "San Miguel", paiseCodigoAlfa: "PER"},
{Ciudad: "Majes", paiseCodigoAlfa: "PER"},
{Ciudad: "Cerro de Pasco", paiseCodigoAlfa: "PER"},
{Ciudad: "Andahuaylas", paiseCodigoAlfa: "PER"},
{Ciudad: "Sicuani", paiseCodigoAlfa: "PER"},
{Ciudad: "Chancay", paiseCodigoAlfa: "PER"},
{Ciudad: "Tingo María", paiseCodigoAlfa: "PER"},
{Ciudad: "Moyobamba", paiseCodigoAlfa: "PER"},
{Ciudad: "Huancavelica", paiseCodigoAlfa: "PER"},
{Ciudad: "Distrito Nacional", paiseCodigoAlfa: "DOM"},
{Ciudad: "Santo Domingo Este", paiseCodigoAlfa: "DOM"},
{Ciudad: "Santiago de los Caballeros", paiseCodigoAlfa: "DOM"},
{Ciudad: "Santo Domingo Norte", paiseCodigoAlfa: "DOM"},
{Ciudad: "Santo Domingo Oeste", paiseCodigoAlfa: "DOM"},
{Ciudad: "Higuey", paiseCodigoAlfa: "DOM"},
{Ciudad: "San Luis", paiseCodigoAlfa: "DOM"},
{Ciudad: "San Felipe de Puerto Plata", paiseCodigoAlfa: "DOM"},
{Ciudad: "San Cristóbal", paiseCodigoAlfa: "DOM"},
{Ciudad: "San Pedro de Macoris", paiseCodigoAlfa: "DOM"},
{Ciudad: "Los Alcarrizos", paiseCodigoAlfa: "DOM"},
{Ciudad: "La Vega", paiseCodigoAlfa: "DOM"},
{Ciudad: "San Francisco de Macorís", paiseCodigoAlfa: "DOM"},
{Ciudad: "La Romana", paiseCodigoAlfa: "DOM"},
{Ciudad: "Moca", paiseCodigoAlfa: "DOM"},
{Ciudad: "Villa Altagracia", paiseCodigoAlfa: "DOM"},
{Ciudad: "San Juan de La Maguana", paiseCodigoAlfa: "DOM"},
{Ciudad: "Haina", paiseCodigoAlfa: "DOM"},
{Ciudad: "Bonao", paiseCodigoAlfa: "DOM"},
{Ciudad: "Cotuí", paiseCodigoAlfa: "DOM"},
{Ciudad: "Baní", paiseCodigoAlfa: "DOM"},
{Ciudad: "Santa Cruz de Barahona", paiseCodigoAlfa: "DOM"},
{Ciudad: "Azua de Compostela", paiseCodigoAlfa: "DOM"},
{Ciudad: "Boca Chica", paiseCodigoAlfa: "DOM"},
{Ciudad: "Villa hermosa", paiseCodigoAlfa: "DOM"},
{Ciudad: "Mao", paiseCodigoAlfa: "DOM"},
{Ciudad: "Pedro Brand", paiseCodigoAlfa: "DOM"},
{Ciudad: "San Antonio de Guerra", paiseCodigoAlfa: "DOM"},
{Ciudad: "San Ignacio de Sabaneta", paiseCodigoAlfa: "DOM"},
{Ciudad: "Santa Cruz del Seibo", paiseCodigoAlfa: "DOM"},
{Ciudad: "Tamboril", paiseCodigoAlfa: "DOM"},
{Ciudad: "Nagua", paiseCodigoAlfa: "DOM"},
{Ciudad: "Puñal", paiseCodigoAlfa: "DOM"},
{Ciudad: "Hato Mayor del Rey", paiseCodigoAlfa: "DOM"},
{Ciudad: "Esperanza", paiseCodigoAlfa: "DOM"},
{Ciudad: "Sosúa", paiseCodigoAlfa: "DOM"},
{Ciudad: "Jarabacoa", paiseCodigoAlfa: "DOM"},
{Ciudad: "San José de las Matas", paiseCodigoAlfa: "DOM"},
{Ciudad: "Yamasá", paiseCodigoAlfa: "DOM"},
{Ciudad: "Monte Plata", paiseCodigoAlfa: "DOM"},
{Ciudad: "Villa González", paiseCodigoAlfa: "DOM"},
{Ciudad: "Montevideo", paiseCodigoAlfa: "URY"},
{Ciudad: "Ciudad de la Costa", paiseCodigoAlfa: "URY"},
{Ciudad: "Salto", paiseCodigoAlfa: "URY"},
{Ciudad: "Paysandú", paiseCodigoAlfa: "URY"},
{Ciudad: "Maldonado", paiseCodigoAlfa: "URY"},
{Ciudad: "Rivera", paiseCodigoAlfa: "URY"},
{Ciudad: "Las Piedras", paiseCodigoAlfa: "URY"},
{Ciudad: "Tacuarembó", paiseCodigoAlfa: "URY"},
{Ciudad: "Melo", paiseCodigoAlfa: "URY"},
{Ciudad: "Artigas", paiseCodigoAlfa: "URY"},
{Ciudad: "Mercedes", paiseCodigoAlfa: "URY"},
{Ciudad: "Minas", paiseCodigoAlfa: "URY"},
{Ciudad: "San José de Mayo", paiseCodigoAlfa: "URY"},
{Ciudad: "Durazno", paiseCodigoAlfa: "URY"},
{Ciudad: "Florida", paiseCodigoAlfa: "URY"},
{Ciudad: "Treinta y Tres", paiseCodigoAlfa: "URY"},
{Ciudad: "Barros Blancos", paiseCodigoAlfa: "URY"},
{Ciudad: "Ciudad del Plata", paiseCodigoAlfa: "URY"},
{Ciudad: "San Carlos", paiseCodigoAlfa: "URY"},
{Ciudad: "Colonia del Sacramento", paiseCodigoAlfa: "URY"},
{Ciudad: "Pando", paiseCodigoAlfa: "URY"},
{Ciudad: "Rocha", paiseCodigoAlfa: "URY"},
{Ciudad: "Fray Bentos", paiseCodigoAlfa: "URY"},
{Ciudad: "Salinas", paiseCodigoAlfa: "URY"},
{Ciudad: "Trinidad", paiseCodigoAlfa: "URY"},
{Ciudad: "18 de Mayo", paiseCodigoAlfa: "URY"},
{Ciudad: "La Paz", paiseCodigoAlfa: "URY"},
{Ciudad: "Canelones", paiseCodigoAlfa: "URY"},
{Ciudad: "Dolores", paiseCodigoAlfa: "URY"},
{Ciudad: "Carmelo", paiseCodigoAlfa: "URY"},
{Ciudad: "Bella Unión", paiseCodigoAlfa: "URY"},
{Ciudad: "Young", paiseCodigoAlfa: "URY"},
{Ciudad: "Santa Lucía", paiseCodigoAlfa: "URY"},
{Ciudad: "Progreso", paiseCodigoAlfa: "URY"},
{Ciudad: "Paso Carrasco", paiseCodigoAlfa: "URY"},
{Ciudad: "Joaquín Suárez", paiseCodigoAlfa: "URY"},
{Ciudad: "Nueva Helvecia", paiseCodigoAlfa: "URY"},
{Ciudad: "General Líber Seregni", paiseCodigoAlfa: "URY"},
{Ciudad: "Río Branco", paiseCodigoAlfa: "URY"},
{Ciudad: "Toledo", paiseCodigoAlfa: "URY"},
{Ciudad: "Paso de los Toros", paiseCodigoAlfa: "URY"},
{Ciudad: "Juan Lacaze", paiseCodigoAlfa: "URY"},
{Ciudad: "Punta del Este", paiseCodigoAlfa: "URY"},
{Ciudad: "Parque del Plata", paiseCodigoAlfa: "URY"},
{Ciudad: "Piriápolis", paiseCodigoAlfa: "URY"},
{Ciudad: "Libertad", paiseCodigoAlfa: "URY"},
{Ciudad: "Rosario", paiseCodigoAlfa: "URY"},
{Ciudad: "Nueva Palmira", paiseCodigoAlfa: "URY"},
{Ciudad: "Chuy", paiseCodigoAlfa: "URY"},
{Ciudad: "Atlántida", paiseCodigoAlfa: "URY"},
{Ciudad: "Cardona", paiseCodigoAlfa: "URY"},
{Ciudad: "Lascano", paiseCodigoAlfa: "URY"},
{Ciudad: "Castillos", paiseCodigoAlfa: "URY"},
{Ciudad: "Pan de Azúcar", paiseCodigoAlfa: "URY"},
{Ciudad: "Tranqueras", paiseCodigoAlfa: "URY"},
{Ciudad: "Sarandí del Yí", paiseCodigoAlfa: "URY"},
{Ciudad: "San Ramón", paiseCodigoAlfa: "URY"},
{Ciudad: "Tarariras", paiseCodigoAlfa: "URY"},
{Ciudad: "Sauce", paiseCodigoAlfa: "URY"},
{Ciudad: "Sarandí Grande", paiseCodigoAlfa: "URY"},
{Ciudad: "José Pedro Varela", paiseCodigoAlfa: "URY"},
{Ciudad: "Tala", paiseCodigoAlfa: "URY"},
{Ciudad: "Guichón", paiseCodigoAlfa: "URY"},
{Ciudad: "La Paloma", paiseCodigoAlfa: "URY"},
{Ciudad: "Caracas", paiseCodigoAlfa: "VEN"},
{Ciudad: "Maracaibo", paiseCodigoAlfa: "VEN"},
{Ciudad: "Valencia", paiseCodigoAlfa: "VEN"},
{Ciudad: "Barquisimeto", paiseCodigoAlfa: "VEN"},
{Ciudad: "Maracay", paiseCodigoAlfa: "VEN"},
{Ciudad: "Ciudad Guayana", paiseCodigoAlfa: "VEN"},
{Ciudad: "Barcelona", paiseCodigoAlfa: "VEN"},
{Ciudad: "San Cristóbal", paiseCodigoAlfa: "VEN"},
{Ciudad: "Maturín", paiseCodigoAlfa: "VEN"},
{Ciudad: "Barinas", paiseCodigoAlfa: "VEN"},
{Ciudad: "Ciudad Bolívar", paiseCodigoAlfa: "VEN"},
{Ciudad: "Cumaná", paiseCodigoAlfa: "VEN"},
{Ciudad: "Mérida", paiseCodigoAlfa: "VEN"},
{Ciudad: "Valera", paiseCodigoAlfa: "VEN"},
{Ciudad: "Cabimas", paiseCodigoAlfa: "VEN"},
{Ciudad: "Santa Teresa del Tuy", paiseCodigoAlfa: "VEN"},
{Ciudad: "Punto Fijo", paiseCodigoAlfa: "VEN"},
{Ciudad: "Acarigua", paiseCodigoAlfa: "VEN"},
{Ciudad: "Los Teques", paiseCodigoAlfa: "VEN"},
{Ciudad: "Coro", paiseCodigoAlfa: "VEN"},
{Ciudad: "Guanare", paiseCodigoAlfa: "VEN"},
{Ciudad: "Ciudad Ojeda", paiseCodigoAlfa: "VEN"},
{Ciudad: "Puerto Cabello", paiseCodigoAlfa: "VEN"},
{Ciudad: "Guarenas", paiseCodigoAlfa: "VEN"},
{Ciudad: "Puerto La Cruz", paiseCodigoAlfa: "VEN"},
{Ciudad: "Guatire", paiseCodigoAlfa: "VEN"},
{Ciudad: "Turmero", paiseCodigoAlfa: "VEN"},
{Ciudad: "Tocuyito", paiseCodigoAlfa: "VEN"},
{Ciudad: "El Tigre", paiseCodigoAlfa: "VEN"},
{Ciudad: "Carora", paiseCodigoAlfa: "VEN"},
{Ciudad: "La Victoria", paiseCodigoAlfa: "VEN"},
{Ciudad: "Cabudare", paiseCodigoAlfa: "VEN"},
{Ciudad: "Carúpano", paiseCodigoAlfa: "VEN"},
{Ciudad: "San Fernando de Apure", paiseCodigoAlfa: "VEN"},
{Ciudad: "Guacara", paiseCodigoAlfa: "VEN"},
{Ciudad: "El Tocuyo", paiseCodigoAlfa: "VEN"},
{Ciudad: "Los Guayos", paiseCodigoAlfa: "VEN"},
{Ciudad: "Santa Rita", paiseCodigoAlfa: "VEN"},
{Ciudad: "Güigüe", paiseCodigoAlfa: "VEN"},
{Ciudad: "Anaco", paiseCodigoAlfa: "VEN"},
{Ciudad: "San Juan de Los Morros", paiseCodigoAlfa: "VEN"},
{Ciudad: "Quibor", paiseCodigoAlfa: "VEN"},
{Ciudad: "El Vigía", paiseCodigoAlfa: "VEN"},
{Ciudad: "Palo Negro", paiseCodigoAlfa: "VEN"},
{Ciudad: "San Felipe", paiseCodigoAlfa: "VEN"},
{Ciudad: "San Carlos", paiseCodigoAlfa: "VEN"},
{Ciudad: "Mariara", paiseCodigoAlfa: "VEN"},
{Ciudad: "Villa de Cura", paiseCodigoAlfa: "VEN"},
{Ciudad: "Ocumare del Tuy", paiseCodigoAlfa: "VEN"},
{Ciudad: "Yaritagua", paiseCodigoAlfa: "VEN"},
{Ciudad: "Cúa", paiseCodigoAlfa: "VEN"},
{Ciudad: "Araure", paiseCodigoAlfa: "VEN"},
{Ciudad: "Calabozo", paiseCodigoAlfa: "VEN"},
{Ciudad: "Táriba", paiseCodigoAlfa: "VEN"},
{Ciudad: "Guasdualito", paiseCodigoAlfa: "VEN"},
{Ciudad: "Puerto Ayacucho", paiseCodigoAlfa: "VEN"},
{Ciudad: "Machiques", paiseCodigoAlfa: "VEN"},
{Ciudad: "Cagua", paiseCodigoAlfa: "VEN"},
{Ciudad: "Porlamar", paiseCodigoAlfa: "VEN"},
{Ciudad: "Charallave", paiseCodigoAlfa: "VEN"},
{Ciudad: "La Asunción", paiseCodigoAlfa: "VEN"},
{Ciudad: "Valle de la Pascua", paiseCodigoAlfa: "VEN"},
{Ciudad: "Santa Lucía", paiseCodigoAlfa: "VEN"},
{Ciudad: "Trujillo", paiseCodigoAlfa: "VEN"},
{Ciudad: "El Valle del Espiritu Santo", paiseCodigoAlfa: "VEN"},
{Ciudad: "Tinaquillo", paiseCodigoAlfa: "VEN"},
{Ciudad: "Puerto Píritu", paiseCodigoAlfa: "VEN"},
{Ciudad: "El Limón", paiseCodigoAlfa: "VEN"},
{Ciudad: "Socopó", paiseCodigoAlfa: "VEN"},
{Ciudad: "Boconó", paiseCodigoAlfa: "VEN"},
{Ciudad: "Punta de Mata", paiseCodigoAlfa: "VEN"},
{Ciudad: "Ejido", paiseCodigoAlfa: "VEN"},
{Ciudad: "Upata", paiseCodigoAlfa: "VEN"},
{Ciudad: "Rubio", paiseCodigoAlfa: "VEN"},
{Ciudad: "Caja Seca", paiseCodigoAlfa: "VEN"},
{Ciudad: "Catia La Mar", paiseCodigoAlfa: "VEN"},
{Ciudad: "Tumeremo", paiseCodigoAlfa: "VEN"},
{Ciudad: "Cantaura", paiseCodigoAlfa: "VEN"},
{Ciudad: "La Grita", paiseCodigoAlfa: "VEN"},
{Ciudad: "Santa Bárbara del Zulia", paiseCodigoAlfa: "VEN"},
{Ciudad: "Tucupita", paiseCodigoAlfa: "VEN"},
{Ciudad: "San José de Guanipa", paiseCodigoAlfa: "VEN"},
{Ciudad: "Chivacoa", paiseCodigoAlfa: "VEN"},
{Ciudad: "Lechería", paiseCodigoAlfa: "VEN"},
{Ciudad: "Zaraza", paiseCodigoAlfa: "VEN"},
{Ciudad: "Nirgua", paiseCodigoAlfa: "VEN"},
{Ciudad: "Siquisique", paiseCodigoAlfa: "VEN"},
{Ciudad: "Guanta", paiseCodigoAlfa: "VEN"},
{Ciudad: "Morón", paiseCodigoAlfa: "VEN"},
{Ciudad: "Pariaguán", paiseCodigoAlfa: "VEN"},
{Ciudad: "San Juan de Colón", paiseCodigoAlfa: "VEN"},
{Ciudad: "San Joaquín", paiseCodigoAlfa: "VEN"},
{Ciudad: "San Antonio de los Altos", paiseCodigoAlfa: "VEN"},
{Ciudad: "Caicara del Orinoco", paiseCodigoAlfa: "VEN"},
{Ciudad: "Achaguas", paiseCodigoAlfa: "VEN"},
{Ciudad: "Biruaca", paiseCodigoAlfa: "VEN"},
{Ciudad: "Pampatar", paiseCodigoAlfa: "VEN"},
{Ciudad: "La Guaira", paiseCodigoAlfa: "VEN"},
{Ciudad: "Maiquetía", paiseCodigoAlfa: "VEN"},
]

module.exports={ciudades}