const ciudades =[
    {ciudad: "Buenos Aires", paiseCodigoAlfa: "ARG"},
    {ciudad: "Córdoba", paiseCodigoAlfa: "ARG"},
    {ciudad: "Rosario", paiseCodigoAlfa: "ARG"},
    {ciudad: "Mar del Plata", paiseCodigoAlfa: "ARG"},
    {ciudad: "San Miguel de Tucumán", paiseCodigoAlfa: "ARG"},
    {ciudad: "Salta", paiseCodigoAlfa: "ARG"},
    {ciudad: "Santa Fe", paiseCodigoAlfa: "ARG"},
    {ciudad: "Corrientes", paiseCodigoAlfa: "ARG"},
    {ciudad: "Bahía Blanca", paiseCodigoAlfa: "ARG"},
    {ciudad: "Resistencia", paiseCodigoAlfa: "ARG"},
    {ciudad: "Posadas", paiseCodigoAlfa: "ARG"},
    {ciudad: "Merlo", paiseCodigoAlfa: "ARG"},
    {ciudad: "Quilmes", paiseCodigoAlfa: "ARG"},
    {ciudad: "San Salvador de Jujuy", paiseCodigoAlfa: "ARG"},
    {ciudad: "Guaymallén", paiseCodigoAlfa: "ARG"},
    {ciudad: "Santiago del Estero", paiseCodigoAlfa: "ARG"},
    {ciudad: "Gregorio de Laferrere", paiseCodigoAlfa: "ARG"},
    {ciudad: "José C. Paz", paiseCodigoAlfa: "ARG"},
    {ciudad: "Paraná", paiseCodigoAlfa: "ARG"},
    {ciudad: "Banfield", paiseCodigoAlfa: "ARG"},
    {ciudad: "González Catán", paiseCodigoAlfa: "ARG"},
    {ciudad: "Neuquén", paiseCodigoAlfa: "ARG"},
    {ciudad: "Formosa", paiseCodigoAlfa: "ARG"},
    {ciudad: "Lanús", paiseCodigoAlfa: "ARG"},
    {ciudad: "La Plata", paiseCodigoAlfa: "ARG"},
    {ciudad: "Godoy Cruz", paiseCodigoAlfa: "ARG"},
    {ciudad: "Isidro Casanova", paiseCodigoAlfa: "ARG"},
    {ciudad: "Las Heras", paiseCodigoAlfa: "ARG"},
    {ciudad: "Berazategui", paiseCodigoAlfa: "ARG"},
    {ciudad: "La Rioja", paiseCodigoAlfa: "ARG"},
    {ciudad: "Comodoro Rivadavia", paiseCodigoAlfa: "ARG"},
    {ciudad: "Moreno", paiseCodigoAlfa: "ARG"},
    {ciudad: "San Luis", paiseCodigoAlfa: "ARG"},
    {ciudad: "San Miguel", paiseCodigoAlfa: "ARG"},
    {ciudad: "San Fernando del Valle de Catamarca", paiseCodigoAlfa: "ARG"},
    {ciudad: "Río Cuarto", paiseCodigoAlfa: "ARG"},
    {ciudad: "Virrey del Pino", paiseCodigoAlfa: "ARG"},
    {ciudad: "Leones", paiseCodigoAlfa: "ARG"},
    {ciudad: "Luján de Cuyo", paiseCodigoAlfa: "ARG"},
    {ciudad: "Pinamar", paiseCodigoAlfa: "ARG"},
    {ciudad: "Olavarría", paiseCodigoAlfa: "ARG"},
    {ciudad: "Azul", paiseCodigoAlfa: "ARG"},
    {ciudad: "Espigas", paiseCodigoAlfa: "ARG"},
    {ciudad: "Santa Cruz de la Sierra", paiseCodigoAlfa: "BOL"},
    {ciudad: "El Alto", paiseCodigoAlfa: "BOL"},
    {ciudad: "La Paz", paiseCodigoAlfa: "BOL"},
    {ciudad: "Cochabamba", paiseCodigoAlfa: "BOL"},
    {ciudad: "Oruro", paiseCodigoAlfa: "BOL"},
    {ciudad: "Sucre", paiseCodigoAlfa: "BOL"},
    {ciudad: "Tarija", paiseCodigoAlfa: "BOL"},
    {ciudad: "Potosí", paiseCodigoAlfa: "BOL"},
    {ciudad: "Warnes", paiseCodigoAlfa: "BOL"},
    {ciudad: "Sacaba", paiseCodigoAlfa: "BOL"},
    {ciudad: "La Guardia", paiseCodigoAlfa: "BOL"},
    {ciudad: "Quillacollo", paiseCodigoAlfa: "BOL"},
    {ciudad: "Montero", paiseCodigoAlfa: "BOL"},
    {ciudad: "Trinidad", paiseCodigoAlfa: "BOL"},
    {ciudad: "Yacuiba", paiseCodigoAlfa: "BOL"},
    {ciudad: "Sao Paulo", paiseCodigoAlfa: "BRA"},
    {ciudad: "Rio de Janeiro", paiseCodigoAlfa: "BRA"},
    {ciudad: "Salvador", paiseCodigoAlfa: "BRA"},
    {ciudad: "Brasilia", paiseCodigoAlfa: "BRA"},
    {ciudad: "Fortaleza", paiseCodigoAlfa: "BRA"},
    {ciudad: "Belo Horizonte", paiseCodigoAlfa: "BRA"},
    {ciudad: "Manaus", paiseCodigoAlfa: "BRA"},
    {ciudad: "Curitiba", paiseCodigoAlfa: "BRA"},
    {ciudad: "Recife", paiseCodigoAlfa: "BRA"},
    {ciudad: "Porto Alegre", paiseCodigoAlfa: "BRA"},
    {ciudad: "Belém", paiseCodigoAlfa: "BRA"},
    {ciudad: "Goiania", paiseCodigoAlfa: "BRA"},
    {ciudad: "Sao Luís", paiseCodigoAlfa: "BRA"},
    {ciudad: "Maceió", paiseCodigoAlfa: "BRA"},
    {ciudad: "Teresina", paiseCodigoAlfa: "BRA"},
    {ciudad: "Natal", paiseCodigoAlfa: "BRA"},
    {ciudad: "Campo Grande", paiseCodigoAlfa: "BRA"},
    {ciudad: "Joao Pessoa", paiseCodigoAlfa: "BRA"},
    {ciudad: "Aracaju", paiseCodigoAlfa: "BRA"},
    {ciudad: "Cuiabá", paiseCodigoAlfa: "BRA"},
    {ciudad: "Porto Velho", paiseCodigoAlfa: "BRA"},
    {ciudad: "Florianópolis", paiseCodigoAlfa: "BRA"},
    {ciudad: "Macapá", paiseCodigoAlfa: "BRA"},
    {ciudad: "Rio Branco", paiseCodigoAlfa: "BRA"},
    {ciudad: "Vitória", paiseCodigoAlfa: "BRA"},
    {ciudad: "Boa Vista", paiseCodigoAlfa: "BRA"},
    {ciudad: "Palmas", paiseCodigoAlfa: "BRA"},
    {ciudad: "Gran Santiago", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran Concepción", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran Valparaíso", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran La Serena", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran Temuco", paiseCodigoAlfa: "CHL"},
    {ciudad: "Antofagasta", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran Iquique", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran Puerto Montt", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran Talca", paiseCodigoAlfa: "CHL"},
    {ciudad: "Arica", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran Rancagua", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran Chillan", paiseCodigoAlfa: "CHL"},
    {ciudad: "Los Ángeles", paiseCodigoAlfa: "CHL"},
    {ciudad: "Calama", paiseCodigoAlfa: "CHL"},
    {ciudad: "Colina", paiseCodigoAlfa: "CHL"},
    {ciudad: "Valdivia", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran Quillota", paiseCodigoAlfa: "CHL"},
    {ciudad: "Osorno", paiseCodigoAlfa: "CHL"},
    {ciudad: "Copiapó", paiseCodigoAlfa: "CHL"},
    {ciudad: "Curicó", paiseCodigoAlfa: "CHL"},
    {ciudad: "Punta Arenas", paiseCodigoAlfa: "CHL"},
    {ciudad: "Melipilla", paiseCodigoAlfa: "CHL"},
    {ciudad: "Gran San Antonio", paiseCodigoAlfa: "CHL"},
    {ciudad: "Lampa", paiseCodigoAlfa: "CHL"},
    {ciudad: "Ovalle", paiseCodigoAlfa: "CHL"},
    {ciudad: "Buin", paiseCodigoAlfa: "CHL"},
    {ciudad: "Los Andes Calle Larga San Esteban", paiseCodigoAlfa: "CHL"},
    {ciudad: "Linares", paiseCodigoAlfa: "CHL"},
    {ciudad: "Peñaflor", paiseCodigoAlfa: "CHL"},
    {ciudad: "San Felipe", paiseCodigoAlfa: "CHL"},
    {ciudad: "Paine", paiseCodigoAlfa: "CHL"},
    {ciudad: "Talagante", paiseCodigoAlfa: "CHL"},
    {ciudad: "San Fernando", paiseCodigoAlfa: "CHL"},
    {ciudad: "Limache Olmué", paiseCodigoAlfa: "CHL"},
    {ciudad: "Rengo", paiseCodigoAlfa: "CHL"},
    {ciudad: "Coyhaique", paiseCodigoAlfa: "CHL"},
    {ciudad: "Villarrica", paiseCodigoAlfa: "CHL"},
    {ciudad: "Vallenar", paiseCodigoAlfa: "CHL"},
    {ciudad: "San Carlos", paiseCodigoAlfa: "CHL"},
    {ciudad: "Angol", paiseCodigoAlfa: "CHL"},
    {ciudad: "San Vicente de Tagua Tagua", paiseCodigoAlfa: "CHL"},
    {ciudad: "Cauquenes", paiseCodigoAlfa: "CHL"},
    {ciudad: "Bogotá", paiseCodigoAlfa: "COL"},
    {ciudad: "Medellín", paiseCodigoAlfa: "COL"},
    {ciudad: "Cali", paiseCodigoAlfa: "COL"},
    {ciudad: "Barranquilla", paiseCodigoAlfa: "COL"},
    {ciudad: "Cartagena", paiseCodigoAlfa: "COL"},
    {ciudad: "Cúcuta", paiseCodigoAlfa: "COL"},
    {ciudad: "Soacha", paiseCodigoAlfa: "COL"},
    {ciudad: "Soledad", paiseCodigoAlfa: "COL"},
    {ciudad: "Bucaramanga", paiseCodigoAlfa: "COL"},
    {ciudad: "Bello", paiseCodigoAlfa: "COL"},
    {ciudad: "Villavicencio", paiseCodigoAlfa: "COL"},
    {ciudad: "Ibagué", paiseCodigoAlfa: "COL"},
    {ciudad: "Santa Marta", paiseCodigoAlfa: "COL"},
    {ciudad: "Valledupar", paiseCodigoAlfa: "COL"},
    {ciudad: "Montería", paiseCodigoAlfa: "COL"},
    {ciudad: "Pereira", paiseCodigoAlfa: "COL"},
    {ciudad: "Manizales", paiseCodigoAlfa: "COL"},
    {ciudad: "Pasto", paiseCodigoAlfa: "COL"},
    {ciudad: "Neiva", paiseCodigoAlfa: "COL"},
    {ciudad: "Palmira", paiseCodigoAlfa: "COL"},
    {ciudad: "Popayán", paiseCodigoAlfa: "COL"},
    {ciudad: "Buenaventura", paiseCodigoAlfa: "COL"},
    {ciudad: "Floridablanca", paiseCodigoAlfa: "COL"},
    {ciudad: "Armenia", paiseCodigoAlfa: "COL"},
    {ciudad: "Sincelejo", paiseCodigoAlfa: "COL"},
    {ciudad: "Itaguí", paiseCodigoAlfa: "COL"},
    {ciudad: "Tumaco", paiseCodigoAlfa: "COL"},
    {ciudad: "Envigado", paiseCodigoAlfa: "COL"},
    {ciudad: "Dosquebradas", paiseCodigoAlfa: "COL"},
    {ciudad: "Tuluá", paiseCodigoAlfa: "COL"},
    {ciudad: "Barrancabermeja", paiseCodigoAlfa: "COL"},
    {ciudad: "Riohacha", paiseCodigoAlfa: "COL"},
    {ciudad: "Uribia", paiseCodigoAlfa: "COL"},
    {ciudad: "Maicao", paiseCodigoAlfa: "COL"},
    {ciudad: "Piedecuesta", paiseCodigoAlfa: "COL"},
    {ciudad: "Tunja", paiseCodigoAlfa: "COL"},
    {ciudad: "Yopal", paiseCodigoAlfa: "COL"},
    {ciudad: "Florencia", paiseCodigoAlfa: "COL"},
    {ciudad: "Girón", paiseCodigoAlfa: "COL"},
    {ciudad: "Jamundí", paiseCodigoAlfa: "COL"},
    {ciudad: "Facatativá", paiseCodigoAlfa: "COL"},
    {ciudad: "Fusagasugá", paiseCodigoAlfa: "COL"},
    {ciudad: "Mosquera", paiseCodigoAlfa: "COL"},
    {ciudad: "Chía", paiseCodigoAlfa: "COL"},
    {ciudad: "Zipaquirá", paiseCodigoAlfa: "COL"},
    {ciudad: "Rionegro", paiseCodigoAlfa: "COL"},
    {ciudad: "Magangué", paiseCodigoAlfa: "COL"},
    {ciudad: "Malambo", paiseCodigoAlfa: "COL"},
    {ciudad: "Cartago", paiseCodigoAlfa: "COL"},
    {ciudad: "Sogamoso", paiseCodigoAlfa: "COL"},
    {ciudad: "Quibdó", paiseCodigoAlfa: "COL"},
    {ciudad: "Turbo", paiseCodigoAlfa: "COL"},
    {ciudad: "Ocaña", paiseCodigoAlfa: "COL"},
    {ciudad: "Buga", paiseCodigoAlfa: "COL"},
    {ciudad: "Pitalito", paiseCodigoAlfa: "COL"},
    {ciudad: "Apartadó", paiseCodigoAlfa: "COL"},
    {ciudad: "Madrid", paiseCodigoAlfa: "COL"},
    {ciudad: "Duitama", paiseCodigoAlfa: "COL"},
    {ciudad: "Ciénaga", paiseCodigoAlfa: "COL"},
    {ciudad: "Aguachica", paiseCodigoAlfa: "COL"},
    {ciudad: "Ipiales", paiseCodigoAlfa: "COL"},
    {ciudad: "Lorica", paiseCodigoAlfa: "COL"},
    {ciudad: "Turbaco", paiseCodigoAlfa: "COL"},
    {ciudad: "Santander de Quilichao", paiseCodigoAlfa: "COL"},
    {ciudad: "Villa del Rosario", paiseCodigoAlfa: "COL"},
    {ciudad: "Sahagún", paiseCodigoAlfa: "COL"},
    {ciudad: "Yumbo", paiseCodigoAlfa: "COL"},
    {ciudad: "Girardot", paiseCodigoAlfa: "COL"},
    {ciudad: "Cereté", paiseCodigoAlfa: "COL"},
    {ciudad: "Funza", paiseCodigoAlfa: "COL"},
    {ciudad: "Sabanalarga", paiseCodigoAlfa: "COL"},
    {ciudad: "Los Patios", paiseCodigoAlfa: "COL"},
    {ciudad: "Arauca", paiseCodigoAlfa: "COL"},
    {ciudad: "Caucasia", paiseCodigoAlfa: "COL"},
    {ciudad: "Tierralta", paiseCodigoAlfa: "COL"},
    {ciudad: "Candelaria", paiseCodigoAlfa: "COL"},
    {ciudad: "Manaure", paiseCodigoAlfa: "COL"},
    {ciudad: "Cajicá", paiseCodigoAlfa: "COL"},
    {ciudad: "Acacías", paiseCodigoAlfa: "COL"},
    {ciudad: "Sabaneta", paiseCodigoAlfa: "COL"},
    {ciudad: "Montelíbano", paiseCodigoAlfa: "COL"},
    {ciudad: "Caldas", paiseCodigoAlfa: "COL"},
    {ciudad: "Copacabana", paiseCodigoAlfa: "COL"},
    {ciudad: "Santa Rosa de Cabal", paiseCodigoAlfa: "COL"},
    {ciudad: "Cumaribo", paiseCodigoAlfa: "COL"},
    {ciudad: "La Estrella", paiseCodigoAlfa: "COL"},
    {ciudad: "Calarcá", paiseCodigoAlfa: "COL"},
    {ciudad: "Garzón", paiseCodigoAlfa: "COL"},
    {ciudad: "La Dorada", paiseCodigoAlfa: "COL"},
    {ciudad: "Zona Bananera", paiseCodigoAlfa: "COL"},
    {ciudad: "Arjona", paiseCodigoAlfa: "COL"},
    {ciudad: "El Carmen de Bolívar", paiseCodigoAlfa: "COL"},
    {ciudad: "Espinal", paiseCodigoAlfa: "COL"},
    {ciudad: "Corozal", paiseCodigoAlfa: "COL"},
    {ciudad: "Granada", paiseCodigoAlfa: "COL"},
    {ciudad: "Fundación", paiseCodigoAlfa: "COL"},
    {ciudad: "El Banco", paiseCodigoAlfa: "COL"},
    {ciudad: "La Ceja", paiseCodigoAlfa: "COL"},
    {ciudad: "Marinilla", paiseCodigoAlfa: "COL"},
    {ciudad: "Villamaría", paiseCodigoAlfa: "COL"},
    {ciudad: "Puerto Asís", paiseCodigoAlfa: "COL"},
    {ciudad: "Baranoa", paiseCodigoAlfa: "COL"},
    {ciudad: "Galapa", paiseCodigoAlfa: "COL"},
    {ciudad: "Planeta Rica", paiseCodigoAlfa: "COL"},
    {ciudad: "Agustín Codazzi", paiseCodigoAlfa: "COL"},
    {ciudad: "Plato", paiseCodigoAlfa: "COL"},
    {ciudad: "Saravena", paiseCodigoAlfa: "COL"},
    {ciudad: "El Carmen de Viboral", paiseCodigoAlfa: "COL"},
    {ciudad: "La Plata", paiseCodigoAlfa: "COL"},
    {ciudad: "San Marcos", paiseCodigoAlfa: "COL"},
    {ciudad: "Ciénaga de Oro", paiseCodigoAlfa: "COL"},
    {ciudad: "Chigorodó", paiseCodigoAlfa: "COL"},
    {ciudad: "San Gil", paiseCodigoAlfa: "COL"},
    {ciudad: "Mocoa", paiseCodigoAlfa: "COL"},
    {ciudad: "Tibú", paiseCodigoAlfa: "COL"},
    {ciudad: "Guarne", paiseCodigoAlfa: "COL"},
    {ciudad: "Florida", paiseCodigoAlfa: "COL"},
    {ciudad: "Chiquinquirá", paiseCodigoAlfa: "COL"},
    {ciudad: "San Andrés", paiseCodigoAlfa: "COL"},
    {ciudad: "El Cerrito", paiseCodigoAlfa: "COL"},
    {ciudad: "Barbacoas", paiseCodigoAlfa: "COL"},
    {ciudad: "Arauquita", paiseCodigoAlfa: "COL"},
    {ciudad: "San José del Guaviare", paiseCodigoAlfa: "COL"},
    {ciudad: "Riosucio", paiseCodigoAlfa: "COL"},
    {ciudad: "Tuchín", paiseCodigoAlfa: "COL"},
    {ciudad: "Girardota", paiseCodigoAlfa: "COL"},
    {ciudad: "Barbosa", paiseCodigoAlfa: "COL"},
    {ciudad: "Pamplona", paiseCodigoAlfa: "COL"},
    {ciudad: "El Bagre", paiseCodigoAlfa: "COL"},
    {ciudad: "El Tambo", paiseCodigoAlfa: "COL"},
    {ciudad: "Puerto Colombia", paiseCodigoAlfa: "COL"},
    {ciudad: "San Pelayo", paiseCodigoAlfa: "COL"},
    {ciudad: "San Vicente del Caguán", paiseCodigoAlfa: "COL"},
    {ciudad: "Chinchiná", paiseCodigoAlfa: "COL"},
    {ciudad: "Carepa", paiseCodigoAlfa: "COL"},
    {ciudad: "San Onofre", paiseCodigoAlfa: "COL"},
    {ciudad: "La Jagua de Ibirico", paiseCodigoAlfa: "COL"},
    {ciudad: "Chaparral", paiseCodigoAlfa: "COL"},
    {ciudad: "San José", paiseCodigoAlfa: "CRC"},
    {ciudad: "Alajuela", paiseCodigoAlfa: "CRC"},
    {ciudad: "Cartago", paiseCodigoAlfa: "CRC"},
    {ciudad: "Heredia", paiseCodigoAlfa: "CRC"},
    {ciudad: "Liberia", paiseCodigoAlfa: "CRC"},
    {ciudad: "Puntarenas", paiseCodigoAlfa: "CRC"},
    {ciudad: "Limón", paiseCodigoAlfa: "CRC"},
    {ciudad: "La Habana", paiseCodigoAlfa: "CUB"},
    {ciudad: "Santiago de Cuba", paiseCodigoAlfa: "CUB"},
    {ciudad: "Camaguey", paiseCodigoAlfa: "CUB"},
    {ciudad: "Holguín", paiseCodigoAlfa: "CUB"},
    {ciudad: "Guantánamo", paiseCodigoAlfa: "CUB"},
    {ciudad: "Santa Clara", paiseCodigoAlfa: "CUB"},
    {ciudad: "Las Tunas", paiseCodigoAlfa: "CUB"},
    {ciudad: "Bayamo", paiseCodigoAlfa: "CUB"},
    {ciudad: "Cienfuegos", paiseCodigoAlfa: "CUB"},
    {ciudad: "Pinar del Río", paiseCodigoAlfa: "CUB"},
    {ciudad: "Matanzas", paiseCodigoAlfa: "CUB"},
    {ciudad: "Ciego de Ávila", paiseCodigoAlfa: "CUB"},
    {ciudad: "Sancti Spíritus", paiseCodigoAlfa: "CUB"},
    {ciudad: "Manzanillo", paiseCodigoAlfa: "CUB"},
    {ciudad: "Cárdenas", paiseCodigoAlfa: "CUB"},
    {ciudad: "Palma Soriano", paiseCodigoAlfa: "CUB"},
    {ciudad: "Moa", paiseCodigoAlfa: "CUB"},
    {ciudad: "Morón", paiseCodigoAlfa: "CUB"},
    {ciudad: "Florida", paiseCodigoAlfa: "CUB"},
    {ciudad: "Contramaestre", paiseCodigoAlfa: "CUB"},
    {ciudad: "Artemisa", paiseCodigoAlfa: "CUB"},
    {ciudad: "Nueva Gerona", paiseCodigoAlfa: "CUB"},
    {ciudad: "Trinidad", paiseCodigoAlfa: "CUB"},
    {ciudad: "Colón", paiseCodigoAlfa: "CUB"},
    {ciudad: "Baracoa", paiseCodigoAlfa: "CUB"},
    {ciudad: "Guines", paiseCodigoAlfa: "CUB"},
    {ciudad: "Placetas", paiseCodigoAlfa: "CUB"},
    {ciudad: "Nuevitas", paiseCodigoAlfa: "CUB"},
    {ciudad: "Sagua la Grande", paiseCodigoAlfa: "CUB"},
    {ciudad: "San José de las Lajas", paiseCodigoAlfa: "CUB"},
    {ciudad: "Banes", paiseCodigoAlfa: "CUB"},
    {ciudad: "San Luis", paiseCodigoAlfa: "CUB"},
    {ciudad: "Puerto Padre", paiseCodigoAlfa: "CUB"},
    {ciudad: "San Antonio de los Baños", paiseCodigoAlfa: "CUB"},
    {ciudad: "Caibarién", paiseCodigoAlfa: "CUB"},
    {ciudad: "Cabaiguán", paiseCodigoAlfa: "CUB"},
    {ciudad: "Mayarí", paiseCodigoAlfa: "CUB"},
    {ciudad: "San Cristóbal", paiseCodigoAlfa: "CUB"},
    {ciudad: "Vertientes", paiseCodigoAlfa: "CUB"},
    {ciudad: "Jaguey Grande", paiseCodigoAlfa: "CUB"},
    {ciudad: "Consolación del Sur", paiseCodigoAlfa: "CUB"},
    {ciudad: "Jovellanos", paiseCodigoAlfa: "CUB"},
    {ciudad: "Amancio", paiseCodigoAlfa: "CUB"},
    {ciudad: "Guira de Melena", paiseCodigoAlfa: "CUB"},
    {ciudad: "Cumanayagua", paiseCodigoAlfa: "CUB"},
    {ciudad: "Jatibonico", paiseCodigoAlfa: "CUB"},
    {ciudad: "Niquero", paiseCodigoAlfa: "CUB"},
    {ciudad: "San Germán", paiseCodigoAlfa: "CUB"},
    {ciudad: "Sagua de Tánamo", paiseCodigoAlfa: "CUB"},
    {ciudad: "Bauta", paiseCodigoAlfa: "CUB"},
    {ciudad: "La Maya", paiseCodigoAlfa: "CUB"},
    {ciudad: "Guanajay", paiseCodigoAlfa: "CUB"},
    {ciudad: "Colombia", paiseCodigoAlfa: "CUB"},
    {ciudad: "Jiguaní", paiseCodigoAlfa: "CUB"},
    {ciudad: "Manicaragua", paiseCodigoAlfa: "CUB"},
    {ciudad: "Camajuaní", paiseCodigoAlfa: "CUB"},
    {ciudad: "Guisa", paiseCodigoAlfa: "CUB"},
    {ciudad: "Jobabo", paiseCodigoAlfa: "CUB"},
    {ciudad: "Guayas", paiseCodigoAlfa: "ECU"},
    {ciudad: "Pichincha", paiseCodigoAlfa: "ECU"},
    {ciudad: "Azuay", paiseCodigoAlfa: "ECU"},
    {ciudad: "Santo Domingo de los Tsáchilas", paiseCodigoAlfa: "ECU"},
    {ciudad: "El Oro", paiseCodigoAlfa: "ECU"},
    {ciudad: "Manabí", paiseCodigoAlfa: "ECU"},
    {ciudad: "Loja", paiseCodigoAlfa: "ECU"},
    {ciudad: "Tungurahua", paiseCodigoAlfa: "ECU"},
    {ciudad: "Esmeraldas", paiseCodigoAlfa: "ECU"},
    {ciudad: "Los Ríos", paiseCodigoAlfa: "ECU"},
    {ciudad: "Chimborazo", paiseCodigoAlfa: "ECU"},
    {ciudad: "Imbabura", paiseCodigoAlfa: "ECU"},
    {ciudad: "Santa Elena flag.pngSanta Elena", paiseCodigoAlfa: "ECU"},
    {ciudad: "Cotopaxi", paiseCodigoAlfa: "ECU"},
    {ciudad: "Carchi", paiseCodigoAlfa: "ECU"},
    {ciudad: "Sucumbíos", paiseCodigoAlfa: "ECU"},
    {ciudad: "Orellana", paiseCodigoAlfa: "ECU"},
    {ciudad: "Cañar", paiseCodigoAlfa: "ECU"},
    {ciudad: "Pastaza", paiseCodigoAlfa: "ECU"},
    {ciudad: "Bolívar", paiseCodigoAlfa: "ECU"},
    {ciudad: "Napo", paiseCodigoAlfa: "ECU"},
    {ciudad: "Morona Santiago", paiseCodigoAlfa: "ECU"},
    {ciudad: "Zamora Chinchipe", paiseCodigoAlfa: "ECU"},
    {ciudad: "Galápagos", paiseCodigoAlfa: "ECU"},
    {ciudad: "Ciudad de Guatemala", paiseCodigoAlfa: "GTM"},
    {ciudad: "Santa Catarina Pinula", paiseCodigoAlfa: "GTM"},
    {ciudad: "San Miguel Petapa", paiseCodigoAlfa: "GTM"},
    {ciudad: "Mixco", paiseCodigoAlfa: "GTM"},
    {ciudad: "Villa Nueva", paiseCodigoAlfa: "GTM"},
    {ciudad: "Fraijanes", paiseCodigoAlfa: "GTM"},
    {ciudad: "Antigua Guatemala", paiseCodigoAlfa: "GTM"},
    {ciudad: "San Lucas Sacatepéquez", paiseCodigoAlfa: "GTM"},
    {ciudad: "Villa Canales", paiseCodigoAlfa: "GTM"},
    {ciudad: "San José Pinula", paiseCodigoAlfa: "GTM"},
    {ciudad: "Amatitlán", paiseCodigoAlfa: "GTM"},
    {ciudad: "Jocotenango", paiseCodigoAlfa: "GTM"},
    {ciudad: "San Pedro Sacatepéquez", paiseCodigoAlfa: "GTM"},
    {ciudad: "San José del Golfo", paiseCodigoAlfa: "GTM"},
    {ciudad: "Chinautla", paiseCodigoAlfa: "GTM"},
    {ciudad: "San Bartolomé Milpas Altas", paiseCodigoAlfa: "GTM"},
    {ciudad: "Quetzaltenango", paiseCodigoAlfa: "GTM"},
    {ciudad: "Salcajá", paiseCodigoAlfa: "GTM"},
    {ciudad: "San Raymundo", paiseCodigoAlfa: "GTM"},
    {ciudad: "Santa Lucía Milpas Altas", paiseCodigoAlfa: "GTM"},
    {ciudad: "Gonaives", paiseCodigoAlfa: "HTI"},
    {ciudad: "Hinche", paiseCodigoAlfa: "HTI"},
    {ciudad: "Jérémie", paiseCodigoAlfa: "HTI"},
    {ciudad: "Miragoane", paiseCodigoAlfa: "HTI"},
    {ciudad: "Cabo Haitiano", paiseCodigoAlfa: "HTI"},
    {ciudad: "Fuerte Libertad", paiseCodigoAlfa: "HTI"},
    {ciudad: "Port de Paix", paiseCodigoAlfa: "HTI"},
    {ciudad: "Puerto Príncipe", paiseCodigoAlfa: "HTI"},
    {ciudad: "Les Cayes", paiseCodigoAlfa: "HTI"},
    {ciudad: "Jacmel", paiseCodigoAlfa: "HTI"},
    {ciudad: "Distrito Central", paiseCodigoAlfa: "HND"},
    {ciudad: "San Pedro Sula", paiseCodigoAlfa: "HND"},
    {ciudad: "Choloma", paiseCodigoAlfa: "HND"},
    {ciudad: "Danlí", paiseCodigoAlfa: "HND"},
    {ciudad: "La Ceiba", paiseCodigoAlfa: "HND"},
    {ciudad: "El Progreso", paiseCodigoAlfa: "HND"},
    {ciudad: "Villanueva", paiseCodigoAlfa: "HND"},
    {ciudad: "Comayagua", paiseCodigoAlfa: "HND"},
    {ciudad: "Choluteca", paiseCodigoAlfa: "HND"},
    {ciudad: "Juticalpa", paiseCodigoAlfa: "HND"},
    {ciudad: "Puerto Cortés", paiseCodigoAlfa: "HND"},
    {ciudad: "Catacamas", paiseCodigoAlfa: "HND"},
    {ciudad: "Olanchito", paiseCodigoAlfa: "HND"},
    {ciudad: "Tela", paiseCodigoAlfa: "HND"},
    {ciudad: "Tocoa", paiseCodigoAlfa: "HND"},
    {ciudad: "Ciudad de México", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tijuana", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Cristóbal Ecatepec", paiseCodigoAlfa: "MEX"},
    {ciudad: "León", paiseCodigoAlfa: "MEX"},
    {ciudad: "Puebla de Zaragoza", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ciudad Juárez", paiseCodigoAlfa: "MEX"},
    {ciudad: "Guadalajara", paiseCodigoAlfa: "MEX"},
    {ciudad: "Zapopan", paiseCodigoAlfa: "MEX"},
    {ciudad: "Monterrey", paiseCodigoAlfa: "MEX"},
    {ciudad: "Nezahualcóyotl", paiseCodigoAlfa: "MEX"},
    {ciudad: "Chihuahua", paiseCodigoAlfa: "MEX"},
    {ciudad: "Mérida", paiseCodigoAlfa: "MEX"},
    {ciudad: "Cancún", paiseCodigoAlfa: "MEX"},
    {ciudad: "Saltillo", paiseCodigoAlfa: "MEX"},
    {ciudad: "Aguascalientes", paiseCodigoAlfa: "MEX"},
    {ciudad: "Hermosillo", paiseCodigoAlfa: "MEX"},
    {ciudad: "Mexicali", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Luis Potosí", paiseCodigoAlfa: "MEX"},
    {ciudad: "Culiacán Rosales", paiseCodigoAlfa: "MEX"},
    {ciudad: "Santiago de Querétaro", paiseCodigoAlfa: "MEX"},
    {ciudad: "Naucalpan de Juárez", paiseCodigoAlfa: "MEX"},
    {ciudad: "Morelia", paiseCodigoAlfa: "MEX"},
    {ciudad: "Chimalhuacán", paiseCodigoAlfa: "MEX"},
    {ciudad: "Reynosa", paiseCodigoAlfa: "MEX"},
    {ciudad: "Torreón", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tlalnepantla de Baz", paiseCodigoAlfa: "MEX"},
    {ciudad: "Acapulco de Juárez", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tlaquepaque", paiseCodigoAlfa: "MEX"},
    {ciudad: "Guadalupe", paiseCodigoAlfa: "MEX"},
    {ciudad: "Victoria de Durango", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tuxtla Gutiérrez", paiseCodigoAlfa: "MEX"},
    {ciudad: "Apodaca", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ciudad López Mateos", paiseCodigoAlfa: "MEX"},
    {ciudad: "Cuautitlán Izcalli", paiseCodigoAlfa: "MEX"},
    {ciudad: "Heroica Matamoros", paiseCodigoAlfa: "MEX"},
    {ciudad: "General Escobedo", paiseCodigoAlfa: "MEX"},
    {ciudad: "Irapuato", paiseCodigoAlfa: "MEX"},
    {ciudad: "Xalapa", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tonalá", paiseCodigoAlfa: "MEX"},
    {ciudad: "Mazatlán", paiseCodigoAlfa: "MEX"},
    {ciudad: "Nuevo Laredo", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Nicolás de los Garza", paiseCodigoAlfa: "MEX"},
    {ciudad: "Veracruz", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ojo de Agua", paiseCodigoAlfa: "MEX"},
    {ciudad: "Xico", paiseCodigoAlfa: "MEX"},
    {ciudad: "Celaya", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tepic", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ixtapaluca", paiseCodigoAlfa: "MEX"},
    {ciudad: "Cuernavaca", paiseCodigoAlfa: "MEX"},
    {ciudad: "Villahermosa", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ciudad Victoria", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ensenada", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ciudad Obregón", paiseCodigoAlfa: "MEX"},
    {ciudad: "Villa Nicolás Romero", paiseCodigoAlfa: "MEX"},
    {ciudad: "Soledad de Graciano Sánchez", paiseCodigoAlfa: "MEX"},
    {ciudad: "Juárez", paiseCodigoAlfa: "MEX"},
    {ciudad: "Playa del Carmen", paiseCodigoAlfa: "MEX"},
    {ciudad: "Santa Catarina", paiseCodigoAlfa: "MEX"},
    {ciudad: "Gómez Palacio", paiseCodigoAlfa: "MEX"},
    {ciudad: "Uruapan", paiseCodigoAlfa: "MEX"},
    {ciudad: "Los Mochis", paiseCodigoAlfa: "MEX"},
    {ciudad: "Pachuca de Soto", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tampico", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tehuacán", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Francisco Coacalco", paiseCodigoAlfa: "MEX"},
    {ciudad: "Salamanca", paiseCodigoAlfa: "MEX"},
    {ciudad: "Heroica Nogales", paiseCodigoAlfa: "MEX"},
    {ciudad: "Oaxaca de Juárez", paiseCodigoAlfa: "MEX"},
    {ciudad: "La Paz", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Francisco de Campeche", paiseCodigoAlfa: "MEX"},
    {ciudad: "Monclova", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Pedro Garza García", paiseCodigoAlfa: "MEX"},
    {ciudad: "Chilpancingo de los Bravo", paiseCodigoAlfa: "MEX"},
    {ciudad: "Puerto Vallarta", paiseCodigoAlfa: "MEX"},
    {ciudad: "Toluca de Lerdo", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tapachula", paiseCodigoAlfa: "MEX"},
    {ciudad: "Buenavista", paiseCodigoAlfa: "MEX"},
    {ciudad: "Coatzacoalcos", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ciudad Madero", paiseCodigoAlfa: "MEX"},
    {ciudad: "Cabo San Lucas", paiseCodigoAlfa: "MEX"},
    {ciudad: "Guanajuato", paiseCodigoAlfa: "MEX"},
    {ciudad: "Chicoloapan", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ciudad del Carmen", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Cristóbal de las Casas", paiseCodigoAlfa: "MEX"},
    {ciudad: "Poza Rica de Hidalgo", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Juan del Río", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Luis Río Colorado", paiseCodigoAlfa: "MEX"},
    {ciudad: "Chalco de Díaz Covarrubias", paiseCodigoAlfa: "MEX"},
    {ciudad: "Jiutepec", paiseCodigoAlfa: "MEX"},
    {ciudad: "Piedras Negras", paiseCodigoAlfa: "MEX"},
    {ciudad: "Chetumal", paiseCodigoAlfa: "MEX"},
    {ciudad: "Miramar", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ciudad Acuña", paiseCodigoAlfa: "MEX"},
    {ciudad: "Manzanillo", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Pablo de las Salinas", paiseCodigoAlfa: "MEX"},
    {ciudad: "Cuautla de Morelos", paiseCodigoAlfa: "MEX"},
    {ciudad: "Zamora", paiseCodigoAlfa: "MEX"},
    {ciudad: "Villa de Álvarez", paiseCodigoAlfa: "MEX"},
    {ciudad: "Colima", paiseCodigoAlfa: "MEX"},
    {ciudad: "Fresnillo", paiseCodigoAlfa: "MEX"},
    {ciudad: "Kanasín", paiseCodigoAlfa: "MEX"},
    {ciudad: "Córdoba", paiseCodigoAlfa: "MEX"},
    {ciudad: "Zacatecas", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ciudad Valles", paiseCodigoAlfa: "MEX"},
    {ciudad: "San José del Cabo", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ciudad Cuauhtémoc", paiseCodigoAlfa: "MEX"},
    {ciudad: "Naucalpan", paiseCodigoAlfa: "MEX"},
    {ciudad: "Iguala", paiseCodigoAlfa: "MEX"},
    {ciudad: "Delicias", paiseCodigoAlfa: "MEX"},
    {ciudad: "Navojoa", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tepexpan", paiseCodigoAlfa: "MEX"},
    {ciudad: "Orizaba", paiseCodigoAlfa: "MEX"},
    {ciudad: "Cuautitlán", paiseCodigoAlfa: "MEX"},
    {ciudad: "Guaymas", paiseCodigoAlfa: "MEX"},
    {ciudad: "El Pueblito", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ramos Arizpe", paiseCodigoAlfa: "MEX"},
    {ciudad: "Hidalgo del Parral", paiseCodigoAlfa: "MEX"},
    {ciudad: "Comitán de Domínguez", paiseCodigoAlfa: "MEX"},
    {ciudad: "Ciudad Guzmán", paiseCodigoAlfa: "MEX"},
    {ciudad: "Lagos de Moreno", paiseCodigoAlfa: "MEX"},
    {ciudad: "Río Bravo", paiseCodigoAlfa: "MEX"},
    {ciudad: "Tulancingo de Bravo", paiseCodigoAlfa: "MEX"},
    {ciudad: "Temixco", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Juan Bautista Tuxtepec", paiseCodigoAlfa: "MEX"},
    {ciudad: "Apatzingán", paiseCodigoAlfa: "MEX"},
    {ciudad: "San Andrés Cholula", paiseCodigoAlfa: "MEX"},
    {ciudad: "Minatitlán", paiseCodigoAlfa: "MEX"},
    {ciudad: "Playas de Rosarito", paiseCodigoAlfa: "MEX"},
    {ciudad: "Boaco", paiseCodigoAlfa: "NIC"},
    {ciudad: "Jinotepe", paiseCodigoAlfa: "NIC"},
    {ciudad: "Chinandega", paiseCodigoAlfa: "NIC"},
    {ciudad: "Juigalpa", paiseCodigoAlfa: "NIC"},
    {ciudad: "Puerto Cabezas", paiseCodigoAlfa: "NIC"},
    {ciudad: "Bluefields", paiseCodigoAlfa: "NIC"},
    {ciudad: "Estelí", paiseCodigoAlfa: "NIC"},
    {ciudad: "Granada", paiseCodigoAlfa: "NIC"},
    {ciudad: "Jinotega", paiseCodigoAlfa: "NIC"},
    {ciudad: "León", paiseCodigoAlfa: "NIC"},
    {ciudad: "Somoto", paiseCodigoAlfa: "NIC"},
    {ciudad: "Managua", paiseCodigoAlfa: "NIC"},
    {ciudad: "Masaya", paiseCodigoAlfa: "NIC"},
    {ciudad: "Matagalpa", paiseCodigoAlfa: "NIC"},
    {ciudad: "Ocotal", paiseCodigoAlfa: "NIC"},
    {ciudad: "San Carlos", paiseCodigoAlfa: "NIC"},
    {ciudad: "Rivas", paiseCodigoAlfa: "NIC"},
    {ciudad: "Panamá", paiseCodigoAlfa: "PAN"},
    {ciudad: "Colón", paiseCodigoAlfa: "PAN"},
    {ciudad: "David", paiseCodigoAlfa: "PAN"},
    {ciudad: "La Chorrera", paiseCodigoAlfa: "PAN"},
    {ciudad: "Santiago", paiseCodigoAlfa: "PAN"},
    {ciudad: "Changuinola", paiseCodigoAlfa: "PAN"},
    {ciudad: "Penonomé", paiseCodigoAlfa: "PAN"},
    {ciudad: "Bugaba", paiseCodigoAlfa: "PAN"},
    {ciudad: "Puerto Armuelles", paiseCodigoAlfa: "PAN"},
    {ciudad: "Antón", paiseCodigoAlfa: "PAN"},
    {ciudad: "Chepo", paiseCodigoAlfa: "PAN"},
    {ciudad: "Chitré", paiseCodigoAlfa: "PAN"},
    {ciudad: "Aguadulce", paiseCodigoAlfa: "PAN"},
    {ciudad: "Capira", paiseCodigoAlfa: "PAN"},
    {ciudad: "Chame", paiseCodigoAlfa: "PAN"},
    {ciudad: "Soná", paiseCodigoAlfa: "PAN"},
    {ciudad: "Almirante", paiseCodigoAlfa: "PAN"},
    {ciudad: "La Pintada", paiseCodigoAlfa: "PAN"},
    {ciudad: "Las Tablas", paiseCodigoAlfa: "PAN"},
    {ciudad: "La Villa de Los Santos", paiseCodigoAlfa: "PAN"},
    {ciudad: "Asunción", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ciudad del Este", paiseCodigoAlfa: "PRY"},
    {ciudad: "Luque", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Lorenzo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Capiatá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Lambaré", paiseCodigoAlfa: "PRY"},
    {ciudad: "Fernando de la Mora", paiseCodigoAlfa: "PRY"},
    {ciudad: "Limpio", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ñemby", paiseCodigoAlfa: "PRY"},
    {ciudad: "Encarnación", paiseCodigoAlfa: "PRY"},
    {ciudad: "Caaguazú", paiseCodigoAlfa: "PRY"},
    {ciudad: "Coronel Oviedo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Pedro Juan Caballero", paiseCodigoAlfa: "PRY"},
    {ciudad: "Itauguá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Presidente Franco", paiseCodigoAlfa: "PRY"},
    {ciudad: "Mariano Roque Alonso", paiseCodigoAlfa: "PRY"},
    {ciudad: "Minga Guazú", paiseCodigoAlfa: "PRY"},
    {ciudad: "Concepción", paiseCodigoAlfa: "PRY"},
    {ciudad: "Itá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Villa Elisa", paiseCodigoAlfa: "PRY"},
    {ciudad: "Hernandarias", paiseCodigoAlfa: "PRY"},
    {ciudad: "Areguá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Villarrica", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Antonio", paiseCodigoAlfa: "PRY"},
    {ciudad: "Horqueta", paiseCodigoAlfa: "PRY"},
    {ciudad: "Cambyretá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Curuguaty", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ypané", paiseCodigoAlfa: "PRY"},
    {ciudad: "Caacupé", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Estanislao", paiseCodigoAlfa: "PRY"},
    {ciudad: "Julián Augusto Saldívar", paiseCodigoAlfa: "PRY"},
    {ciudad: "Villa Hayes", paiseCodigoAlfa: "PRY"},
    {ciudad: "Capiibary", paiseCodigoAlfa: "PRY"},
    {ciudad: "Santa Rosa del Aguaray", paiseCodigoAlfa: "PRY"},
    {ciudad: "Villeta", paiseCodigoAlfa: "PRY"},
    {ciudad: "Salto del Guairá", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Juan Nepomuceno", paiseCodigoAlfa: "PRY"},
    {ciudad: "Guarambaré", paiseCodigoAlfa: "PRY"},
    {ciudad: "Doctor Juan Eulogio Estigarribia", paiseCodigoAlfa: "PRY"},
    {ciudad: "Itakyry", paiseCodigoAlfa: "PRY"},
    {ciudad: "Carapeguá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Santa Rita", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Pedro de Ycuamandiyú", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Ignacio Guazú", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yhú", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yby Yaú", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Pedro del Paraná", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tobatí", paiseCodigoAlfa: "PRY"},
    {ciudad: "Repatriación", paiseCodigoAlfa: "PRY"},
    {ciudad: "Pilar", paiseCodigoAlfa: "PRY"},
    {ciudad: "Abaí", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yaguarón", paiseCodigoAlfa: "PRY"},
    {ciudad: "Guayaibí", paiseCodigoAlfa: "PRY"},
    {ciudad: "Piribebuy", paiseCodigoAlfa: "PRY"},
    {ciudad: "Mariscal José Félix Estigarribia", paiseCodigoAlfa: "PRY"},
    {ciudad: "Choré", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tomás Romero Pereira", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ypacaraí", paiseCodigoAlfa: "PRY"},
    {ciudad: "Teniente Primero Manuel Irala Fernández", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yasy Cañy", paiseCodigoAlfa: "PRY"},
    {ciudad: "Independencia", paiseCodigoAlfa: "PRY"},
    {ciudad: "Paso Yobái", paiseCodigoAlfa: "PRY"},
    {ciudad: "Juan Emiliano O Leary", paiseCodigoAlfa: "PRY"},
    {ciudad: "Caazapá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Arroyos y Esteros", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ybycuí", paiseCodigoAlfa: "PRY"},
    {ciudad: "Liberación", paiseCodigoAlfa: "PRY"},
    {ciudad: "Doctor Juan Manuel Frutos", paiseCodigoAlfa: "PRY"},
    {ciudad: "General Isidoro Resquín", paiseCodigoAlfa: "PRY"},
    {ciudad: "Eusebio Ayala", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Juan Bautista", paiseCodigoAlfa: "PRY"},
    {ciudad: "Edelira", paiseCodigoAlfa: "PRY"},
    {ciudad: "Paraguarí", paiseCodigoAlfa: "PRY"},
    {ciudad: "General Elizardo Aquino", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yuty", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Rafael del Paraná", paiseCodigoAlfa: "PRY"},
    {ciudad: "Doctor Juan León Mallorquín", paiseCodigoAlfa: "PRY"},
    {ciudad: "Quiindy", paiseCodigoAlfa: "PRY"},
    {ciudad: "Coronel José Félix Bogado", paiseCodigoAlfa: "PRY"},
    {ciudad: "Benjamín Aceval", paiseCodigoAlfa: "PRY"},
    {ciudad: "Natalio", paiseCodigoAlfa: "PRY"},
    {ciudad: "Emboscada", paiseCodigoAlfa: "PRY"},
    {ciudad: "San José de los Arroyos", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tres de Mayo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Carlos Antonio López", paiseCodigoAlfa: "PRY"},
    {ciudad: "Filadelfia", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ayolas", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tavaí", paiseCodigoAlfa: "PRY"},
    {ciudad: "Capitán Bado", paiseCodigoAlfa: "PRY"},
    {ciudad: "Loreto", paiseCodigoAlfa: "PRY"},
    {ciudad: "Santa Rosa de Lima", paiseCodigoAlfa: "PRY"},
    {ciudad: "Alto Verá", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Joaquín", paiseCodigoAlfa: "PRY"},
    {ciudad: "Pirayú", paiseCodigoAlfa: "PRY"},
    {ciudad: "Bella Vista Norte", paiseCodigoAlfa: "PRY"},
    {ciudad: "Villa Ygatimí", paiseCodigoAlfa: "PRY"},
    {ciudad: "Obligado", paiseCodigoAlfa: "PRY"},
    {ciudad: "Raúl Arsenio Oviedo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Loma Plata", paiseCodigoAlfa: "PRY"},
    {ciudad: "Atyrá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Itapúa Poty", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yrybucuá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tacuatí", paiseCodigoAlfa: "PRY"},
    {ciudad: "Acahay", paiseCodigoAlfa: "PRY"},
    {ciudad: "Carayaó", paiseCodigoAlfa: "PRY"},
    {ciudad: "Hohenau", paiseCodigoAlfa: "PRY"},
    {ciudad: "Mayor Otaño", paiseCodigoAlfa: "PRY"},
    {ciudad: "Minga Porá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Bella Vista", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tembiaporá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Capitán Meza", paiseCodigoAlfa: "PRY"},
    {ciudad: "Altos", paiseCodigoAlfa: "PRY"},
    {ciudad: "Mbuyapey", paiseCodigoAlfa: "PRY"},
    {ciudad: "Capitán Miranda", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ybyrarobaná", paiseCodigoAlfa: "PRY"},
    {ciudad: "Caraguatay", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yatytay", paiseCodigoAlfa: "PRY"},
    {ciudad: "Belén", paiseCodigoAlfa: "PRY"},
    {ciudad: "General Artigas", paiseCodigoAlfa: "PRY"},
    {ciudad: "Santa Rosa del Mbutuy", paiseCodigoAlfa: "PRY"},
    {ciudad: "Nueva Esperanza", paiseCodigoAlfa: "PRY"},
    {ciudad: "Nueva Italia", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Roque González de Santa Cruz", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yataity del Norte", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Bernardino", paiseCodigoAlfa: "PRY"},
    {ciudad: "Lima", paiseCodigoAlfa: "PRY"},
    {ciudad: "Puerto Pinasco", paiseCodigoAlfa: "PRY"},
    {ciudad: "General Francisco Caballero Álvarez", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Lázaro", paiseCodigoAlfa: "PRY"},
    {ciudad: "Vaquería", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yby Pytá", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Alberto", paiseCodigoAlfa: "PRY"},
    {ciudad: "Itacurubí del Rosario", paiseCodigoAlfa: "PRY"},
    {ciudad: "José Domingo Ocampos", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yguazú", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Cristóbal", paiseCodigoAlfa: "PRY"},
    {ciudad: "Capitán Mauricio José Troche", paiseCodigoAlfa: "PRY"},
    {ciudad: "Itacurubí de la Cordillera", paiseCodigoAlfa: "PRY"},
    {ciudad: "Fram", paiseCodigoAlfa: "PRY"},
    {ciudad: "Villa del Rosario", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Cosme y Damián", paiseCodigoAlfa: "PRY"},
    {ciudad: "Borja", paiseCodigoAlfa: "PRY"},
    {ciudad: "Los Cedrales", paiseCodigoAlfa: "PRY"},
    {ciudad: "25 de Diciembre", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tres de Febrero", paiseCodigoAlfa: "PRY"},
    {ciudad: "Trinidad", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Juan del Paraná", paiseCodigoAlfa: "PRY"},
    {ciudad: "Corpus Christi", paiseCodigoAlfa: "PRY"},
    {ciudad: "Doctor Raúl Peña", paiseCodigoAlfa: "PRY"},
    {ciudad: "Regimiento de Infantería Tres Corrales", paiseCodigoAlfa: "PRY"},
    {ciudad: "Alberdi", paiseCodigoAlfa: "PRY"},
    {ciudad: "Pirapó", paiseCodigoAlfa: "PRY"},
    {ciudad: "Azotey", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ñacunday", paiseCodigoAlfa: "PRY"},
    {ciudad: "Carmen del Paraná", paiseCodigoAlfa: "PRY"},
    {ciudad: "Santa María de Fe", paiseCodigoAlfa: "PRY"},
    {ciudad: "La Paloma del Espíritu Santo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Mbocayaty del Guairá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ypejhú", paiseCodigoAlfa: "PRY"},
    {ciudad: "Iturbe", paiseCodigoAlfa: "PRY"},
    {ciudad: "Katueté", paiseCodigoAlfa: "PRY"},
    {ciudad: "Mbaracayú", paiseCodigoAlfa: "PRY"},
    {ciudad: "Escobar", paiseCodigoAlfa: "PRY"},
    {ciudad: "General Eugenio Alejandrino Garay", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tavapy", paiseCodigoAlfa: "PRY"},
    {ciudad: "Caapucú", paiseCodigoAlfa: "PRY"},
    {ciudad: "Doctor Cecilio Báez", paiseCodigoAlfa: "PRY"},
    {ciudad: "General Delgado", paiseCodigoAlfa: "PRY"},
    {ciudad: "Zanja Pytá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Isla Pucú", paiseCodigoAlfa: "PRY"},
    {ciudad: "Itapé", paiseCodigoAlfa: "PRY"},
    {ciudad: "Nueva Alborada", paiseCodigoAlfa: "PRY"},
    {ciudad: "Santa Rosa del Monday", paiseCodigoAlfa: "PRY"},
    {ciudad: "Quyquyhó", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ybytymí", paiseCodigoAlfa: "PRY"},
    {ciudad: "Nueva Germania", paiseCodigoAlfa: "PRY"},
    {ciudad: "Coronel Martínez", paiseCodigoAlfa: "PRY"},
    {ciudad: "General Bernardino Caballero", paiseCodigoAlfa: "PRY"},
    {ciudad: "Unión", paiseCodigoAlfa: "PRY"},
    {ciudad: "Sargento José Félix López", paiseCodigoAlfa: "PRY"},
    {ciudad: "Mariscal Francisco Solano López", paiseCodigoAlfa: "PRY"},
    {ciudad: "Valenzuela", paiseCodigoAlfa: "PRY"},
    {ciudad: "Juan de Mena", paiseCodigoAlfa: "PRY"},
    {ciudad: "José A. Fassardi", paiseCodigoAlfa: "PRY"},
    {ciudad: "Fulgencio Yegros", paiseCodigoAlfa: "PRY"},
    {ciudad: "Sapucai", paiseCodigoAlfa: "PRY"},
    {ciudad: "Puerto Casado", paiseCodigoAlfa: "PRY"},
    {ciudad: "Primero de Marzo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Santiago", paiseCodigoAlfa: "PRY"},
    {ciudad: "Simón Bolívar", paiseCodigoAlfa: "PRY"},
    {ciudad: "Félix Pérez Cardozo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Jesús", paiseCodigoAlfa: "PRY"},
    {ciudad: "General Higinio Morínigo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Iruña", paiseCodigoAlfa: "PRY"},
    {ciudad: "Buena Vista", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Miguel", paiseCodigoAlfa: "PRY"},
    {ciudad: "Nanawa", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Juan Bautista del Ñeembucú", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Alfredo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Naranjal", paiseCodigoAlfa: "PRY"},
    {ciudad: "Doctor Moisés Santiago Bertoni", paiseCodigoAlfa: "PRY"},
    {ciudad: "La Colmena", paiseCodigoAlfa: "PRY"},
    {ciudad: "Cerrito", paiseCodigoAlfa: "PRY"},
    {ciudad: "Domingo Martínez de Irala", paiseCodigoAlfa: "PRY"},
    {ciudad: "Karapaí", paiseCodigoAlfa: "PRY"},
    {ciudad: "La Pastora", paiseCodigoAlfa: "PRY"},
    {ciudad: "Natalicio Talavera", paiseCodigoAlfa: "PRY"},
    {ciudad: "Nueva Toledo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Santa Elena", paiseCodigoAlfa: "PRY"},
    {ciudad: "Nueva Londres", paiseCodigoAlfa: "PRY"},
    {ciudad: "Maciel", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yataity del Guairá", paiseCodigoAlfa: "PRY"},
    {ciudad: "José Leandro Oviedo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tebicuarymí", paiseCodigoAlfa: "PRY"},
    {ciudad: "Capitán Carmelo Peralta", paiseCodigoAlfa: "PRY"},
    {ciudad: "Fuerte Olimpo", paiseCodigoAlfa: "PRY"},
    {ciudad: "San José Obrero", paiseCodigoAlfa: "PRY"},
    {ciudad: "Antequera", paiseCodigoAlfa: "PRY"},
    {ciudad: "Mayor José Martínez", paiseCodigoAlfa: "PRY"},
    {ciudad: "José Falcón", paiseCodigoAlfa: "PRY"},
    {ciudad: "Mbocayaty del Yhaguy", paiseCodigoAlfa: "PRY"},
    {ciudad: "Paso Barreto", paiseCodigoAlfa: "PRY"},
    {ciudad: "Santa Fe del Paraná", paiseCodigoAlfa: "PRY"},
    {ciudad: "General José Eduvigis Díaz", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tacuaras", paiseCodigoAlfa: "PRY"},
    {ciudad: "Nueva Colombia", paiseCodigoAlfa: "PRY"},
    {ciudad: "Villa Oliva", paiseCodigoAlfa: "PRY"},
    {ciudad: "Villa Florida", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Patricio", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Pablo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Loma Grande", paiseCodigoAlfa: "PRY"},
    {ciudad: "Laureles", paiseCodigoAlfa: "PRY"},
    {ciudad: "Teniente Esteban Martínez", paiseCodigoAlfa: "PRY"},
    {ciudad: "Itanará", paiseCodigoAlfa: "PRY"},
    {ciudad: "Ñumí", paiseCodigoAlfa: "PRY"},
    {ciudad: "General José María Bruguez", paiseCodigoAlfa: "PRY"},
    {ciudad: "La Paz", paiseCodigoAlfa: "PRY"},
    {ciudad: "Tebicuary", paiseCodigoAlfa: "PRY"},
    {ciudad: "Humaitá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Isla Umbú", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Salvador", paiseCodigoAlfa: "PRY"},
    {ciudad: "Yabebyry", paiseCodigoAlfa: "PRY"},
    {ciudad: "Bahía Negra", paiseCodigoAlfa: "PRY"},
    {ciudad: "Villalbín", paiseCodigoAlfa: "PRY"},
    {ciudad: "Guazú Cuá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Paso de Patria", paiseCodigoAlfa: "PRY"},
    {ciudad: "Desmochados", paiseCodigoAlfa: "PRY"},
    {ciudad: "Doctor Bottrell", paiseCodigoAlfa: "PRY"},
    {ciudad: "Villa Franca", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Carlos del Apa", paiseCodigoAlfa: "PRY"},
    {ciudad: "Maracaná", paiseCodigoAlfa: "PRY"},
    {ciudad: "María Antonia", paiseCodigoAlfa: "PRY"},
    {ciudad: "San Vicente Pancholo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Arroyito", paiseCodigoAlfa: "PRY"},
    {ciudad: "Puerto Adela", paiseCodigoAlfa: "PRY"},
    {ciudad: "Paso Horqueta", paiseCodigoAlfa: "PRY"},
    {ciudad: "Cerro Corá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Campo Aceval", paiseCodigoAlfa: "PRY"},
    {ciudad: "Laurel", paiseCodigoAlfa: "PRY"},
    {ciudad: "Itacuá", paiseCodigoAlfa: "PRY"},
    {ciudad: "Puerto Ybapobo", paiseCodigoAlfa: "PRY"},
    {ciudad: "Neuland", paiseCodigoAlfa: "PRY"},
    {ciudad: "Lima", paiseCodigoAlfa: "PER"},
    {ciudad: "Arequipa", paiseCodigoAlfa: "PER"},
    {ciudad: "Callao", paiseCodigoAlfa: "PER"},
    {ciudad: "Trujillo", paiseCodigoAlfa: "PER"},
    {ciudad: "Chiclayo", paiseCodigoAlfa: "PER"},
    {ciudad: "Piura", paiseCodigoAlfa: "PER"},
    {ciudad: "Huancayo", paiseCodigoAlfa: "PER"},
    {ciudad: "Cuzco", paiseCodigoAlfa: "PER"},
    {ciudad: "Chimbote", paiseCodigoAlfa: "PER"},
    {ciudad: "Iquitos", paiseCodigoAlfa: "PER"},
    {ciudad: "Pucallpa", paiseCodigoAlfa: "PER"},
    {ciudad: "Tacna", paiseCodigoAlfa: "PER"},
    {ciudad: "Ica", paiseCodigoAlfa: "PER"},
    {ciudad: "Juliaca", paiseCodigoAlfa: "PER"},
    {ciudad: "Ayacucho", paiseCodigoAlfa: "PER"},
    {ciudad: "Cajamarca", paiseCodigoAlfa: "PER"},
    {ciudad: "Huánuco", paiseCodigoAlfa: "PER"},
    {ciudad: "Tarapoto", paiseCodigoAlfa: "PER"},
    {ciudad: "Chincha Alta", paiseCodigoAlfa: "PER"},
    {ciudad: "Huacho", paiseCodigoAlfa: "PER"},
    {ciudad: "Sullana", paiseCodigoAlfa: "PER"},
    {ciudad: "Puno", paiseCodigoAlfa: "PER"},
    {ciudad: "Huaraz", paiseCodigoAlfa: "PER"},
    {ciudad: "Huaral", paiseCodigoAlfa: "PER"},
    {ciudad: "Tumbes", paiseCodigoAlfa: "PER"},
    {ciudad: "Jaén", paiseCodigoAlfa: "PER"},
    {ciudad: "Cañete", paiseCodigoAlfa: "PER"},
    {ciudad: "Talara", paiseCodigoAlfa: "PER"},
    {ciudad: "Paita", paiseCodigoAlfa: "PER"},
    {ciudad: "Puerto Maldonado", paiseCodigoAlfa: "PER"},
    {ciudad: "Yurimaguas", paiseCodigoAlfa: "PER"},
    {ciudad: "Chulucanas", paiseCodigoAlfa: "PER"},
    {ciudad: "Catacaos", paiseCodigoAlfa: "PER"},
    {ciudad: "Pisco", paiseCodigoAlfa: "PER"},
    {ciudad: "Abancay", paiseCodigoAlfa: "PER"},
    {ciudad: "Lambayeque", paiseCodigoAlfa: "PER"},
    {ciudad: "Huaura", paiseCodigoAlfa: "PER"},
    {ciudad: "Moquegua", paiseCodigoAlfa: "PER"},
    {ciudad: "Huanchaco", paiseCodigoAlfa: "PER"},
    {ciudad: "Barranca", paiseCodigoAlfa: "PER"},
    {ciudad: "Ilo", paiseCodigoAlfa: "PER"},
    {ciudad: "San Miguel", paiseCodigoAlfa: "PER"},
    {ciudad: "Majes", paiseCodigoAlfa: "PER"},
    {ciudad: "Cerro de Pasco", paiseCodigoAlfa: "PER"},
    {ciudad: "Andahuaylas", paiseCodigoAlfa: "PER"},
    {ciudad: "Sicuani", paiseCodigoAlfa: "PER"},
    {ciudad: "Chancay", paiseCodigoAlfa: "PER"},
    {ciudad: "Tingo María", paiseCodigoAlfa: "PER"},
    {ciudad: "Moyobamba", paiseCodigoAlfa: "PER"},
    {ciudad: "Huancavelica", paiseCodigoAlfa: "PER"},
    {ciudad: "Distrito Nacional", paiseCodigoAlfa: "DOM"},
    {ciudad: "Santo Domingo Este", paiseCodigoAlfa: "DOM"},
    {ciudad: "Santiago de los Caballeros", paiseCodigoAlfa: "DOM"},
    {ciudad: "Santo Domingo Norte", paiseCodigoAlfa: "DOM"},
    {ciudad: "Santo Domingo Oeste", paiseCodigoAlfa: "DOM"},
    {ciudad: "Higuey", paiseCodigoAlfa: "DOM"},
    {ciudad: "San Luis", paiseCodigoAlfa: "DOM"},
    {ciudad: "San Felipe de Puerto Plata", paiseCodigoAlfa: "DOM"},
    {ciudad: "San Cristóbal", paiseCodigoAlfa: "DOM"},
    {ciudad: "San Pedro de Macoris", paiseCodigoAlfa: "DOM"},
    {ciudad: "Los Alcarrizos", paiseCodigoAlfa: "DOM"},
    {ciudad: "La Vega", paiseCodigoAlfa: "DOM"},
    {ciudad: "San Francisco de Macorís", paiseCodigoAlfa: "DOM"},
    {ciudad: "La Romana", paiseCodigoAlfa: "DOM"},
    {ciudad: "Moca", paiseCodigoAlfa: "DOM"},
    {ciudad: "Villa Altagracia", paiseCodigoAlfa: "DOM"},
    {ciudad: "San Juan de La Maguana", paiseCodigoAlfa: "DOM"},
    {ciudad: "Haina", paiseCodigoAlfa: "DOM"},
    {ciudad: "Bonao", paiseCodigoAlfa: "DOM"},
    {ciudad: "Cotuí", paiseCodigoAlfa: "DOM"},
    {ciudad: "Baní", paiseCodigoAlfa: "DOM"},
    {ciudad: "Santa Cruz de Barahona", paiseCodigoAlfa: "DOM"},
    {ciudad: "Azua de Compostela", paiseCodigoAlfa: "DOM"},
    {ciudad: "Boca Chica", paiseCodigoAlfa: "DOM"},
    {ciudad: "Villa hermosa", paiseCodigoAlfa: "DOM"},
    {ciudad: "Mao", paiseCodigoAlfa: "DOM"},
    {ciudad: "Pedro Brand", paiseCodigoAlfa: "DOM"},
    {ciudad: "San Antonio de Guerra", paiseCodigoAlfa: "DOM"},
    {ciudad: "San Ignacio de Sabaneta", paiseCodigoAlfa: "DOM"},
    {ciudad: "Santa Cruz del Seibo", paiseCodigoAlfa: "DOM"},
    {ciudad: "Tamboril", paiseCodigoAlfa: "DOM"},
    {ciudad: "Nagua", paiseCodigoAlfa: "DOM"},
    {ciudad: "Puñal", paiseCodigoAlfa: "DOM"},
    {ciudad: "Hato Mayor del Rey", paiseCodigoAlfa: "DOM"},
    {ciudad: "Esperanza", paiseCodigoAlfa: "DOM"},
    {ciudad: "Sosúa", paiseCodigoAlfa: "DOM"},
    {ciudad: "Jarabacoa", paiseCodigoAlfa: "DOM"},
    {ciudad: "San José de las Matas", paiseCodigoAlfa: "DOM"},
    {ciudad: "Yamasá", paiseCodigoAlfa: "DOM"},
    {ciudad: "Monte Plata", paiseCodigoAlfa: "DOM"},
    {ciudad: "Villa González", paiseCodigoAlfa: "DOM"},
    {ciudad: "Montevideo", paiseCodigoAlfa: "URY"},
    {ciudad: "Ciudad de la Costa", paiseCodigoAlfa: "URY"},
    {ciudad: "Salto", paiseCodigoAlfa: "URY"},
    {ciudad: "Paysandú", paiseCodigoAlfa: "URY"},
    {ciudad: "Maldonado", paiseCodigoAlfa: "URY"},
    {ciudad: "Rivera", paiseCodigoAlfa: "URY"},
    {ciudad: "Las Piedras", paiseCodigoAlfa: "URY"},
    {ciudad: "Tacuarembó", paiseCodigoAlfa: "URY"},
    {ciudad: "Melo", paiseCodigoAlfa: "URY"},
    {ciudad: "Artigas", paiseCodigoAlfa: "URY"},
    {ciudad: "Mercedes", paiseCodigoAlfa: "URY"},
    {ciudad: "Minas", paiseCodigoAlfa: "URY"},
    {ciudad: "San José de Mayo", paiseCodigoAlfa: "URY"},
    {ciudad: "Durazno", paiseCodigoAlfa: "URY"},
    {ciudad: "Florida", paiseCodigoAlfa: "URY"},
    {ciudad: "Treinta y Tres", paiseCodigoAlfa: "URY"},
    {ciudad: "Barros Blancos", paiseCodigoAlfa: "URY"},
    {ciudad: "Ciudad del Plata", paiseCodigoAlfa: "URY"},
    {ciudad: "San Carlos", paiseCodigoAlfa: "URY"},
    {ciudad: "Colonia del Sacramento", paiseCodigoAlfa: "URY"},
    {ciudad: "Pando", paiseCodigoAlfa: "URY"},
    {ciudad: "Rocha", paiseCodigoAlfa: "URY"},
    {ciudad: "Fray Bentos", paiseCodigoAlfa: "URY"},
    {ciudad: "Salinas", paiseCodigoAlfa: "URY"},
    {ciudad: "Trinidad", paiseCodigoAlfa: "URY"},
    {ciudad: "18 de Mayo", paiseCodigoAlfa: "URY"},
    {ciudad: "La Paz", paiseCodigoAlfa: "URY"},
    {ciudad: "Canelones", paiseCodigoAlfa: "URY"},
    {ciudad: "Dolores", paiseCodigoAlfa: "URY"},
    {ciudad: "Carmelo", paiseCodigoAlfa: "URY"},
    {ciudad: "Bella Unión", paiseCodigoAlfa: "URY"},
    {ciudad: "Young", paiseCodigoAlfa: "URY"},
    {ciudad: "Santa Lucía", paiseCodigoAlfa: "URY"},
    {ciudad: "Progreso", paiseCodigoAlfa: "URY"},
    {ciudad: "Paso Carrasco", paiseCodigoAlfa: "URY"},
    {ciudad: "Joaquín Suárez", paiseCodigoAlfa: "URY"},
    {ciudad: "Nueva Helvecia", paiseCodigoAlfa: "URY"},
    {ciudad: "General Líber Seregni", paiseCodigoAlfa: "URY"},
    {ciudad: "Río Branco", paiseCodigoAlfa: "URY"},
    {ciudad: "Toledo", paiseCodigoAlfa: "URY"},
    {ciudad: "Paso de los Toros", paiseCodigoAlfa: "URY"},
    {ciudad: "Juan Lacaze", paiseCodigoAlfa: "URY"},
    {ciudad: "Punta del Este", paiseCodigoAlfa: "URY"},
    {ciudad: "Parque del Plata", paiseCodigoAlfa: "URY"},
    {ciudad: "Piriápolis", paiseCodigoAlfa: "URY"},
    {ciudad: "Libertad", paiseCodigoAlfa: "URY"},
    {ciudad: "Rosario", paiseCodigoAlfa: "URY"},
    {ciudad: "Nueva Palmira", paiseCodigoAlfa: "URY"},
    {ciudad: "Chuy", paiseCodigoAlfa: "URY"},
    {ciudad: "Atlántida", paiseCodigoAlfa: "URY"},
    {ciudad: "Cardona", paiseCodigoAlfa: "URY"},
    {ciudad: "Lascano", paiseCodigoAlfa: "URY"},
    {ciudad: "Castillos", paiseCodigoAlfa: "URY"},
    {ciudad: "Pan de Azúcar", paiseCodigoAlfa: "URY"},
    {ciudad: "Tranqueras", paiseCodigoAlfa: "URY"},
    {ciudad: "Sarandí del Yí", paiseCodigoAlfa: "URY"},
    {ciudad: "San Ramón", paiseCodigoAlfa: "URY"},
    {ciudad: "Tarariras", paiseCodigoAlfa: "URY"},
    {ciudad: "Sauce", paiseCodigoAlfa: "URY"},
    {ciudad: "Sarandí Grande", paiseCodigoAlfa: "URY"},
    {ciudad: "José Pedro Varela", paiseCodigoAlfa: "URY"},
    {ciudad: "Tala", paiseCodigoAlfa: "URY"},
    {ciudad: "Guichón", paiseCodigoAlfa: "URY"},
    {ciudad: "La Paloma", paiseCodigoAlfa: "URY"},
    {ciudad: "Caracas", paiseCodigoAlfa: "VEN"},
    {ciudad: "Maracaibo", paiseCodigoAlfa: "VEN"},
    {ciudad: "Valencia", paiseCodigoAlfa: "VEN"},
    {ciudad: "Barquisimeto", paiseCodigoAlfa: "VEN"},
    {ciudad: "Maracay", paiseCodigoAlfa: "VEN"},
    {ciudad: "Ciudad Guayana", paiseCodigoAlfa: "VEN"},
    {ciudad: "Barcelona", paiseCodigoAlfa: "VEN"},
    {ciudad: "San Cristóbal", paiseCodigoAlfa: "VEN"},
    {ciudad: "Maturín", paiseCodigoAlfa: "VEN"},
    {ciudad: "Barinas", paiseCodigoAlfa: "VEN"},
    {ciudad: "Ciudad Bolívar", paiseCodigoAlfa: "VEN"},
    {ciudad: "Cumaná", paiseCodigoAlfa: "VEN"},
    {ciudad: "Mérida", paiseCodigoAlfa: "VEN"},
    {ciudad: "Valera", paiseCodigoAlfa: "VEN"},
    {ciudad: "Cabimas", paiseCodigoAlfa: "VEN"},
    {ciudad: "Santa Teresa del Tuy", paiseCodigoAlfa: "VEN"},
    {ciudad: "Punto Fijo", paiseCodigoAlfa: "VEN"},
    {ciudad: "Acarigua", paiseCodigoAlfa: "VEN"},
    {ciudad: "Los Teques", paiseCodigoAlfa: "VEN"},
    {ciudad: "Coro", paiseCodigoAlfa: "VEN"},
    {ciudad: "Guanare", paiseCodigoAlfa: "VEN"},
    {ciudad: "Ciudad Ojeda", paiseCodigoAlfa: "VEN"},
    {ciudad: "Puerto Cabello", paiseCodigoAlfa: "VEN"},
    {ciudad: "Guarenas", paiseCodigoAlfa: "VEN"},
    {ciudad: "Puerto La Cruz", paiseCodigoAlfa: "VEN"},
    {ciudad: "Guatire", paiseCodigoAlfa: "VEN"},
    {ciudad: "Turmero", paiseCodigoAlfa: "VEN"},
    {ciudad: "Tocuyito", paiseCodigoAlfa: "VEN"},
    {ciudad: "El Tigre", paiseCodigoAlfa: "VEN"},
    {ciudad: "Carora", paiseCodigoAlfa: "VEN"},
    {ciudad: "La Victoria", paiseCodigoAlfa: "VEN"},
    {ciudad: "Cabudare", paiseCodigoAlfa: "VEN"},
    {ciudad: "Carúpano", paiseCodigoAlfa: "VEN"},
    {ciudad: "San Fernando de Apure", paiseCodigoAlfa: "VEN"},
    {ciudad: "Guacara", paiseCodigoAlfa: "VEN"},
    {ciudad: "El Tocuyo", paiseCodigoAlfa: "VEN"},
    {ciudad: "Los Guayos", paiseCodigoAlfa: "VEN"},
    {ciudad: "Santa Rita", paiseCodigoAlfa: "VEN"},
    {ciudad: "Guigue", paiseCodigoAlfa: "VEN"},
    {ciudad: "Anaco", paiseCodigoAlfa: "VEN"},
    {ciudad: "San Juan de Los Morros", paiseCodigoAlfa: "VEN"},
    {ciudad: "Quibor", paiseCodigoAlfa: "VEN"},
    {ciudad: "El Vigía", paiseCodigoAlfa: "VEN"},
    {ciudad: "Palo Negro", paiseCodigoAlfa: "VEN"},
    {ciudad: "San Felipe", paiseCodigoAlfa: "VEN"},
    {ciudad: "San Carlos", paiseCodigoAlfa: "VEN"},
    {ciudad: "Mariara", paiseCodigoAlfa: "VEN"},
    {ciudad: "Villa de Cura", paiseCodigoAlfa: "VEN"},
    {ciudad: "Ocumare del Tuy", paiseCodigoAlfa: "VEN"},
    {ciudad: "Yaritagua", paiseCodigoAlfa: "VEN"},
    {ciudad: "Cúa", paiseCodigoAlfa: "VEN"},
    {ciudad: "Araure", paiseCodigoAlfa: "VEN"},
    {ciudad: "Calabozo", paiseCodigoAlfa: "VEN"},
    {ciudad: "Táriba", paiseCodigoAlfa: "VEN"},
    {ciudad: "Guasdualito", paiseCodigoAlfa: "VEN"},
    {ciudad: "Puerto Ayacucho", paiseCodigoAlfa: "VEN"},
    {ciudad: "Machiques", paiseCodigoAlfa: "VEN"},
    {ciudad: "Cagua", paiseCodigoAlfa: "VEN"},
    {ciudad: "Porlamar", paiseCodigoAlfa: "VEN"},
    {ciudad: "Charallave", paiseCodigoAlfa: "VEN"},
    {ciudad: "La Asunción", paiseCodigoAlfa: "VEN"},
    {ciudad: "Valle de la Pascua", paiseCodigoAlfa: "VEN"},
    {ciudad: "Santa Lucía", paiseCodigoAlfa: "VEN"},
    {ciudad: "Trujillo", paiseCodigoAlfa: "VEN"},
    {ciudad: "El Valle del Espiritu Santo", paiseCodigoAlfa: "VEN"},
    {ciudad: "Tinaquillo", paiseCodigoAlfa: "VEN"},
    {ciudad: "Puerto Píritu", paiseCodigoAlfa: "VEN"},
    {ciudad: "El Limón", paiseCodigoAlfa: "VEN"},
    {ciudad: "Socopó", paiseCodigoAlfa: "VEN"},
    {ciudad: "Boconó", paiseCodigoAlfa: "VEN"},
    {ciudad: "Punta de Mata", paiseCodigoAlfa: "VEN"},
    {ciudad: "Ejido", paiseCodigoAlfa: "VEN"},
    {ciudad: "Upata", paiseCodigoAlfa: "VEN"},
    {ciudad: "Rubio", paiseCodigoAlfa: "VEN"},
    {ciudad: "Caja Seca", paiseCodigoAlfa: "VEN"},
    {ciudad: "Catia La Mar", paiseCodigoAlfa: "VEN"},
    {ciudad: "Tumeremo", paiseCodigoAlfa: "VEN"},
    {ciudad: "Cantaura", paiseCodigoAlfa: "VEN"},
    {ciudad: "La Grita", paiseCodigoAlfa: "VEN"},
    {ciudad: "Santa Bárbara del Zulia", paiseCodigoAlfa: "VEN"},
    {ciudad: "Tucupita", paiseCodigoAlfa: "VEN"},
    {ciudad: "San José de Guanipa", paiseCodigoAlfa: "VEN"},
    {ciudad: "Chivacoa", paiseCodigoAlfa: "VEN"},
    {ciudad: "Lechería", paiseCodigoAlfa: "VEN"},
    {ciudad: "Zaraza", paiseCodigoAlfa: "VEN"},
    {ciudad: "Nirgua", paiseCodigoAlfa: "VEN"},
    {ciudad: "Siquisique", paiseCodigoAlfa: "VEN"},
    {ciudad: "Guanta", paiseCodigoAlfa: "VEN"},
    {ciudad: "Morón", paiseCodigoAlfa: "VEN"},
    {ciudad: "Pariaguán", paiseCodigoAlfa: "VEN"},
    {ciudad: "San Juan de Colón", paiseCodigoAlfa: "VEN"},
    {ciudad: "San Joaquín", paiseCodigoAlfa: "VEN"},
    {ciudad: "San Antonio de los Altos", paiseCodigoAlfa: "VEN"},
    {ciudad: "Caicara del Orinoco", paiseCodigoAlfa: "VEN"},
    {ciudad: "Achaguas", paiseCodigoAlfa: "VEN"},
    {ciudad: "Biruaca", paiseCodigoAlfa: "VEN"},
    {ciudad: "Pampatar", paiseCodigoAlfa: "VEN"},
    {ciudad: "La Guaira", paiseCodigoAlfa: "VEN"},
    {ciudad: "Maiquetía", paiseCodigoAlfa: "VEN"},

]

module.exports = { ciudades };
